### ISSUE TITLE
Custom Content Product Looping Breaking Section

### ISSUE THREAD

**Issue by adriancorcoran** [Shopify/liquid#1007]
### Problem
When adding a **custom content section** to the store, if a product is selected, then the handle of the product is taken as the section setting. Therefore when displaying the product, the section filters all products for the handle and displays the product - **in each loop**.

This means when multiple **custom content sections**, each with multiple loops it causes a fatal error after approx. 20 products. Error is `Liquid error (line 86): Exceeded maximum number of unique handles for all_products`

![](https://screenshot.click/08-53-xyb69-4smnb.jpg)

### Scope
Section and Code found in [Debut] , [Narrative]  - not in the other 8

### Expected vs Actual

**Expected**
Expect section to function continuously, regardless of number of sections:
![](https://screenshot.click/08-53-ul50q-42ioc.jpg)

**Actual**
Section is breaking if more than 20 individual product components are added using this section
![](https://screenshot.click/08-53-xyb69-4smnb.jpg)

### Replication Steps

**1.** In Debut, go to the theme editor and add a **Custom Content** section.

**2.** In the section, add 4 **Product** content types.

**3.** Repeat steps (1 & 2) six times and the section will break.

### More Information
No related issues, it's probably happening because there must be a maximum limit on the number of calls to product handles on the page.

### Suggestions

*This is a temporary fix, but not a long term solution. I would suggest something similar but also to look at the max. number of calls per page*

**Fix can be implemented by:**

**1.** Create a Collection, with conditions that contain any product with a price > 0.00 - *this will in effect be a collection which holds all products and name it* **All**

**2.** At the start of the **Custom Content** section code, create a variable called `all_my_products` which is assigned to the **All** collection. *This variable will then hold a reference to all products on the store, which prevents this data being retrieved in each loop.*

`{%- assign all_my_products = collections['all'].products %} `

![](https://screenshot.click/01-54-z8pi7-hb5uf.jpg)

**3.** When in the loop, instead of looping and filtering through all products each time, use the `all_my_products` variable and a loop instead instead:

*Replace this:*
```
{% when 'product' %}
{%- assign product = all_products[block.settings.product] -%}
```

*With this:*
```
{% when 'product' %}
{% for tmp_product in all_my_products %}
{% if tmp_product.handle == block.settings.product %}
{%- assign product = tmp_product -%}
{% break %}
{% endif %}
{% endfor %}
```

**Comment by shopmike** [comment]
@adriancorcoran closing as this is a limit set within Shopify on the `all_products` object and not directly related to the Liquid library. 

I'd recommend if you're trying to implement something like this, I would be setting up each row as a collection section as this will not have the same limitation as you have hit here.

**Comment by adriancorcoran** [comment]
Thanks Mike, I wasn't looking to change the Shopify limit, just that the way the sections in those two themes handle the looping, it could be made into a non-issue by changing the code - however with sections everywhere coming it's now probably redundant :)
