### ISSUE TITLE
capture surrounds strings by spaces

### ISSUE THREAD

**Issue by Ana06** [Shopify/liquid#1008]
I am using Jekyll and I have the following code:

```
{% capture short_name %}
hello
{% endcapture %}
```

With that code the `short_name` variable is assigned to ` hello `, surrounded by spaces, which seems to be a bug. I am not sure if I should report this to Jekyll instead.

Maybe related to the already closed https://github.com/Shopify/liquid/issues/783

**Comment by fw42** [comment]
You can get around this by using
```
{% capture short_name %}hello{% endcapture %}
```
or
```
{% capture -%}
hello
{%- endcapture %}
```
should work too

**Comment by Ana06** [comment]
@fw42 is then this expected? If so, it may be a good idea to update the documentation, as there are no spaces here: https://help.shopify.com/themes/liquid/tags/variable-tags :wink:

**Comment by fw42** [comment]
Thanks! Will take a look
