### ISSUE TITLE
Is there a port of Liquid for Python ?

### ISSUE THREAD

**Issue by DanisHack** [Shopify/liquid#1009]
I am looking for a port of Liquid for Python. Please help.

**Comment by adamhollett** [comment]
There doesn't seem to be. It seems someone was working on [a wrapper](https://github.com/doctaphred/liquid.py) but that was a while ago. [This StackOverflow post](https://stackoverflow.com/questions/3642192/does-python-have-a-safe-user-editable-script-markup-for-templates-like-rors-li) links to a bunch of other Python template languages you might consider.

**Comment by pwwang** [comment]
See https://github.com/pwwang/liquid.py
