### ISSUE TITLE
Converting text to a number

### ISSUE THREAD

**Issue by RobbStar** [Shopify/liquid#1017]
I am new with liquid and I am unable to convert the element accessed as text to a number.
I tried plus: 0 and times: 1 and also tried convert: "number". Can you tell me where am I going wrong.
Here is part of the code

{% assign iSumOfQuantity = 0 %}
        {% for row in table.rows %}
            {% assign iQuanityColumn = 0 %}
        <tr>
            {% for cell in row.cells %}
            
            {% if iQuanityColumn == 3 %}
                {% assign iSumOfQuantity = cell.text | plus: iSumOfQuantity %} //HERE IS THE ISSUE
            {% endif %}
            
            {% assign iQuanityColumn = iQuanityColumn | plus: 1 %}
            
            <td style="padding: 5px 10px; text-align: {{ table.columns[forloop.index0].align }}; border-left-width: 1px{% if forloop.last == true %}; border-right-width: 1px{% endif %}{% if table.columns[forloop.index0].nowrap %}; white-space: nowrap; width: 80px{% endif %}">{{ cell.text | newline_to_br }}</td>
            {% endfor %}
        </tr>
        {% endfor %}
<tr><p>
        {{iSumOfQuantity}}</p>
        </tr>

It takes the iSumOfQuantity as string and concatenates the further values instead of taking it as a number

**Comment by cswing-github** [comment]
Use ” | plus: 0 “ filter.

**Comment by adamhollett** [comment]
I don't know if this will work, but give it a try:

```
{% assign iSumOfQuantity = 0 %}
{% for row in table.rows %}
  {% assign iQuanityColumn = 0 %}

  {% for cell in row.cells %}

    {% if iQuanityColumn == 3 %}
      {% assign numToAdd = cell.text | times: 1.0 %} // <-- this is new, should convert cell.text to a number
      {% assign iSumOfQuantity = numToAdd | plus: iSumOfQuantity %}
    {% endif %}
        
    {% assign iQuanityColumn = iQuanityColumn | plus: 1 %}
        
    <td style="padding: 5px 10px; text-align: {{ table.columns[forloop.index0].align }}; border-left-width: 1px{% if forloop.last == true %}; border-right-width: 1px{% endif %}{% if table.columns[forloop.index0].nowrap %}; white-space: nowrap; width: 80px{% endif %}">{{ cell.text | newline_to_br }}</td>
  {% endfor %}
  </tr>
{% endfor %}

{{ iSumOfQuantity }}
```


Also, you might have a typo: `iQuanityColumn` should probably be `iQuantityColumn`.

**Comment by shopmike** [comment]
Closing as this looks like it has been resolved.
