### ISSUE TITLE
Possible to customize the rendering of liquid objects?

### ISSUE THREAD

**Issue by dmalan** [Shopify/liquid#1019]
Is it possible to customize how liquid objects are rendered so that, e.g., if `foo` is a hash with certain keys, then

```
{{ foo }}
```

is actually rendered in a certain way (e.g., as a definition list in HTML)? Or, alternatively, if `foo` is a list, it's rendered as an unordered list in HTML? For simplicity, we'd prefer not to require that `foo` be passed to a plugin or filter, instead just inferring by its structure how it should be rendered. If monkey-patching is the only option, what might be the best place among https://github.com/Shopify/liquid/tree/master/lib/liquid to inject such customized behavior?

Thank you!

**Comment by dylanahsmith** [comment]
You could use a [Liquid::Drop](https://github.com/Shopify/liquid/wiki/Introduction-to-Drops) and define the `to_s` method.

**Comment by fw42** [comment]
@dmalan: Did that answer your question? Can this be closed?
