### ISSUE TITLE
A Clojure port

### ISSUE THREAD

**Issue by superkonduktr** [Shopify/liquid#1020]
_(not technically an issue but a friendly epistle)_

Hi,
I'm the author of [wet](https://github.com/superkonduktr/wet), a Clojure/ClojureScript port of Liquid that has been battle-tested at [Flocktory](https://www.flocktory.com/en/), a (mainly) Clojure shop, for almost a year now. If you deem it worthy, I thought it would be great to put it on the [list of ports](https://github.com/Shopify/liquid/wiki/Ports-of-Liquid-to-other-environments) in the Liquid wiki. I'd also appreciate any comments or suggestions!

Cheers,
Aleksey

**Comment by adamhollett** [comment]
Thanks @superkonduktr! I've added it to the list of ports.
