### ISSUE TITLE
Vue.js syntax: Error with "Unexpected character $ (dollar sign)" 

### ISSUE THREAD

**Issue by alxmcr** [Shopify/liquid#1021]
Hi, Liquid's team:

I'm starting a personal blog with **Jekyll** and create some posts, but when I use the **Vue.js syntax**, I have a problem with the process of generating the files. It isn't completely successful. I have this warning: 

```
Liquid Warning: Liquid syntax error (line 6): Unexpected character $ in "{{ $route.params.id }}"
```

### How Can you reproduce this error?

1. Create a new Jekyll project (Source: [Quick-start Instructions](https://jekyllrb.com/)) 
```
$ gem install bundler jekyll
$ jekyll new my-awesome-site
````

2. Install the `kramdown` and `rouge` gems
```
$ gem install kramdown rouge 
```

I thought the problem was with `rouge` but [the problem apparently is not there](https://github.com/jneen/rouge/issues/971).

3. Update `_config.yml`

```
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
```

4. Create a New post Markdown (For example: `2018-08-14-vue-syntax.md`)
5. Copy these lines ([Gist - Button 'raw'](https://gist.github.com/alxmcr/4c87feab0d3f1edb4c8dc2f5bb2ab310) ):

![image](https://user-images.githubusercontent.com/8689897/44104850-ed772718-9fbd-11e8-91cc-d516570d9a79.png)

6.  Open the terminal

```
$ cd my-awesome-site
$ bundle exec jekyll serve
# => Now browse to http://localhost:4000
````

Unfortunately, you have this terminal output:

![image](https://user-images.githubusercontent.com/8689897/44105251-1afbf280-9fbf-11e8-8056-bfe478d85940.png)

And If you open your browser, you watch it:

![image](https://user-images.githubusercontent.com/8689897/44105348-6a32e714-9fbf-11e8-9008-b57e6205eb58.png)

**How can I solve this problem? Can you help me, please?** I'll appreciate it.

**Comment by dylanahsmith** [comment]
It looks like vue.js uses the same `{{` and `}}` like liquid, so I don't think they are compatible unless vue.js supports an alternative syntax.

**Comment by alxmcr** [comment]
Thank you so much! I will try with these tags `{% raw %}` and `{% endraw %}` .

**Comment by alxmcr** [comment]
Well, I used these tags `{% raw %}` and `{% endraw %}` in my code: 

![image](https://user-images.githubusercontent.com/8689897/44161554-abeaf300-a08b-11e8-868f-ac6aaa1f955f.png)


and **it works!** 

![image](https://user-images.githubusercontent.com/8689897/44161613-dfc61880-a08b-11e8-92d8-f6fbc281b7ef.png)

**Thanks for your help!**

I share your opinion 👍 , it's not so ideal. In my case, I did a few changes in my code, it's ok! but when the code is larger, it will be very complicated and confused to do the changes. I'm so sorry, this is my humble opinion. **Thanks for your help, again! I appreciate it so much** 😃.

**Comment by adamhollett** [comment]
I'm glad you were able to resolve your issues @alxmcr :)

I'm going to mark this issue as resolved.

**Comment by alxmcr** [comment]
Thanks @adamhollett ! Also, I'm happy 😄 !. Have a good day! 👍
