### ISSUE TITLE
Bug with "product" schema type

### ISSUE THREAD

**Issue by sam327** [Shopify/liquid#1022]
When I have a product link type, it selects correctly in the customizer, but the link shows the wrong URL.

I've got a block on a page to showcase some specific seasonal items. And this mostly works.

     "blocks": [{
          "name": "Product List",
          "type":"pageblock",
          "settings": [
               {
                    "type": "text",
                    "id": "prodname",
                     "label": "Product Name"
               },
               {
                    "type": "product",
                    "id": "linkurl",
                    "label": "Link to item"
               }]

And then I've got a bit of code on my front-end that looks like:

    {% for block in section.blocks %} 
    {% if block.settings.linkurl %}
        <div class="buylink">
            <a href="{{ block.settings.linkurl }}" class="button">{{ block.settings.prodname }}</a>
        </div>
    {% endif %}
    {% endfor %}

So, nothing weird so far.

Hop over to the customizer, and hit the 'select product' button, and that all looks nice. However, the URL I get on my front-end ends up being mywebsite.com/_pages_/product-name - and this is wrong.

It I change _type_ from "product" to "url" - the selector isn't as pretty in the admin panel, but the front end URL is correct - mywebsite.com/_products_/product-name

I'm not sure if it's because it's in a block that it's weird, or if there are other extenuating circumstances.

**Comment by fw42** [comment]
This sounds like a Shopify problem. This repository is about Liquid, not about how Liquid is being used by the Shopify application (Liquid itself doesn't have a concept of pages, products, blocks, ...).

**Comment by sam327** [comment]
Ah. Whoops. Apologies. Shopify support sent me here.
