### ISSUE TITLE
custom variable

### ISSUE THREAD

**Issue by MiladRahmani** [Shopify/liquid#1023]
Is it possible to  create custom variable in liquid ?
E.g in {{ x | A | B }} do that if x > 10 show "A" else show "B" and "A" , "B" can change by user
Thank you

**Comment by callaginn** [comment]
Yes, use "assign" or "capture" to create a custom variable:
https://help.shopify.com/en/themes/liquid/tags/variable-tags#assign
https://help.shopify.com/en/themes/liquid/tags/variable-tags#capture

You can add conditional statements with "if", "unless", or "case" tags:
https://help.shopify.com/en/themes/liquid/tags/control-flow-tags#if

**Comment by MiladRahmani** [comment]
Yes that's right but i want to use if else statment in one line, that mean that if 'x' was true show 'A' else show 'B'
Can you help me, please?

**Comment by callaginn** [comment]
Like this?
```
{% assign x = '12' %}
{% if x > 10 %}{{ a }}{% else %}{{ b }}{% endif %}
```

**Comment by shopmike** [comment]
@callaginn has provided the cleanest option thats currently possible. I think you may also be referring to a ternary operator, sadly Liquid does not have this functionality.
