### ISSUE TITLE
Detect Site Environment Using Liquid

### ISSUE THREAD

**Issue by callaginn** [Shopify/liquid#1029]
_I already tried asking this in the official Shopify Forums, but that community seems dead. Hoping I can get some help with this issue over here:_

---

We're trying to display extra debugging information for any site that is viewed via a development address (*.myshopify.com or localhost:3000) using Liquid.

We used to be able to do this with [FreakDesign's liquid code](https://freakdesign.com.au/blogs/news/34154561-detect-if-shopify-admin-is-logged-in-using-liquid). However, changes were made on Shopify's end that broke this functionality:

I viewed the site's source code via Slate v1's "https://localhost:3000" address and saw several references to "localhost" within the "content_for_header" object. However, adjusting the code to look like the following does NOT work:

```
{% capture CFH %}{{ content_for_header  }}{% endcapture %}{{ CFH }}

{% if CFH contains 'localhost' %}
    {% assign isAdmin = true %}
{% endif %}
```

Since I noticed the {{ canonical_url }} object prints "//localhost:3000/" in my source code, I tried this statement -- which also doesn't work:

```
{% if canonical_url contains 'localhost' %}
    This is a DEV site
{% endif %}
```
Splitting apart that object, shows my LIVE address, instead of localhost:3000. What the?
```
{{ canonical_url | split: '/' }}
```
The {{ shop.secure_url }} object prints "//localhost:3000/" in my localhost environment's source code. However, the following code didn't work either:

```
{% if shop.secure_url contains 'localhost' %}
    This is a DEV site
{% endif %}
```
Curiously, splitting that variable apart via the following code causes it to print a *.myshopify.com address in my localhost environment.
```
{{ shop.secure_url | split: '/' }}
```
Does anyone have any idea how I can accomplish this OR why splitting apart certain objects causes them to show a completely different adress? I even tried capturing those objects into a new variable and spitting apart that variable. However, if I hardcode those object values, it works.

**Comment by pushrax** [comment]
Wow, that’s some strange behaviour. If this is a local environment though, you have full control over the code that’s running and should be able to pinpoint the error by tracing forward from initialization or back through variable evaluation. Probably easier to go backward in this case; start by placing a breakpoint in VariableLookup#evaluate and checking out the parameters. If you’re not familiar with Ruby debuggers, perhaps try dumping all the variables before they are passed to liquid.

The only reason I can think of is if the dropped object has a different to_s than to_liquid, something like this might be possible.

**Comment by shopmike** [comment]
@callaginn This is because slate is just modifying these values to run a form of HMR (Hot Module Replacement). So the reason `content_for_header` is reporting the Shopify address is that Shopify is actually processing the template, but slate is modifying it after the fact so that it can live reload your CSS, JS, etc. 

If you wanted to find a way to detect this I would suggest the slate project would be the best place to open an issue as this functionality is specific to them.
