### ISSUE TITLE
How to check if content of a string is whitspace

### ISSUE THREAD

**Issue by victormayworm** [Shopify/liquid#1030]
Hi,

i'm trying to check if the value of my variable is whitespace. I want use this liquid script to do this:

```
{%- assign my_variable = '       ' -%}
{%- if my_variable | strip == '' -%}
the string is empty or whitespace
{%- endif -%}
```

with this code the result is ever "the string is....", same if the value of my_variable is empty, whitespace or a valid string, like "liquid" for example. To solve this problem i needed assign the result of the filter to a variable and check this result on if statement:

```
{%- assign my_variable = '       ' -%}
{%- assign my_variable_strip = my_variable | strip -%}
{%- if my_variable_strip == '' -%}
the string is empty or whitespace
{%- endif -%}
```

realy there's no way to use the filter to check if my_variable is empty or whitespace on if statement? Why i can't do this?

sorry for bad english!

**Comment by pushrax** [comment]
Liquid doesn't support filters in expressions. Coincidentally, this is something we've been discussing potentially changing. I'm planning to write a proposal soon.

For the moment, the answer to this issue is simply that it's unsupported.

**Comment by victormayworm** [comment]
Ok. Thanks.
