### ISSUE TITLE
'size' operator incorrect value when combined with 'capture'

### ISSUE THREAD

**Issue by OpenSpacesAndPlaces** [Shopify/liquid#1035]
Given a sample like:
`{% capture sText | strip %}   {% endcapture %}`

This works and reports length 0:
`{% assign iLength = sText | strip | size %}`

This reports a length of 3
```
{{sText.size}}
'{{sText}}'
```
and a value of ' '

----

In my specific case the length was reported as 240 characters and the text returned is ' '.
The even stranger part is the returned value for sText is still ' ' even when "| strip" is omitted.
So it's not readily clear where the 240 characters is being reported from.

---

We're using 'DotLiquid' 2.0.298 on .Net Framework 4.7.1.

**Comment by pushrax** [comment]
`{% capture sText | strip %}` is not valid syntax. Regex-based parsers end up treating it as `{% capture sText %}`.

You can use `{% capture sText %} {% endcapture %}{% assign sText = sText | strip %}`
