### ISSUE TITLE
(chore): Version Bump for PR #930 merge

### ISSUE THREAD

**Issue by tannermares** [Shopify/liquid#1037]
### What is the issue?
#930 was just merged a couple days ago but the version was not bumped. 🤗

**Comment by fw42** [comment]
We don't need to bump the version after every PR that gets merged. Only when we actually want to make a new Rubygems release.

**Comment by tannermares** [comment]
@fw42 ok no prob. I'll link to the commit for now.

**Comment by fw42** [comment]
I didn't mean to say we can't release a new version :-) If that's what you need, I'm happy to do that. Will take a look tomorrow.

**Comment by tannermares** [comment]
@fw42: Yeah that would be great! Thanks!

**Comment by fw42** [comment]
Done (https://rubygems.org/gems/liquid/versions/4.0.1)
