### ISSUE TITLE
Comment form submit forces user away from comment form area

### ISSUE THREAD

**Issue by Marcus-Seoighe** [Shopify/liquid#1045]
## Comment area - Theme Issues

**Problem**
It would seem that Shopify is forcing the submit action on forms to direct to `{URL}#comments` instead of what’s specified in the form `action` - an example is when a form is trying to use an anchor like `.../#comment_form` to keep the user on the form section to see the notification.

Expected vs Actual
When form submitted that the user would stay in the form section to be able to see the notification after the form was submitted. 

**More Information**
Once the comment form is submitted, then the redirect sends the user back to the top of the comments section - instead of to the top of the comment form so that the user can see the response given from their submitted form. 
Here's a vid of it in action:
https://screenshot.click/19-01-qau5u-1au4l.mp4
You can reproduce that here: https://warehouse-development.myshopify.com/blogs/news/10-types-of-camera-bags-and-what-to-ask-before-buying-them
The 'new comment' form, you can see that it is expected to redirect to: `/blogs/news/10-types-of-camera-bags-and-what-to-ask-before-buying-them/comments#comment_form` (with the anchor `#comment_form`) but it actually forces it to go to the top of the comments section.
![Alt Text](https://screenshot.click/19-59-y0l9d-qzr36.jpg)

**Replication Steps**
Tested the comments form on a few themes in my test store and found that some theme partners worked around this by placing the notification on the top of the comments area:
![Alt Text](https://screenshot.click/19-03-hugnt-hb5vt.jpg)

**Other examples**
Also tested using the Debut theme which just jumps back to the top of the page when submit is actioned: Debut: https://screenshot.click/19-10-5tl8s-yu6tw.mp4

**Pings:**
@Tetsuro

**Comment by fw42** [comment]
Is this related to the Liquid templating system?

**Comment by shopmike** [comment]
Closing due to being related to Shopify Themes
