### ISSUE TITLE
Passing a tag argument to File.open yields rb_sysopen

### ISSUE THREAD

**Issue by ghost** [Shopify/liquid#1050]
When accepting a tag argument, such as `{% my_tag argument_name %}` and then passing it to `File.open` or any other function that reads from disk, it'll fail with:

```
Liquid Exception: No such file or directory @ rb_sysopen - (PATH) in index.html
jekyll 3.8.5 | Error:  No such file or directory @ rb_sysopen - (PATH)
```

This occurred to me while writing a Jekyll plugin that loads a CSV file based on a tag argument. Interestingly enough, based on reports from a friend, it seems to work fine on Windows.

Here's a reproduction repository: https://github.com/oe/repro-plugindir

I'm not _completely_ sure this is related to Liquid, but since Jekyll does relatively little between defining a Tag and executing it, I thought I'd file this here.

**Comment by pushrax** [comment]
This sounds like a working directory issue, unrelated to Liquid. That error comes from [`rb_syserr_fail_path`](https://github.com/ruby/ruby/blob/803dcea481ea20fc7dfc690e73ccb23646a5c4ab/internal.h#L1509) via [`rb_sysopen`](https://github.com/ruby/ruby/blob/803dcea481ea20fc7dfc690e73ccb23646a5c4ab/io.c#L5970) and simply indicates the file does not exist.

```
irb(main):001:0> File.open('doesntexist')
Traceback (most recent call last):
        4: from /usr/local/bin/irb:11:in `<main>'
        3: from (irb):1
        2: from (irb):1:in `open'
        1: from (irb):1:in `initialize'
Errno::ENOENT (No such file or directory @ rb_sysopen - doesntexist)
```
