### ISSUE TITLE
strip_html is too aggressive, does not replace images by their alt text

### ISSUE THREAD

**Issue by Crissov** [Shopify/liquid#1052]
I came here because Jekyll or a a plugin used by the theme I'm using tries to populate `page.title` from the first markdown heading (third level or higher) and [uses](https://github.com/benbalter/jekyll-titles-from-headings/blob/master/lib/jekyll-titles-from-headings/generator.rb) `strip_html` for that. At least, that is what I think is happening. Maybe the plugin should be doing that differently, but the problem remains: `strip_html` does not retain fallback textual content like `<img alt="this"/>`.

Original markdown input:

```` markdown
# ![foo](bar) baz
````

Intermediary HTML throughput:

```` html
<h1><img src="bar" alt="foo" /> baz</h1>
````

Actual output (value of `page.title`):

````
baz
````

Expected output:

````
foo baz
````

[`standardfilters.rb`](https://github.com/Shopify/liquid/blob/master/lib/liquid/standardfilters.rb#L104):

```` ruby
    def strip_html(input)
      empty = ''.freeze
      input.to_s.gsub(/<script.*?<\/script>/m, empty).gsub(/<!--.*?-->/m, empty).gsub(/<style.*?<\/style>/m, empty).gsub(/<.*?>/m, empty)
    end
````

This would need just another `.gsub()`, something like `/<img\s[^>]*?alt\s*=\s*(?:"([^"]*)"|'([^']*)')[^>]*?>/m`. 

There are some other HTML elements with fallback attributes like that, but they are unlikely to be generated from markdown inside a heading, so I do not care as much about them right now.

**Comment by adamhollett** [comment]
This is an interesting issue! I understand the problem you're having, but from a code perspective `#strip_html` is doing what it's intended to. It's stripping all the HTML code from the string. It's not likely that we'd be able to change the behaviour of a standard Liquid filter at this point.

It seems like this use case is something that might be better handled in the plugin you're using! But I'll let someone else weigh in as well.

**Comment by pushrax** [comment]
> It seems like this use case is something that might be better handled in the plugin you're using! But I'll let someone else weigh in as well.

Agree, converting HTML to text is a different operation than stripping HTML, and doing this generally is a rather complex operation. The plugin can make assumptions about the input and implement the minimal requirement to render page titles correctly.

The `strip_html` filter is mainly used to prevent XSS/script injection, so it doesn't need to care about encoded characters. Usually Liquid is rendering to an output format that supports those encoded characters anyway. If we decode them, we'd have to strip HTML from the decoded string to be safe. If we strip them, the output will look quite different.

Going to close as wontfix since it seems clear the right level of abstraction to solve this particular problem is in the referenced plugin.

**Comment by Crissov** [comment]
I humbly disagree. Liquid seems like the perfect place for this filter, but I understand that it needs a new name, e.g. `flatten_html`.

**Comment by pushrax** [comment]
So far I've not seen that converting HTML to text in a semantically aware way is not a common operation to do inside a Liquid template. Every filter we add needs to be supported for all time and in every implementation of Liquid (in other languages), so we avoid this cost unless it's clear template authors will benefit.

The plugin referenced happens to be using this Liquid filter and a couple Jekyll filters in this path, but it's not a Liquid template itself. It could easily use its own method to do this.

**Comment by pkiula** [comment]
Shopify had to reinvent the wheel with their own new language. This would be trivial in PHP or Python or JS. Strip_tags, but leave certain exception tags in there like A or UL/LI. So stupid.
