### ISSUE TITLE
How to get shopify checkout variables in my custom web page on payments

### ISSUE THREAD

**Issue by rohitsdd** [Shopify/liquid#1056]
We are trying to track ecommerce revenue from our webstores. We can see the data being sent from our "product" page source but the revenue is still at $0 in google analytics.  How to get shopify checkout variables in my custom we page on payments so that I trigger google analytics event of payment processed.

1. Ecommerce is turned on

2. Enhanced ecommerce is also turned on

4. This is our header script

<script>
    (function (w, d, s, l, i) {
      w[l] = w[l] || []; w[l].push({
        'gtm.start':
          new Date().getTime(), event: 'gtm.js'
      }); var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
          'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
    })(window, document, 'script', 'dataLayer', 'GTM-53K27J6');
  </script>

<script>
    (function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function () {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
    ga('create', 'UA-108527695-1', 'auto', { allowLinker: true });
    ga('require', 'linker');
    ga('linker:autoLink', ['prairie-supply.myshopify.com, getsunday.com']);
    ga('send', 'pageview');
  </script>

5. Also add the tracking id in (storename.myshopify.com/admin/online_store/preferences) Google Analytics account section

6. add Additional scripts in (storename.myshopify.com/admin/settings/checkout)

<script>
(function (i, s, o, g, r, a, m) {
      i['GoogleAnalyticsObject'] = r;
      i[r] = i[r] || function () {
        (i[r].q = i[r].q || []).push(arguments)
      }, i[r].l = 1 * new Date();
      a = s.createElement(o),
        m = s.getElementsByTagName(o)[0];
      a.async = 1;
      a.src = g;
      m.parentNode.insertBefore(a, m)
    })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
ga('create', 'UA-108527695-1', 'auto', {allowLinker: true});
ga('require', 'linker');
ga('linker:autoLink', ['getsunday.com']);
ga('require', 'ecommerce');
        ga('ecommerce:addTransaction', {
          'id': checkout.order_id,
          'affiliation': '',
          'revenue': checkout.subtotal_price,
          'shipping': checkout.shipping_rate.price,
          'tax': checkout.total_tax
        });
        ga('ecommerce:addItem', {
              'id': line_item.product_id,
              'name': line_item.title,
              'sku': line_item.sku,
              'category': '',
              'price': line_item.price,
              'quantity': line_item.quantity
          });
    ga('ecommerce:send');
ga('send', 'pageview');
</script>
<script type="text/javascript">document.location= "https://getsunday.com/thank-you";</script>

Please let me know the correct steps to get those and help me here ASAP. Thanks in advance.

**Comment by fw42** [comment]
This is more of a question for Shopify support, not about the Liquid templating system and the Liquid Ruby gem itself (which this GitHub repository is about). Please reach out to theme support, they should be able to help you.
