### ISSUE TITLE
Cart count summary not displaying properly on initial add to cart button press?

### ISSUE THREAD

**Issue by youngruski** [Shopify/liquid#1060]
Hi everyone, 

Would really appreciate any guidance on this issue I've been having. 
Adding an item to cart with an "Add to Cart" button press shows the cart summary modal in the top right hand corner, but doesn't properly display the item added nor the item count in the cart icon. 

The cart technically functions fine and going to a different page and viewing the cart shows the original item added. A previous developer coded a lot of this site and I'm unable to figure out the issue. 
Site is https://www.alexmikajewelry.com. 

Can provide the cart.liquid code as well if someone wouldn't mind taking a quick look. Thank you!

**Comment by salexzee** [comment]
This doesn't sound like a liquid issue. It sounds more like an issue you would discuss with a developer who works on your site or the developer who created the theme you use.
