### ISSUE TITLE
Add platformOS to "Who uses Liquid" list on wiki

### ISSUE THREAD

**Issue by diana-lakatos** [Shopify/liquid#1063]
Could you please add us to the "Who uses Liquid" list on the wiki?

Company name: `platformOS` (starts with lowercase letter)
Link: https://www.platform-os.com 

I cloned the wiki and tried to add it myself, but got a permission denied error. 

Thank you!

**Comment by pushrax** [comment]
Added! We were getting a lot of spam so the wiki is restricted to committers now.

**Comment by diana-lakatos** [comment]
@pushrax I understand. Thank you very much for adding us!
