### ISSUE TITLE
[Liam] Add tracking to the GH Liquid page

### ISSUE THREAD

**Issue by liamgriffin** [Shopify/liquid#1064]
Right now we have to way to measure what level of traffic the GitHub page for Liquid is getting: https://shopify.github.io/liquid/

Tracking (via Google Analytics, or similar) should be added to this page to monitor site traffic. 

Next steps: Reach out to appropriate teams to see how best to add tracking.

**Comment by liamgriffin** [comment]
Lack of metrics tracking on this page referenced in recent Content Audit: https://docs.google.com/presentation/d/1SaqKUCBpBtBQEPaAioEjDdv9zMamUUo15cDt6NzqEuA/edit#slide=id.g4f0d93e5b0_0_0

**Comment by tiffanytse** [comment]
https://github.com/Shopify/liquid/pull/1081
