### ISSUE TITLE
Add comprehensive Liquid guide to "Stuff to read, watch, etc."

### ISSUE THREAD

**Issue by pavelloz** [Shopify/liquid#1067]
I've noticed that [wiki](https://github.com/Shopify/liquid/wiki) has a list of links with resources about Liquid under section **Stuff to read, watch, etc.**, so maybe it will be beneficial for users to also include this resource (which is a compilation of all resources i found on the internet + my own additions/edits):
 
I don't know how to call it, the closest i can think of is "comprehensive Liquid guide".

https://documentation.platform-os.com/api-reference/liquid/introduction

PS. Also fun fact, that webpage is written in liquid + markdown combination itself, which seems like a good combo for both logic and text formatting.

Thanks ;)

**Comment by shopmike** [comment]
Hey @pavelloz thanks for the suggestion, considering there are so many platforms using Liquid and each one has its own docs, I don't think we would be able to support linking all of these. In fact, the wiki doesn't link to either the Shopify or Jekyll docs at this point and they are the 2 biggest users as far as I know.

I'm sure people looking around will find and appreciate the docs you have done 👍
