### ISSUE TITLE
Using too few brackets doesn't raise parsing error

### ISSUE THREAD

**Issue by scottwhudson** [Shopify/liquid#1068]
Using v4.0.1

` temp = Liquid::Template.parse("unbalanced { brackets }}", error_mode: :strict)` doesn't return any kind of parse error.
`temp.errors #=> []`

In this case, the incorrect syntax just renders as a static string:

`temp.render("brackets" => "foo")` returns `"unbalanced { brackets }}"`

How can I handle a case of imbalanced brackets?

**Comment by pushrax** [comment]
Unfortunately this is completely valid Liquid; and is very common in HTML templates that include JavaScript, which makes use of single `{`. If your use case never allows this, you could search the template for any single `{` with a simple regex and raise an error.
