### ISSUE TITLE
Why can you do math operations on string?

### ISSUE THREAD

**Issue by Zyles** [Shopify/liquid#1076]
What is this behaviour?

```
{% assign number = 123asasasasasa %}
{% capture number_string_thing %}{{ number | times: 1 }}{% endcapture %}
{{ number_string_thing }}
```

**Comment by shopmike** [comment]
Liquid is designed to be simple for everyone, this means some of its behaviours are a little different than most programming languages as it's designed for beginners as well. 

As you have expressed that you want to apply a number filter to a string, it is doing a very fuzzy typecast to try and match the behaviour your after.
