### ISSUE TITLE
Ability to read collection contents that are filtered

### ISSUE THREAD

**Issue by paulhc** [Shopify/liquid#1085]
Would be really useful to be able to do a for-loop on a collection with a filter applied. e.g. to find products in a collection 'tagged with' a given tag. I can't tell you how many times I've found a situation where this would've been super helpful. e.g. to get a count of products with that tag without cycling through all products, to find products with a specific tag without trying to go through 1000 results in a big collection, to circumvent the 1000 limit by filtering is to there are fewer products or articles to iterate etc.

**Comment by shopmike** [comment]
Hey @paulhc, this is a known feature request inside Shopify. I agree this would be super useful so I'll also be pushing for this. As this isn't Liquid specific and is more just about providing a filter in Shopify I'm just closing this to keep the issues in here Liquid related.
