### ISSUE TITLE
how to set default value for bool variable

### ISSUE THREAD

**Issue by aimuke** [Shopify/liquid#1100]
```
{% assign varA = false %}
{{ varA | default: true }}
```
I want to get the value of varA, but, Liquiddefault filter will set the value only if “the left side is nil, false, or empty”. So I always get ture.
How sould I get the value of varA?  thx.

**Comment by fw42** [comment]
`{{ varA }}`?

**Comment by aimuke** [comment]
thanks. @fw42 .

The variable `varA` may be empty which  I want to set it to `true`.  If I use `{{ varA }}`, I cannot get the default value.

**Comment by ashmaroli** [comment]
## Workarounds
- If you just wanna render the value:
  ```
  {%- if varA == false -%}
    false
  {%- else -%}
    {{ varA | default: true }}
  {%- endif -%}
  ```
- Or if you're just gonna use it in a conditional:
  ```
  {%- if varA -%}
    cookie!
  {%- else -%}
    no cookie!
  {%- endif -%}
  ```

**Comment by aimuke** [comment]
thx, @ashmaroli 

Yes, I can do it like this. thx.

**Comment by CrazyOrr** [comment]
The [default filter](https://shopify.github.io/liquid/filters/default/)
> Allows you to specify a fallback in case a value doesn’t exist. default will show its value if the left side is nil, false, or empty.
This fallback rule doesn't apply when a variable has a boolean value of `false`, which is a valid value and doesn't need to be fallbacked on.

**Comment by dylanahsmith** [comment]
Looks like we are missing documentation on https://shopify.github.io/liquid/filters/default/ for the `allow_false` keyword argument to the default filter, although there is documentation for it in the source code https://github.com/Shopify/liquid/blob/c7c21e88f018af6a02095cd8161d065d2967ea21/lib/liquid/standardfilters.rb#L434-L437

**Comment by ashmaroli** [comment]
@dylanahsmith The [commit that introduced `allow_false`](https://github.com/Shopify/liquid/commit/f1d62978efe60e7b326a9f2ca5eeac7b39fc56ea) haven't been released yet. So, documenting it on https://shopify.github.io/liquid/filters/default/ is going to create confusion..
