### ISSUE TITLE
How to check if a string is English or Chinese? 

### ISSUE THREAD

**Issue by ChangyuYan** [Shopify/liquid#1101]
I am trying to filter my blog posts' tags. On the English page, I want to display the tags that are only English, and on the Chinese page, I want to display the tags that are only Chinese. 

I am looking for something like what's on the second line: 

```
{% for category in site.categories %}
    {% if category.lang == "en" %} 
        <p>
            <a href="{{ '/category/#'  | prepend: site.baseurl  }}{{ category | first }}"><i class="fa fa-angle-right"></i> {{ category | first | capitalize }}</a>
            <span class="badge badge-theme pull-right">{{ category | last | size }}</span>
        </p>
    {% endif %} 
{% endfor %}

```

Is there a syntax available already? 

Thank you!

**Comment by ashmaroli** [comment]
@ChangyuYan Unfortunately, Liquid does not detect the "locale" of a given string and neither does Jekyll.
You may have to look for third-party Jekyll plugins to provide this functionality.

**Comment by fw42** [comment]
If you are familiar with Ruby then this shouldn't be too difficult to implement yourself as a Jekyll plugin. 

Ruby actually has a built-in feature for this kind of stuff that you could use:
```
irb(main):001:0> "foo".match(/\p{Han}/)
=> nil
irb(main):002:0> "有難う".match(/\p{Han}/)
=> #<MatchData "有">
```
