### ISSUE TITLE
Unable to set default_resource_limits

### ISSUE THREAD

**Issue by Sexual** [Shopify/liquid#1105]
Attempting to setup an initializer, but I get a error indicating it cannot be set. Usaing the latest gem `liquid (4.0.3)`

```
 Liquid::Template.default_resource_limits = {render_score_limit: 1_000}
```

Error:
```
undefined method `default_resource_limits=' for Liquid::Template:Class Did you mean? default_resource_limits
```

Looking through the code, it doesn't actually seem like default_resource_limits is writeable.

**Comment by fw42** [comment]
Try `Liquid::Template.default_resource_limits[:render_score_limit] = 1000`, which should work.
