### ISSUE TITLE
Can't access XML Elements or JSON values with double curly braces

### ISSUE THREAD

**Issue by DavidKing0193** [Shopify/liquid#1106]
I'm currently working in Microsoft Logic Apps, and am attempting to transform an XML document into another form of XML. I've tried with the raw XML, and with the XML after it's been converted to JSON.

For example, here's a segment of my transformation:

`<BELNR>{{ AddSalesOrder.DataArea.SalesOrder.Header.DocumentsIds.DocumentId.Id }}</BELNR>`

AddSalesOrder is my root element and I've tried the above and below variations:

`<BELNR>{{ content.AddSalesOrder.DataArea.SalesOrder.Header.DocumentsIds.DocumentId.Id }}</BELNR>
<BELNR>{{ content.DataArea.SalesOrder.Header.DocumentsIds.DocumentId.Id }}</BELNR>`

But I always get back nil as the value. I know because I've stored the value in a variable and then fed it through an if-statement to check if it was nil, which it was.

Am I doing something wrong?

Let me know if I can provide more information.

**Comment by ashmaroli** [comment]
> Let me know if I can provide more information.

You could provide more background on how the objects are structured internally.
For the above code to work, your objects should resemble the following Ruby Hash (when it is converted into a Hash) irrespective of whether the root object is internally a `Liquid::Drop` instance or a Ruby `Hash` instance:
```ruby
"AddSalesOrder" => {
  "DataArea" => {
    "SalesOrder" => {
      "Header" => {
        "DocumentsIds" => {
          "DocumentId" => {
            "Id" => 123456
          }
        }
      }
    }
  }
}
```

**Comment by DavidKing0193** [comment]
Sure!

This is what the structure of the document looks like:

`<AddSalesOrder revision="8.0" tororevision="2.6" environment="Production" lang="en-US"
               xmlns="http://tempuri.org/AddSalesOrder_v2_6"
               xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:schemaLocation="http://tempuri.org/AddSalesOrder_v2_6 AddSalesOrder_v2_6.xsd">
	<ApplicationArea>
		<Sender>
			<LogicalId>571</LogicalId>
			<Component>Prelude</Component>
			<Task>ORDERENTRY</Task>
			<Communication>ASYNC</Communication>
		</Sender>
		<Receiver>
			<LogicalId>TORO</LogicalId>
		</Receiver>
		<CreationDateTime>2019-05-02T14:58:06-04:00</CreationDateTime>
	</ApplicationArea>
	<DataArea>
		<Add confirm="Always"/>
		<SalesOrder>
			<Header>
				<DocumentIds>
					<DocumentId>
						<Id>602776</Id>
					</DocumentId>
				</DocumentIds>
				<DocumentDateTime>2019-05-02T14:58:06-04:00</DocumentDateTime>
				<OrderStatus entryDateTime="2019-05-02T14:58:06-04:00">
					<Code>SUBMITTED</Code>
				</OrderStatus>
				<ShipNote lang="en-us" author="" entryDateTime="2019-05-02T14:58:06-04:00"/>
				<DocumentReferences>
					<PurchaseOrderDocumentReference>
						<DocumentId>
							<Id>146002/JEFF 5/2/19</Id>
						</DocumentId>
						<DocumentDate>2019-05-02T14:58:06-04:00</DocumentDate>
					</PurchaseOrderDocumentReference>
					<Toro.SalesOrder.Header.DocumentReferences.UserArea>
						<Toro.DocumentType>DS</Toro.DocumentType>
						<Toro.DocumentSource>571</Toro.DocumentSource>
					</Toro.SalesOrder.Header.DocumentReferences.UserArea>
				</DocumentReferences>
				<SpecialPriceAuthorization/>
				<Parties>
					<CustomerParty>
						<PartyId>
							<Id>571</Id>
						</PartyId>
						<Name lang="en-us">Wesco Turf, Inc.</Name>
						<Addresses>
							<Address>
								<AddressLine1>XXXXX</AddressLine1>
								<City>XXXXX</City>
								<StateorProvince>XXXXX</StateorProvince>
								<Country>XXXXX</Country>
								<PostalCode>XXXXX</PostalCode>
							</Address>
						</Addresses>
					</CustomerParty>
					<BillToParty>
						<PartyId>
							<Id>571</Id>
						</PartyId>
						<Name lang="en-us">XXXXX</Name>
						<Addresses>
							<Address>
								<AddressLine1>XXXXX</AddressLine1>
								<City>XXXXX</City>
								<StateorProvince>XXXXX</StateorProvince>
								<Country>XXXXX</Country>
								<PostalCode>XXXXX</PostalCode>
							</Address>
						</Addresses>
					</BillToParty>
					<ShipToParty>
						<PartyId>
							<Id>311058</Id>
						</PartyId>
						<AlternatePartyIds>
							<ShipToPartyId>
								<Id>311058</Id>
							</ShipToPartyId>
						</AlternatePartyIds>
						<Name lang="en-us">XXXXX</Name>
					</ShipToParty>
				</Parties>
				<Toro.SalesOrder.Header.UserArea>
					<Toro.ShipComplete/>
					<Toro.ShipMethod>98</Toro.ShipMethod>
					<Toro.StoreNumber>311058</Toro.StoreNumber>
					<Toro.SalesBusinessUnitDescription/>
					<Toro.LineNumberTotal>1</Toro.LineNumberTotal>
				</Toro.SalesOrder.Header.UserArea>
			</Header>
			<Line>
				<LineNumber>1</LineNumber>
				<OrderItem>
					<ItemIds>
						<ItemId>
							<Id>105-1025</Id>
						</ItemId>
					</ItemIds>
				</OrderItem>
				<OrderQuantity uom="EA">1.0</OrderQuantity>
				<UnitPrice>
					<Amount currency="US">48.21</Amount>
					<FunctionalAmount currency="US">48.21</FunctionalAmount>
					<PerQuantity uom="EA">48.21</PerQuantity>
				</UnitPrice>
				<ExtendedPrice currency="US">48.21</ExtendedPrice>
				<TotalAmount currency="US">48.21</TotalAmount>
				<NeedDeliveryDate>2019-05-03T14:58:06-04:00</NeedDeliveryDate>
				<Note lang="en-us" author="" entryDateTime=""/>
				<Toro.SalesOrder.Line.UserArea>
					<Toro.CustomerBinNum>1J09F14</Toro.CustomerBinNum>
				</Toro.SalesOrder.Line.UserArea>
			</Line>
		</SalesOrder>
	</DataArea>
</AddSalesOrder>`

**Comment by ashmaroli** [comment]
> This is what the structure of the document looks like:

I meant your JSON object..

**Comment by DavidKing0193** [comment]
> > This is what the structure of the document looks like:
> 
> I meant your JSON object..

My apologies. I've been hammering away at this for quite some time now.

[AddSalesOrder_JSON.txt](https://github.com/Shopify/liquid/files/3262802/AddSalesOrder_JSON.txt)

**Comment by ashmaroli** [comment]
@DavidKing0193 There's a minor typo in your template above.
Running the following script will show you that Liquid works as expected:
```ruby
# frozen_string_literal: true

require 'json'
require 'liquid'

template = %(<div>{{ AddSalesOrder.DataArea.SalesOrder.Header.DocumentIds.DocumentId.Id }}</div>)
data = <<~JSON
  {
    "AddSalesOrder": {
      "DataArea": {
        "SalesOrder": {
          "Header": {
            "DocumentIds": {
              "DocumentId": {
                "Id": "602776"
              }
            }
          }
        }
      }
    }
  }
JSON

puts Liquid::Template.parse(template).render(JSON.parse(data))
```

**Comment by DavidKing0193** [comment]
Oh wow. I see that now. let me quick check to see if that works on my end.

**Comment by DavidKing0193** [comment]
> Running the following script will show you that Liquid works as expected

Welp, running it through my Logic Apps pipeline doesn't seem to have changed anything. I wonder if it's some peculiarity with the Liquid Template connector...

I really appreciate your help. If you want to duck out and put your energy elsewehere, it's no hard feelings. I've already started to translate my Liquid Template into an XSLT file.

**Comment by shopmike** [comment]
Sorry, this wasn't fully resolved, I'm going to close this due to age but feel free to re-open if you still have this issue.
