### ISSUE TITLE
Use of pipe in statement breaks statement

### ISSUE THREAD

**Issue by kabads** [Shopify/liquid#1108]
First discussed here https://talk.jekyllrb.com/t/category-page-need-a-page-with-a-link-to-all-posts-of-a-category/2997 - 

I'm using code to iterate over categories: 

    {% assign category = page.title|downcase %}

    {% for post in site.posts %}
    {% if post.categories contains {{category}}  %}
    <li>{{ post.title }}</li>
    {% endif %}
    {% endfor %}

This ^ works! But what I'd like to do, is replace the variable assignment with the call on downcase directly in the if statement (which breaks). Like so: 

    {% for post in site.posts %}
    {% if post.categories contains page.title | downcase %}
    <li>{{ post.title }}</li>
    {% endif %}
    {% endfor %}

With this code, I get the error: 

    Liquid Warning: Liquid syntax error (line 27): Expected end_of_string but found pipe in "post.categories contains page.title | downcase" in /_layouts/categories.html

**Comment by fw42** [comment]
Closing as this isn't a bug but just an unsupported syntax.
