### ISSUE TITLE
Variable scoped locally in for loop interferes with other variable on template

### ISSUE THREAD

**Issue by josefarrugia** [Shopify/liquid#1112]
Hey there 👋🏽,

Noticed something quite peculiar on my custom collection section template on Shopify. I have a sidebar with a list of collections which is user controlled via the schema/theme settings. 

For some apparent reason my collection variable, inside a for loop, somehow interfered with the collection section template's collection variable as none of the products were displaying on the collection page.

I had to change the variable name being assigned in the for loop so that it won't interfere with the other collection variable on the page. As far as I know any variables assigned in a for loop are locally scoped.

Here's a snippet of my code:

```twig
// sections/collection.liquid
//
// sidebar code:
{% for block in section.blocks %}
  {% case block.type %}
    {% when 'collection' %}
      {%- assign collection = collections[block.settings.collection] -%}
      <li>
        <a href="{{ collection.url }}">{{ collection.title }}</a>
      </li>
  {% endcase %}
{% endfor %}

// the variable collection interferes with this code below:
{% for product in collection.products %}
...
...
...
```

What am I missing? Any thoughts from your end?

**Comment by fw42** [comment]
By "interfere", you mean that the `assign` in the loop is overwriting the `collection` variable that already existed before the loop (and that change is visible outside of the loop). This is kind of the behaviour that I expected (and also how some other programming languages (like Ruby) would behave). I don't think this is a bug, unless I'm misunderstanding you.

**Comment by josefarrugia** [comment]
@fw42 I was expecting any variable to be set in the `forLoop` to be only accessible locally.
