### ISSUE TITLE
Liquid syntax error using specific code

### ISSUE THREAD

**Issue by newyumi** [Shopify/liquid#1113]
I wrote the next code in my blog using Jekyll.

> prompt_context() {
>   if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
>     prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
>   fi
> }

But error happened 'Liquid Exception: Liquid syntax error (line 118): Unknown tag 'F' in {file path}'
I don't know how I can solve this problem.

**Comment by ashmaroli** [comment]
Liquid parses all strings unconditionally. It won't know if a given string is a code-sample or not.
If the parser encounters a sequence of `{%`, it will tokenize the subsequent alphanumericals as a *tag_name* and try to validate this *tag_name* against a list of registered Liquid-tags.

To have Liquid ignore sequences `{%` and `{{` from being parsed as *tag-starters* and *variable-starters* respectively, enclose the entire bloc within the **`{% raw %}...{% endraw %}`** block tag:

```bash
{% raw %}
  prompt_context() {
    if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
      prompt_segment black default "%(!.%{%F{yellow}%}.)$USER"
    fi
  }
{% endraw %}
```
