### ISSUE TITLE
Allow passing variables to sections

### ISSUE THREAD

**Issue by jpgklassen** [Shopify/liquid#1118]
We are able to pass variables to snippets via:

```
{% assign product = all_products['my-product'] %}
{% include ‘my-snippet’ with product %}
```

...but this doesn't work for sections. Can we make it possible to pass variables to sections please?

**Comment by shopmike** [comment]
Hey, @jpgklassen I can understand why this would be wanted but the reality of sections is they have been designed to be self-contained which opens up more possibilities such as the Sections API, Theme Editor improvements and a bunch of other cool stuff.

In this instance, `sections` are not designed to replace `include` there is a new `render` tag coming through for this purpose. I'd recommend keeping this code in a snippet and using it that way.

**Comment by maketimetodesign** [comment]
All good and well, but what if you ~want~ _need_ the power of sections, blocks etc and want to configure/control output of the section?
