### ISSUE TITLE
[Mac OSX, Ruby 2.3.7p456] Issue with running example server

### ISSUE THREAD

**Issue by cmaness-ncino** [Shopify/liquid#1119]
Just downloaded the Liquid repository did a `gem install liquid` and I'm trying to run the example server with `ruby server.rb` however when I try to look at the `/products` route anywhere were there is iteration happening I get a `Liquid error: internal.` Any leads on this?

**Comment by robinbijlani** [comment]
I originally had the same problem as you. I don't know Ruby, so I'm not sure if this is the correct approach, but I was able to get the pages rendering properly by running the server with:
`bundle exec ruby example/server/server.rb`

**Comment by shopmike** [comment]
There is a rake task setup for this. Which means you can run either
```
bundle exec rake example
```
or
```
rake example
```
