### ISSUE TITLE
Default filter does not behave as advertised

### ISSUE THREAD

**Issue by mwerezak** [Shopify/liquid#1127]
According to documentation...
> Sets a default value for any variable with no assigned value. Can be used with strings, arrays, and hashes.
> The default value is returned if the variable resolves to nil or an empty string "". A string containing whitespace characters will not resolve to the default value.

If the filter did exactly this, there would be no issue. However it also returns the default value if the boolean value false is given. This is a problem, since it means that in the example below, if someone wants to have a setting that defaults to true...

```
{% assign example_switch = settings.flag | default: true %}
```

...there is actually no value that can be assigned to `settings.flag` that will turn off the switch!

This is surprising behavior that is bound to cause trouble for other people to.

Yes I suppose you can just never have a boolean that defaults to true, and always invert your logic as necessary, but that's working around a bug instead of fixing it. Not only that but doing so is a particular PITA in liquid since there is no logical not operator - inverting a switch requires inserting an entire if/else construct just to swap true/false.

**Comment by tobi** [comment]
Yea that’s a silly bug. Can you submit test case and fix?

**Comment by shopmike** [comment]
Possible fix for this -> https://github.com/Shopify/liquid/pull/1144
