### ISSUE TITLE
feat: Implement hash of file

### ISSUE THREAD

**Issue by alexandre1985** [Shopify/liquid#1128]
## Summary
I would like to have an easy way of getting the hash of any file

## Motivation
Would serve many purpose, one good example would be with Jekyll not relying on plugins to implement cache bust

## Guide-level explanation

this could be implemented as an filter or as a dot variable

## Reference-level explanation

I have not much experience with Ruby or developing features/gems.
Sorry

## Drawbacks
Dont see any drawbacks. Would be nice to have (in my opinion) and useful (to me at least)

## Unresolved Questions

don't know. My lack of developer skills in Ruby doesn't allow me foresight

(this has been copied from https://github.com/jekyll/jekyll/issues/7791)

**Comment by shopmike** [comment]
This is suited as a plugin and not directly within Liquid. I see this has already been opened elsewhere so closing this here.
