### ISSUE TITLE
color_modify filter produces inconsistent results

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/liquid#1148]
Across the board, the scale for hue colour adjustments is `-360° - 360°`, but according to Shopify's documentation, the scale is `0° - 360°`.

Potentially because of this, I believe `color_modify` is producing incorrect results.

For example, in SCSS, Photoshop, and all other hue modify tools, when I modify `#40BAEA` by 12°, the output is `#4098EA`, which is correct.

However, when I use `{{ '#40baea' | color_modify: 'hue', 12 }}` in Shopify, the output is `#EA6240`.

Assuming this an actual issue, this basically means that every store on Shopify that's using this filter, is getting incorrect results, potentially without realising.

Since the scale is essentially half that of the real world, I then tried to double the hue adjustment to `24`. This then produced `#EA8440`, which again is incorrect.

![color_modify](https://user-images.githubusercontent.com/18140157/64628672-b9d38a80-d3e9-11e9-9e78-d870f525e24f.png)

**Comment by ConduciveMammal** [comment]
Hey @shopmike, thanks a lot for the great explanation/example!
So have I just misunderstood the functionality or is it a flaw in the documentation?

My thought process is when viewing this in a SCSS context to achieve the same result, I use `adjust-hue(#40baea, 12)`, which in my mind, is setting the hue of `#40baea` to a new value of `12`. Or have I just totally misunderstood it?

**Comment by shopmike** [comment]
Going by the results it seems that `adjust-hue` is actually taking the current hue value and then shifting it `+12`
