### ISSUE TITLE
"Where" filter with one argument

### ISSUE THREAD

**Issue by vincerubinetti** [Shopify/liquid#1152]
The [`where` filter documentation](https://shopify.github.io/liquid/filters/where/) says that you can omit the second argument to filter out all falsey values in an array. I've found that I can't do that without getting a syntax error: 

`wrong number of arguments (given 2, expected 3)`

What I'm trying to achieve is the following: 
```liquid
{% assign entries = site.data.catalog | where: "images.thumbnail_url" | sort: "info.date" | reverse %}
```

I need all the entries from `catalog` that have the sub-key `images.thumbnail_url` defined (truthy). And I need the entry itself so I can access other fields of it. I don't just need the filtered `thumbnail_url`'s themselves.

Is there something I'm missing here...

**Comment by shopmike** [comment]
@vincerubinetti are you sure this is the line that is causing the error? As the `where` filter code looks correct and if I put this code in a theme I don't receive any errors.

**Comment by vincerubinetti** [comment]
If I take out the where filter -- just the filter, not the whole line even -- the error goes away. I've since made a work-around, but the where filter is quite a bit cleaner and nice and semantic.

I can try to look at the versions of packages I'm using and provide the structure of the `site.data.catalog` I'm using, if that would help.

**Comment by shopmike** [comment]
Are you using Jekyll? If so you are likely using the Jekyll where filter and not the standard Liquid one. They had this functionality built-in prior to it coming into the core Liquid library, so it works a little differently I'm guessing.

**Comment by vincerubinetti** [comment]
Ah yes, I am. Sorry that was probably a key piece of context I should've mentioned. Had no idea they had it prior. Will close this issue.
