### ISSUE TITLE
Check this error - "json not allowed for this object"

### ISSUE THREAD

**Issue by yu-coder** [Shopify/liquid#1153]
**{{ variable | json }}**
`{"error":"json not allowed for this object"}`

How can I avoid to show for this type of variable data while loop arrays?
Thank you.

**Comment by shopmike** [comment]
@yu-coder not all objects in Shopify support `json` because some are very large. It is usually unlikely that you need the whole object so most developers in this instance will access the variables they need in to a custom object
```
<script>
json = {
"field1": {{ variable.some_field_1 | json }},
"field2": {{ variable.some_field_2 | json }}
}
</script>
```

**Comment by yu-coder** [comment]
Thanks @shopmike 
What I want to know is that: when I access hidden article, it shows like the above error.
So I want to check if article is hidden to avoid showing this article while looping all articles in article pages.

**Comment by shopmike** [comment]
@yu-coder I think what you're trying to do is solved by using the following as this sounds like an `EmptyDrop` https://help.shopify.com/en/themes/liquid/basics/types#emptydrop

**Comment by yu-coder** [comment]
Yes, it is solved by checking for emptiness.

```
{% unless _article == empty %}
...
{% endunless %}
```
Thanks for your help. @shopmike 👍

**Comment by masserra** [comment]
> @yu-coder not all objects in Shopify support `json` because some are very large. It is usually unlikely that you need the whole object so most developers in this instance will access the variables they need in to a custom object
> 
> ```
> <script>
> json = {
> "field1": {{ variable.some_field_1 | json }},
> "field2": {{ variable.some_field_2 | json }}
> }
> </script>
> ```

Then, why does `{{ product.metafields.custom | json }}` work, while `{{ product.metafields.custom.key | json }}` doesn't? 

If a child object is too large to be JSON stringified then it shouldn't work either when stringifying the parent instead. When doing so I can see the child JSON stringified, but I can't JSON stringify the child directly...

I find some of these rules quite confusing. Either I didn't find the right reason yet or the rule doesn't make sense. It doesn't make sense that it's related to size, if one can just do it to the parent instead, overriding the rule altogether.
