### ISSUE TITLE
Want to get an extension of a filename

### ISSUE THREAD

**Issue by yu-coder** [Shopify/liquid#1173]
Hi, I am going to get an **extension of a filename** and make it **lowercase**.

For example
`A123.JPG => A123.jpg`

I can make string **lowercase** using **downcase** filter.
Is there any best way to get the **extension of a filename**?

**Comment by ashmaroli** [comment]
If you require this filter for working with Jekyll, you can use a local plugin. Have the following code in a file at path `_plugins/file_filters.rb`.
```ruby
module Jekyll
  module FileFilters
    def extname(input)
      File.extname(input)
    end
  end
end

Liquid::Template.register_filter(Jekyll::FileFilters)
```

Then just use the filter in your template(s):
```
{{ 'A123.JPG' | downcase | extname }}
```

**Comment by yu-coder** [comment]
Thanks @ashmaroli 
It helped me.
