### ISSUE TITLE
Syntax checker not allowing valid datarefs?

### ISSUE THREAD

**Issue by rcrews** [Shopify/liquid#1177]
Accessing data in  
`_site/productid/csp/2.0.0/navigation.yml` with tag  
`{% include links.html nav=site.data.productid.csp["200"].navigation %}`
I'm getting the following:
`Liquid Exception: Invalid syntax for include tag: nav=site.data.productid.csp["200"].navigation Valid syntax: {% include file.ext param='value' param2='value' %} in csp/2.0.0/links.html`
However
* adding quotes changes the meaning:  
`{% include links.html nav='site.data.productid.csp["200"].navigation' %}`
* `{% include links.html nav=site.data.productid.csp.cloud.navigation %}` works fine

Is the syntax checker is being too aggressive?

**Comment by shopmike** [comment]
I'm not sure this is a direct Liquid issue as the syntax for the include tag is actually different on the default `include` tag used in this library. To highlight what I mean variables are set with `var: something` and not `var=something`. Not saying this issue still doesn't exist but I would also possibly look to where this `include` tag functionality is actually coming from as it is likely in the actual implementation you are using.
