### ISSUE TITLE
Two nested for-loops produce double output

### ISSUE THREAD

**Issue by mosesontheweb** [Shopify/liquid#1179]
Hi,

recently I switched from Lektor to Jekyll due to some strange problems. Porting Jinja2 templates to Liquid is quite easy, there are only some modifications to do to get the same result.

The only thing what is strange is that two nested for-loops produce double output, which isn't the case in Jinja2 templates. Here's an example how I encountered this problem:

JSON file (used as datafile in Jekyll):
```json
{
    "home": {
        "name": "Home",
        "path": "/",
        "icon": "fas fa-home"
    },
    "faq": {
        "name": "FAQ",
        "path": "/faq",
        "icon": "fas fa-question"
    },
    "manuals": {
        "name": "Anleitungen",
        "path": "/manuals",
        "icon": "fas fa-book-open"
    }
}
```
The part of the template used for rendering thiis data:
```html
        <div class="navbar-menu">
            <div class="navbar-start">
                {% for rubrik in site.data.navigation %}
                {% for part in rubrik %}
                <a class="navbar-item{% if page.url == part.path %} is-active{% endif %}" href="{{ part.path }}">
                    <span class="icon"><i class="{{ part.icon }}"></i></span><span>{{ part.name }}</span>
                </a>
                {% endfor %}
                {% endfor %}
            </div>
        </div>
```
The output:
```html
       <div class="navbar-menu">
            <div class="navbar-start">


                <a class="navbar-item" href="">
                    <span class="icon"><i class=""></i></span><span></span>
                </a>

                <a class="navbar-item is-active" href="/">
                    <span class="icon"><i class="fas fa-home"></i></span><span>Home</span>
                </a>



                <a class="navbar-item" href="">
                    <span class="icon"><i class=""></i></span><span></span>
                </a>

                <a class="navbar-item" href="/faq">
                    <span class="icon"><i class="fas fa-question"></i></span><span>FAQ</span>
                </a>



                <a class="navbar-item" href="">
                    <span class="icon"><i class=""></i></span><span></span>
                </a>

                <a class="navbar-item" href="/manuals">
                    <span class="icon"><i class="fas fa-book-open"></i></span><span>Anleitungen</span>
                </a>


            </div>
        </div>
```
As you can see I get double output. The first one empty coming from the first loop, the second one, which is correct. The handling of data is right since the second loop output is as expected.

Are there any hints on this or could this be a bug? I'm using Jekyll v4.0 which comes with Liquid v4.0.3.

Regards, Thomas

**Comment by shopmike** [comment]
This is weird behaviour, I'd say this has something to do with how the data structure is processed. If I had to guess I would assume its looping Key, Value, Key, Value, Key, Value. I'd likely raise this against https://github.com/jekyll/jekyll as this seems more like an implementation issue than the Liquid library itself.

**Comment by shopmike** [comment]
Just going to close this. As I guess I'm assuming changing the following will help.
```
{% for part in rubrik %}
```
to
```
{% for part in rubrik[1] %}
```

**Comment by mosesontheweb** [comment]
Hi,
that actually is only the half way. Your suggestion leads to this:
```
        labelHome
        <p><a href=""></a></p>
        
        path/home
        <p><a href=""></a></p>
        
        iconfas fa-home
        <p><a href=""></a></p>
        
    
        
        labelFAQ
        <p><a href=""></a></p>
        
        path/faq
        <p><a href=""></a></p>
        
        iconfas fa-question
        <p><a href=""></a></p>
```
But @ashmaroli solved it with this solution: https://github.com/jekyll/jekyll/issues/7837#issuecomment-537037829

If Liquid would allow Ruby functions within a template, unpack would maybe another way to do this.

Anyway, thanks!

**Comment by shopmike** [comment]
Nice to see you have some sort of fix. Yeah, his solution is ignoring whatever the blank array items your looping over are. You can likely dump out what these are with `{{ part | json }}` or something similar and figure out what these actually are.

**Comment by shopmike** [comment]
This might be another way to do this

```liquid
        <div class="navbar-menu">
            <div class="navbar-start">
                {% for rubrik in site.data.navigation %}
                {% assign part = rubrik[1] %}
                <a class="navbar-item{% if page.url == part.path %} is-active{% endif %}" href="{{ part.path }}">
                    <span class="icon"><i class="{{ part.icon }}"></i></span><span>{{ part.name }}</span>
                </a>
                {% endfor %}
            </div>
        </div>
````
