### ISSUE TITLE
Add 'continue' and 'break' to 'for' tag

### ISSUE THREAD

**Issue by timothystone** [Shopify/liquid#119]
This is a serious miss in the `for` tag, making simple boolean logic to skip an iteration or cut out of the loop **impossible**.

I can't think of a single reason why these features are not available in the `for` tag. I can't even cite an example of a template language that doesn't provide this feature, even the implementation language of Liquid, Ruby, provides `continue` and `break` in loops.

The `continue` and `break` options could also be used in the `tablerow` tag as well to clear up a long standing issue with iterating through collections, testing for type or other attribute, and empty cells being inserted.

**Comment by cpres** [comment]
It would be great if this was added to your documentation:
https://docs.shopify.com/themes/liquid-documentation/tags/iteration-tags

this meaning break and continue

**Comment by fw42** [comment]
@dtKinger: Can we add `continue` and `break` to the docs?

**Comment by JoshHighland** [comment]
break is still not documented in the Shopify API docs - https://docs.shopify.com/themes/liquid-documentation/tags/iteration-tags

**Comment by fw42** [comment]
@dtKinger @admhlt ping? can one of you take care of this?

**Comment by admhlt** [comment]
I'm on it! :+1:

**Comment by admhlt** [comment]
`break` and `continue` have been added to the page on [Iteration tags](http://docs.myshopify.io/themes/liquid-documentation/tags/iteration-tags/). It may be a day or two until the changes are on the live site.
