### ISSUE TITLE
formatting decimal values

### ISSUE THREAD

**Issue by karpikpl** [Shopify/liquid#1194]
Hi,
I'm using liquid templates in Microsoft Azure. The problem that I'm running into is that liquid seems to round floating point numbers.

```
{%- assign rate = 0.733675715 -%}
{{ rate }}
```
results in `0.7336757`
where my expectation is to get `0.733675715`

I've tried different solutions, including converting data to string in liquid but nothing worked so far.

How do I make Liquid display `0.733675715`?

**Comment by shopmike** [comment]
@karpikpl Microsoft Azure is actually using http://dotliquidmarkup.org/ as per their docs. 

> Within Logic Apps, Liquid templates are used as a kind of XSLT for JSON objects. This allows us to create more complex transformations on JSON objects, without the need of introducing a custom Azure Function. Liquid templates are part of the Integration Account. Behind the scenes, DotLiquid Jump is used.

I'd recommend reopening this issue over at https://github.com/dotliquid/dotliquid/

**Comment by karpikpl** [comment]
I got confirmation from Microsoft that it is in fact issue with Azure, not dotliquid.

I found an unrelated bug in dotliquid that made me think it's caused by them.
