### ISSUE TITLE
`{% liquid %}` tag does not work inside any other tags

### ISSUE THREAD

**Issue by thelornenelson** [Shopify/liquid#1214]
@pushrax

The new `{% liquid %}` tag does not seem to work properly when it's used inside other tags.

For example, this code works as expected, and outputs `Hello world`.
```
{% liquid
  echo "Hello world"
%}
```

This code doesn't work at all and generates a `Liquid syntax error (line 4): 'if' tag was never closed` error
```
{% if true %}
  {% liquid
    echo "Hello world"
  %}
{% endif %}
```

The same issue occurs inside other tags I tried.

**Comment by tobi** [comment]
That's... not the intention.

**Comment by radmedov** [comment]
Looks like it's still an issue.

**Comment by dylanahsmith** [comment]
Are you able to reproduce the issue using the latest commit in this repo?  I think the fix just hasn't been deployed yet.
