### ISSUE TITLE
Fragment caching possible?

### ISSUE THREAD

**Issue by imderek** [Shopify/liquid#123]
With ERB you can fragment cache individual records in a list view like so:

```
<% @items.each do |item| %>
  <% cache item do %>
    <%= item.name %>
  <% end %>
<% end %>
```

Thus, the second time the list is viewed, each rendered item will be loaded from cache. Is it possible to use this same approach when using Liquid templates? The template might look something like:

```
{% for item in items %}
  {{ item.name }}
{% endfor %}
```

and rendered with:

``` ruby
template = Liquid::Template.parse(template)
template.render('items' => @items)
```

When it loops over the items, I'd like to be able to fragment cache each one. Any pointers?

**Comment by ZenCocoon** [comment]
@fw42 do you have some details about your caching implementation / recommendation?

**Comment by dylanahsmith** [comment]
We mostly use [identity_cache](https://github.com/shopify/identity_cache) for record caching and [cacheable](https://github.com/shopify/cacheable) for page caching.

**Comment by ZenCocoon** [comment]
@dylanahsmith Thanks for the links.
