### ISSUE TITLE
Where filter not working with numbers

### ISSUE THREAD

**Issue by szollbrecht** [Shopify/liquid#1231]
When I upgraded from version 3 to 4.0.3 (using liquid with jekyll), the where filter stopped working.

I'm filtering on a number: `{% assign posts = site.posts | where: "year", "2017" %}`

When I add a character "x2017" it works fine again. Not sure whether the filter has a problem or the problem lies in jekyll?

**Comment by huysentruitw** [comment]
Seems to be fixed in 4.1.0, so I'd suggest to [update](https://jekyllrb.com/docs/upgrading/).

**Comment by szollbrecht** [comment]
Thanks for the hint! I updated and removed my workaround. Works fine again :)
