### ISSUE TITLE
Whitespace in square brackets should be ignored

### ISSUE THREAD

**Issue by falldowngoboone** [Shopify/liquid#1242]
Recently when converting a Nunjucks template to Liquid, I ran into an issue with whitespaces inside of square bracket notation.

```
variable[ key ]
```

👆 The above code does what I would expect in Nunjucks and accesses the value associated with the string to which `key` is set. In Liquid, however, the value is `variable` itself. Not sure if this is a known issue, but I could not find information anywhere about this.

I would expect the above should work without having to remove whitespace. My question is, can anyone reproduce this, and, if they can, could this be fixed?

**Comment by harttle** [comment]
Seems shopify/liquid has this problem as well, but the `variable[ key ]` syntax seems resonable. I'll try to fix it soon.
