### ISSUE TITLE
Any idea when a new cut of master will get released?

### ISSUE THREAD

**Issue by jaredcwhite** [Shopify/liquid#1243]
Hey all, I'm heading up the new [Bridgetown](/bridgetownrb/bridgetown) project, and have already put the awesome new `render` tag to good use. I'm wondering if there's any ETA for when a new gem version will get released? Currently on new site builds I'm having to reference my GH liquid fork with a slightly bumped version number so the Gemfile and Bridgetown's gemspec aren't fighting each other. Would be great just to require "4.1" or whatever and be done.

Thank you in advance!

**Comment by jaredcwhite** [comment]
Bump? cc @pushrax @dylanahsmith

The last official gem release appears to have been over a year ago. Bridgetown is fast moving towards a full implementation of #1244 and we need gemspecs to be able to reference 4.0.4 or 4.1 or 5.0 or however you plan to version this. Otherwise our options are… rewrite a custom `render` tag that's compatible with 4.0.3? Fork the gem? (Definitely don't want to do that!) Not sure what else?

TIA 😃

**Comment by jaredcwhite** [comment]
All right, I ended up pulling code from the master branch into a separate gem which simply overrides code from Liquid 4.0.3 to support `render`. Inelegant, yes…breaks something…maybe, but all my Bridgetown tests and website code is passing so I think we're good for the time being.

For anyone else out there ready to use `render` in your projects, check it out:
https://github.com/bridgetownrb/liquid-render-tag

Once there's a new official release of Liquid, this gem can go away forever. 😄

**Comment by ctubbsii** [comment]
Please release a new version... the announcement in May for multiline tags at https://shopify.dev/changelog/new-liquid-multiline-tags is *very* exciting, but the last release was back in March.

**Comment by macournoyer** [comment]
Done! https://rubygems.org/gems/liquid/versions/5.0.0  🎉
