### ISSUE TITLE
Removing carriage returns

### ISSUE THREAD

**Issue by pravinkarthy** [Shopify/liquid#1248]
Hi,

This issue is related to https://github.com/Shopify/liquid/issues/460.  As suggested in the issue by @fw42 , I used "strip_newline" filter but it is not removing the "\r" carriage return character while generating the XML input template.  My sample text input is something like "ABC \r\n DEF" but the rendered template has the text as "ABC \r DEF".  We are using DotLiquid v 2.0.314.0

**Comment by dylanahsmith** [comment]
> We are using DotLiquid v 2.0.314.0

Looks like you are reporting this to the wrong repo.  http://dotliquidmarkup.org/ says:

> DotLiquid is a templating system ported to the .net framework from Ruby’s Liquid Markup.

This has been fixed in ruby a long time ago (https://github.com/Shopify/liquid/pull/203) so it should be easy to convince DotLiquid to port the change
