### ISSUE TITLE
Design Question

### ISSUE THREAD

**Issue by achadee** [Shopify/liquid#1267]
Hi I'm just planning out a project (potentially using liquid) and have a general design question,

Is it better to render the templates server side on each client side request, or to pre render them on a hook from a model update?

My main concern is with developers and live reloading code to my server (ie. hitting save on your local machine and it uploading to my server - much like themekit)

from what I can see they both have their advantages and disadvantages.

Render on each client side requests 
=======
pros
- faster for developers that are shipping code 
- no data mismatches

cons
- a lot of database queries

Prerender
=======
pros
- can load the page super fast from a cdn (storing the template prerendered) 
- reduce load on db requests

cons
- deploying code (for developers to live reload code will be slow)

If someone with experience in this could shed some light that would be awesome :^)

**Comment by dylanahsmith** [comment]
This is a question that isn't specific to liquid, but more of a caching question in general.  Pre-rendering is essentially write-through caching, render on demand is read-through caching and sometimes it isn't worth doing any caching at all.
