### ISSUE TITLE
my help

### ISSUE THREAD

**Issue by Matt-PDF** [Shopify/liquid#1273]
Ola sou novo em nesse assunto de criação de temas, sou brasileiro como pode notar e tenho varias duvidas a respeito gostaria muito de uma ajudas nesse processo assim que der me manda uma feedback 
matheusgama821@gmail.com

**Comment by burakswe** [comment]
Hi @Matt-PDF ,
I think, you're trying to figure out how you can create Shopify themes. There are a lot of articles here: https://www.shopify.com/partners/blog/topics/shopify-theme-development

You can also ask your theme-related questions on [Shopify Community](https://community.shopify.com/c/Shopify-Community/ct-p/en) 

I hope it helps.
