### ISSUE TITLE
What is Square Bracket outside and what does it exactly does?

### ISSUE THREAD

**Issue by ZXDragon360** [Shopify/liquid#1293]
While developing a website using Shopify, I tried to get the value from the given target which is a standalone term "[[itemVendorLabel]]" without anything to associate such as an array or collection. At first doubt, it looks fine to me. However, the value I got from it was not working when compare against our collection of products for match vendor name. Here is a snippet:
`{%- capture bc_layout -%}
{%- case layout -%}

{%- when 'productGridItemHtml' -%}
<div class="grid__item small--one-half medium-up--one-fifth"> 
    <script class="bc-sf-filter-product-script" data-id="bc-product-json-[[itemId]]" type="application/json">[[itemJson]]</script> 
    <a href="[[itemUrl]]" class="product-card"> 
        <div class="product-card__image-container"> 
            <div class="product-card__image-wrapper"> 
            [[itemImages]] 
            <noscript><img src="[[itemThumbUrl]]" alt="[[itemTitle]]" class="product-card__image"></noscript> 
            </div> 
            </div> 
        <div class="product-card__info"> 
          		[[itemSwatches]] 
                [[itemVendor]]
                <div class="product-card__name">[[itemTitle]]</div> 
                <span class="stamped-product-reviews-badge" data-id="[[itemId]]"></span>
            {% if customer %}
          	<div class="product-card__price">[[itemPrice]]</div> 
          	{% else %}
          	<div class="product-card__price"></div> 
          	{% endif %}
            [[itemSoldOutLabel]] 
            </div> 
            [[itemSaleLabel]] 
            <div class="product-card__overlay"> 
            <span class="btn product-card__overlay-btn">  {{ 'products.product.view' | t }}  </span> 
        </div> 
    </a> 
</div>

{%- when 'vendorHtml' -%}
	<div class="product-card__brand">

      {% capture getVendor %}[[itemVendorLabel]]{% endcapture %}
      {% for product_vendor in collection.all_vendors %}
        {% if product_vendor == getVendor | handlize %}
          	{% assign vendor = product_vendor %}
      		{{ vendor }}
      	{% else %}
      		{% assign vendor = false %}
        {% endif %}
      {% endfor %}
      
      {% if vendor %}
        {{ vendor | handlize }} - yes
      {% else %}
        [[itemVendorLabel]] - no
      {% endif %}
      
	</div>

{%- when 'saleLabelHtml' -%}
	<div class="product-tag product-tag--absolute" aria-hidden="true"> {{ 'products.product.on_sale' | t }} </div>

{%- when 'soldOutLabelHtml' -%}
	<div class="product-card__availability"> {{ 'products.product.sold_out' | t }} </div>

{%- when 'previousHtml' -%}
	<span class="prev"><a href="[[itemUrl]]">&larr;</a></span>

{%- when 'nextHtml' -%}
	<span class="next"><a href="[[itemUrl]]">&rarr;</a></span>

{%- when 'pageItemHtml' -%}
	<span class="page"><a href="[[itemUrl]]">[[itemTitle]]</a></span>

{%- when 'pageItemSelectedHtml' -%}
	<span class="page current">[[itemTitle]]</span>

{%- when 'pageItemRemainHtml' -%}
	<span>[[itemTitle]]</span>

{%- when 'paginateHtml' -%}
	<div class="pagination">[[previous]][[pageItems]][[next]]</div>

{%- when 'sortingHtml' -%}
	<label for="bc-sf-filter-top-sorting-select" class="collection-sort__label"> {%- assign temp = 'collections.sorting.title' | t  -%} {%- unless temp contains 'translation missing'  -%} {{ temp }} {%- else -%} Sorting {%- endunless -%} </label>
	<select id="bc-sf-filter-top-sorting-select" class="collection-sort__input">[[sortingItems]]</select>

{%- endcase -%}

{%-  endcapture -%}
{%- assign str = "}}" -%}
{{- bc_layout | json | replace: "[[", "{{" | replace: "]]", str -}}
`

And the picture showed a result of failed match vendor name appended with " - no" on given value from itemVendorLabel:
![image](https://user-images.githubusercontent.com/44376988/92977859-213c7400-f45c-11ea-8caa-276afe62f4d3.png)

It seems the value is not exactly as it is a string. Surely it looks like it contains some hidden special characters that cause a conditional statement to fail on match a string vendor name.

So, I have 2 questions:
1. What is this "[[itemVendorLabel]]" does?
2. How to store the value from it as it is exactly says?

**Comment by dylanahsmith** [comment]
> What is this "[[itemVendorLabel]]" does?

That doesn't get interpreted at all by liquid.  The last line (`{{- bc_layout | json | replace: "[[", "{{" | replace: "]]", str -}}
`) seems to convert that to `{{itemVendorLabel}}` which seems like it might be for some client-side template substitution being done that uses the same syntax as liquid for variables.

If you actually believe this is a liquid issue, then try to simplify the problematic code down so that you can reproduce it using just the liquid gem, since this isn't the place for theme support.
