### ISSUE TITLE
Is the visit from a logged in store owner or store staff?

### ISSUE THREAD

**Issue by mfs-mindsize** [Shopify/liquid#1297]
Logged in user provide the Customer object. But how can we tell if a visit is from a logged in store owner or store staff? 

The lack of the Customer object could simply mean they're not logged in and could be anyone.

**Comment by burakswe** [comment]
@mfs-mindsize There is no such an object to check directly if it's a store owner or store staff, but you can check this via email. What about checking if it's a store owner email or store staff email by `customer.email`?

**Comment by mfs-mindsize** [comment]
@burakswe - Who does checking email help? 

Other than that, having an API to answer such questions would be helpful. That is, you can also interpret this issue as a feature request :)

**Comment by burakswe** [comment]
@mfs-mindsize I don't know who is checking email help. I don't work at Shopify. I'm a contributor of this repo.  
Cheers :)
