### ISSUE TITLE
On a video.liquid section, can you have the background video audio play even when scrolling down past the video?

### ISSUE THREAD

**Issue by jdk301** [Shopify/liquid#1298]
I have a website where the homepage begins with a YouTube video with section.settings.style == 'background' & section.settings.height set to 'small'. Here are the issues I'm currently facing:
First, the video does not have audio
Second, the video-section-wrapper is set to section.settings.height but is slightly zoomed in so that you cannot access the control bar on the bottom of the YouTube video (unmute button, scroll btn, etc.)
Third, I would like the audio to keep playing even when scrolling down the page and off the video (currently, the background video continues to play without audio).

Thank you for this awesome community & I appreciate the help! Please let me know if there are additional information I can provide.

**Comment by burakswe** [comment]
@jdk301 It seems like this is CSS/JS issue. I didn't see the source code, but I don't think this issue is related to Liquid. Maybe you can reach out to theme developer or ask the same question on [Shopify Community](https://community.shopify.com/c/Shopify-Community/ct-p/en) 

Cheers!
