### ISSUE TITLE
Potential to cut a new release?

### ISSUE THREAD

**Issue by itsliamegan** [Shopify/liquid#1299]
I'm not sure if you have a specific roadmap for future versions, but a crucial fix that's preventing me from using Liquid on Ruby 2.7 is [removing support for taint checking](https://github.com/Shopify/liquid/commit/065ccbc4aa5b4955dae9743509907bd9ad0db0b9).

Running on Ruby 2.7, any attempt to use a variable or a literal in a Liquid template results in the `warning: Object#tainted? is deprecated and will be removed in Ruby 3.2.`. This makes sense since 4.0.3—the version I'm currently running—is code from over a year ago and predates the commit that removes the Object#tainted? call.

My first instinct was to run from master instead of a tagged version, but as I'm using it in a gem, it's not possible to specify a GitHub branch to checkout from like it is with Bundler.

I understand that this is probably low priority, and would likely take some effort to determine what changes there have been since May 2019. I'm happy to help with compiling a list of changes or anything else that would expedite this process 👍

**Comment by asbjornu** [comment]
I'm using Liquid in [Jekyll](https://jekyllrb.com/) and would very much like the `{% render %}` tag to become available as per https://github.com/Shopify/liquid/pull/1122#issuecomment-660084231.

**Comment by waruboy** [comment]
Yes I'd vote for this too please, same like @asbjornu , for the render tag.

**Comment by macournoyer** [comment]
https://rubygems.org/gems/liquid/versions/5.0.0 has just been released 🎉
