### ISSUE TITLE
Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8

### ISSUE THREAD

**Issue by horacio** [Shopify/liquid#1324]
Hello, Liquid team!

I'm having a `Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8` exception while rendering HTML. The thing is that [it only happens on 4.0.3](https://github.com/Shopify/liquid/blob/v4.0.3/lib/liquid/block_body.rb#L97); master works perfectly. So it seems that it got fixed on #1091 (possibly), but I can't identify what it is so I can backport it in some way.

As a side note: is there an ETA for a new release? Last is form March '19.

**Comment by macournoyer** [comment]
https://rubygems.org/gems/liquid/versions/5.0.0 has just been released, and should fix this.
