### ISSUE TITLE
Spaces around object property key causing EmptyDrop (Breaking change)

### ISSUE THREAD

**Issue by Christopher-Hayes** [Shopify/liquid#1332]
Hello, since a couple days ago (~Friday/Saturday 10/23 - 10/24) this code suddenly stopped working. The code originally had spaces on the side of the brackets that passed the object property name. This stopped working, and it seems those spaces must be removed for the code work now. Is this a bug or a new syntax requirement?

**This is a demonstration of what's happening**
```
{% assign before = all_products[ product.metafields.metafieldNamespaceHere.metafieldKeyHere ] %}
{% assign after = all_products[product.metafields.metafieldNamespaceHere.metafieldKeyHere] %}
<script>
    console.log('BEFORE: {{ before }} {{ before.id }}');
    console.log('AFTER: {{ after }} {{ after.id }}');
</script>
```
*Notice in the "before" code there is a space inside the `[` and `]`, these spaces had to be removed to get the code working again.*

**Console Output**
```
BEFORE: AllProductsDrop EmptyDrop
AFTER: ProductDrop 4573791289441
```

**Comment by therealsphinx** [comment]
Seems like a bug. Could you show more context?

**Comment by Christopher-Hayes** [comment]
@therealsphinx what would be useful? To be honest, for that code there's not much more to it. The goal of that code was just to get the ID of a product from a handle that was passed in through a custom metafield. Below I have exactly what the code is if that helps. (The error producing version)
```
...
{% assign customProduct = all_products[ product.metafields.kbmax.custom_product_handle ] %}
...
<script>
    ...
    var customProduct = {
        id: {{ customProduct.id }},
        ...
    }
    ...
</script>
```

**Comment by pushrax** [comment]
This is due to a major change to support more of Liquid inside Liquid-C, it should be fixed very soon.

**Comment by dylanahsmith** [comment]
This has been fixed by https://github.com/Shopify/liquid/pull/1335 and https://github.com/Shopify/liquid/pull/1338
