### ISSUE TITLE
Handling errors inside custom filters in :warn mode

### ISSUE THREAD

**Issue by meruen** [Shopify/liquid#1342]
We don't have a way to append custom errors to template object inside custom filters in :warn mode?
```
module MyFilter
    def raise_this(s)
        err = Liquid::Error.new
        err.line_number = 15
        err.template_name = 'some_name'
        @context.errors << err
    end

    def or_maybe_something_like_this(s)
        @context.handle_error(some_random_error)
    end
end

Liquid::Template.register_filter(MyFilter)
```
In both ways the errors are not passed to the template object itself. This is the way the template is being used:
```
template = Liquid::Template.parse({{ 'something' | raise_this }}, error_mode: :warn, line_numbers: true)
template.render({}, strict_variables: true, strict_filters: true)
template.errors # -> [] empty array
```

Am I missing something or could be a good start point for a new feature?

**Comment by dylanahsmith** [comment]
I tested on master and the latest release (v4.0.3) and it worked in both cases.

What version of liquid are you testing with?

**Comment by meruen** [comment]
Update the gem and seems working fine now! Thanks!
