### ISSUE TITLE
Escape doesn't work on html string

### ISSUE THREAD

**Issue by jeremygottfried** [Shopify/liquid#1348]
I am trying to escape an HTML string, but the method just returns the same string I passed in.
```liquid
{%- capture body_html %}<section class="mx-2 my-5">
  <div class="container-fluid">
    <div class="row justify-content-center">
      <div class="col-12 col-sm-8 col-md-3 col-lg-3 col-xl-3">
        <img id="Image-{{ image.id }}"
          class="img-fluid w-100"
          src="{{ "tips-vip-for-life.jpeg" | asset_img_url: "3024x" }}"
          alt="tips vip for life"
        >
      </div>
      <div class="col-12 col-sm-12 col-md-4 col-lg-3 col-xl-2">
        <div class="my-3">
          <div class="text-bold h5"><b>Total:</b> USD {{ cart.total_price | money }}</div>
        </div>
        <a class="btn btn-danger w-100 m-auto font-weight-bold" href="/checkout">
          Continue to checkout
        </a>
        <div class="additional-checkout-buttons">
          {{ content_for_additional_checkout_buttons }}
        </div>
      </div>
    </div>
  </div>
</section>{% endcapture -%}

{%- assign html_string = body_html | escape_once -%}

<div
  data='{"body_html":"{{ html_string }}"}'
  id="cart-page"
>
</div>
```

The escape method returns the same string that I passed in. None of the escape characters are replaced. Neither `escape_once` or `escape` work on the html string.

**Comment by burakswe** [comment]
@dylanahsmith I experienced the same issue on my local server. I even tested on a Shopify store, `espace` and `escape_once` don't work.

**Comment by dylanahsmith** [comment]
Tried reproducing with liquid in isolation

```ruby
require 'liquid'

template = Liquid::Template.parse(<<~LIQUID)
{%- capture body_html %}<b>hello</b>{% endcapture -%}
{%- assign html_string = body_html | escape_once -%}
<pre>{{ html_string }}</pre>
LIQUID

puts template.render
```

and it outputs

```
<pre>&lt;b&gt;hello&lt;/b&gt;</pre>
```

I also tried using your example in Shopify test shop and it was escaped in the output html source code

```html
<div
  data='{"body_html":"&lt;section class=&quot;mx-2 my-5&quot;&gt;
  &lt;div class=&quot;container-fluid&quot;&gt;
    &lt;div class=&quot;row justify-content-center&quot;&gt;
      &lt;div class=&quot;col-12 col-sm-8 col-md-3 col-lg-3 col-xl-3&quot;&gt;
        &lt;img id=&quot;Image-&quot;
          class=&quot;img-fluid w-100&quot;
          src=&quot;//cdn.shopify.com/s/files/1/0096/1102/t/1/assets/tips-vip-for-life_3024x.jpeg?62&quot;
          alt=&quot;tips vip for life&quot;
        &gt;
      &lt;/div&gt;
      &lt;div class=&quot;col-12 col-sm-12 col-md-4 col-lg-3 col-xl-2&quot;&gt;
        &lt;div class=&quot;my-3&quot;&gt;
          &lt;div class=&quot;text-bold h5&quot;&gt;&lt;b&gt;Total:&lt;/b&gt; USD $0.00&lt;/div&gt;
        &lt;/div&gt;
        &lt;a class=&quot;btn btn-danger w-100 m-auto font-weight-bold&quot; href=&quot;/checkout&quot;&gt;
          Continue to checkout
        &lt;/a&gt;
        &lt;div class=&quot;additional-checkout-buttons&quot;&gt;
          
        &lt;/div&gt;
      &lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/section&gt;"}'
  id="cart-page"
>
</div>
```

**Comment by burakswe** [comment]
@dylanahsmith I'm able to get your example working in a Ruby file, but still it doesn't escape in a Shopify store. 
Do you have any idea?

**Comment by dylanahsmith** [comment]
I already posted the output I got when trying on a Shopify test shop. If you view the page source, what do you see for the output of that snippet

**Comment by jeremygottfried** [comment]
I'm guessing this is not going to be debugged any time soon. If we could have the ability to instantiate key/value Objects and Arrays, we probably wouldn't run into issues like this. I could create my own object and then wrap the entire object in a "to_json" method, the same way I do with the liquid objects provided by Shopify. Otherwise I'm stuck manually writing out JSON if I want to pass data.

**Comment by dylanahsmith** [comment]
> I'm guessing this is not going to be debugged any time soon.

I would look into it if I could reproduce it, however, I wasn't provided enough to do that.  For instance, I wasn't even provided with an answer to this question

> If you view the page source, what do you see for the output of that snippet

You could also help with debugging this yourself by simplifying your example until it has only the relevant parts needed to reproduce the problem.  If you can remove the dependence on Shopify, then you could provide a complete reproduction script as I tried to show in https://github.com/Shopify/liquid/issues/1348#issuecomment-765673500 but I instead found that the filter appears to be working as expected.

**Comment by jeremygottfried** [comment]
Here's a basic example:

```liquid
{%- capture body_html %}<div></div>{% endcapture -%}

{%- assign html_string = body_html | escape_once -%}

<div data='{"body_html":"{{ html_string }}"}'></div>
```

Output in shopify store:
```html
<div data="{&quot;body_html&quot;:&quot;<div></div>&quot;}"></div>
```

The div string wasn't escaped at all. If it was escaped, then the div string would look something like this:
```html
&lt;div&gt;&lt;/div&gt;
```

I trust that this would work with liquid in isolation, but it's not working in Shopify, which is where most people use Shopify liquid.

**Comment by dylanahsmith** [comment]
Note that the `escape_once` filter isn't overridden in Shopify.  Since the input to the escape is coming from a capture tag within liquid, I don't see why it would be Shopify specific.  We do use https://github.com/Shopify/liquid-c at Shopify, but I tested with that as well.

However, I did try within Shopify again.  To further isolate my test, I used your example prefixed with a `{% layout none -%}` line on a page.test.liquid template that I used with a test page.  The rendered page was `<div data='{"body_html":"&lt;div&gt;&lt;/div&gt;"}'></div>` when I used "View Page Source", unlike your example, which is what I would expect.

Something very strange about the output you provided is that part of the template text (e.g. `{"body_html":"`) was escaped, even thought that isn't going through any filtering or other logic.

If that is your minimal example, then does that mean the wrapping div tag is significant?  E.g. do you see the same lack of escaping issue with

```liquid
{% layout none -%}
{%- capture input %}<br>{% endcapture -%}
{%- assign output = input | escape_once -%}
{{ output }}
```

for that, I get `&lt;br&gt;gt;`

**Comment by dylanahsmith** [comment]
Also, are the assign or capture tags significant?  E.g. does `{{ "<br>" | escape_once }}` output `&lt;br&gt;` or is it not escaped either?

**Comment by jeremygottfried** [comment]
Ah looks like it is escaping! On chrome dev tools, it doesn't show up escaped, but if you go to "view page source" it is.
So the real issue is that it's not escaping correctly for more complex HTML strings.

For example: 
```liquid
{%- capture input %}{{ content_for_additional_checkout_buttons }}{% endcapture -%}

{%- assign output = input | escape_once -%}

<div data='{"body_html":"{{ output }}"}'></div>
```

This outputs: 
```html
<div data='{"body_html":"&lt;div class=&quot;dynamic-checkout__content&quot; id=&quot;dynamic-checkout-cart&quot; data-shopify=&quot;dynamic-checkout-cart&quot;&gt;&lt;/div&gt;"}'></div>
```

Something is wrong with the escaped string because if I run
```js
const data = element.getAttribute('data');
JSON.parse(data);
```
That results in an error:
```
Uncaught SyntaxError: Unexpected token d in JSON at position 26
```

I don't get that error if I escape an empty div like `<div></div>`. 
The escape should be escaping in a way that can be read by `JSON.parse`.

**Comment by dylanahsmith** [comment]
Yeah, the page source is what you want to look at to see exactly what liquid is outputting.  The DOM inspector will show you the result of the HTML being unescaped and will show the result of any changes to the DOM from scripts on the page.

The JSON you are parsing is indeed invalid.  Notice that the quotes aren't escaped: 

```json
{"body_html":"<div class="dynamic-checkout__content" id="dynamic-checkout-cart" data-shopify="dynamic-checkout-cart"></div>"}
```

You are dealing with JSON embedded in HTML, so JSON escape using the `json` filter then HTML escape 

```liquid
{% capture some_html %}"{% endcapture%}
<div data='{"body_html":{{ some_html | json | escape }}}'></div>
```
