### ISSUE TITLE
Accessing variables with names such as `g:id`

### ISSUE THREAD

**Issue by TomiHiltunen** [Shopify/liquid#1369]
Hey! 👋

I have a use-case where I have a list of fields that should be accessible as liquid variables. Sometimes, especially with Google related fields, the names can contain special characters such as semicolon as is in the case of `g:id`. Using a template `{{ g:id }}` does not result in the expected value.

Is there a way to access variables with such names and what's the syntax for that? I did read the documentation and searched for a solution before creating this issue but I couldn't find an answer.

**Comment by pushrax** [comment]
This is one way:

```rb
Liquid::Template.parse("{{ ['g:id'] }}").render!("g:id" => 42)
=> "42"
```

Alternatively, for something like this, it would make more sense to store these variables in a separate hash. It's a bit cleaner than having them in the global namespace.

```rb
Liquid::Template.parse("{{ analytics_config['g:id'] }}").render!("analytics_config" => { "g:id" => 42 })
=> "42"
```

**Comment by TomiHiltunen** [comment]
@pushrax, Thank you for taking the time to help. Seems that the syntax you provided does indeed work. What was required in addition was to update the `liquidjs` package a couple of minor versions. :+1:
