### ISSUE TITLE
Covert accent characters to normal characters?

### ISSUE THREAD

**Issue by covalentbond** [Shopify/liquid#1382]
For example `{% assign text = "Crème Brulée" %}`
How to convert it to `"Creme Brulee"`

**Comment by covalentbond** [comment]
@dylanahsmith can you please answer this, thanks!

**Comment by dylanahsmith** [comment]
I think you would need a filter for that purpose.  E.g. shopify has `handle`/`handleize` for converting a string for using in a url, although that seems to be different from your use case given that you want to preserve whitespace.

**Comment by covalentbond** [comment]
I was able to handle the white spaces, just need to know how to convert the accent characters to normal characters:
For more clarity a similar instance:` CrèmeBrulée` to `CremeBrulee`

**Comment by dylanahsmith** [comment]
> Only found `slugify: latin` something related to this in the docs

It seems like you are referring to jekyll based on this reference to `slugify` (https://jekyllrb.com/docs/liquid/filters/), so it seems like this is more of a jekyll question. There isn't a standard liquid filter specifically for this.  The closest to it is a [replace](https://shopify.github.io/liquid/filters/replace/) filter, but it would be quite hacky and slow to use a filter for every possible character you want to replace.
