### ISSUE TITLE
Liquid 5 does not support ActiveSupport::SafeBuffer string substitute

### ISSUE THREAD

**Issue by rhymes** [Shopify/liquid#1390]
Until version 4.x instances of [ActiveSupport::SafeBuffer](https://api.rubyonrails.org/classes/ActiveSupport/SafeBuffer.html) worked well with the `liquid` gem. As many strings moving around a Rails application are actually `SafeBuffer` instances this wasn't an issue on the side of the consumer of the gem.

In version 5.0 though, `liquid` breaks in the following way:

```ruby
1] pry(main)> Liquid::Template.parse(ActiveSupport::SafeBuffer.new("foobar")).render
NoMethodError: undefined method `line_number' for "foobar":ActiveSupport::SafeBuffer
/vendor/bundle/ruby/2.7.0/gems/liquid-5.0.0/lib/liquid/block_body.rb:83:in `rescue in render_node'
Caused by NoMethodError: undefined method `render_to_output_buffer' for "foobar":ActiveSupport::SafeBuffer
/vendor/bundle/ruby/2.7.0/gems/liquid-5.0.0/lib/liquid/block_body.rb:80:in `render_node'
```

This works instead:

```ruby
[2] pry(main)> Liquid::Template.parse(ActiveSupport::SafeBuffer.new("foobar").to_str).render
=> "foobar"
```

By setting a debugger and [checking the diff between 4.0.3 and 5.0.0](https://my.diffend.io/gems/liquid/4.0.3/5.0.0) I noticed that in some places the new code, uses `instance_of?(String)` to determine if something is a string, this though breaks the contract of duck typing, as `SafeBuffer` instances are not instances of `String` (of course)  but behave like a string:

```ruby
[3] pry(main)> ActiveSupport::SafeBuffer.new("foobar").is_a?(String)
=> true
[4] pry(main)> ActiveSupport::SafeBuffer.new("foobar").instance_of?(String)
=> false
```

I can bypass this by forcing `.to_str` on our side but if you're interested (since the dependabot build for this upgrade was broken), I can submit a PR to switch to `is_a?(String)` to make sure duck typing still works.

Here is where `instance_of?` is used in the code: https://github.com/Shopify/liquid/search?q=instance_of

**Comment by tobi** [comment]
I'd love a PR with unit test for that if you could.

**Comment by rhymes** [comment]
@tobi done: https://github.com/Shopify/liquid/pull/1400

**Comment by tobi** [comment]
TYVM!
