### ISSUE TITLE
url_encode & percent encoding RF

### ISSUE THREAD

**Issue by erkde** [Shopify/liquid#1412]
I'm trying to encode a string like `[en] Website Manual` as the value of the `subject` param within a `mailto`, into a "safe" percent-encoded string, e.g. `%5Ben%5D%20WAI%20Website%20Manual`

Is there an alternative to `url_encode`, it turns a space into a `+`, by using `CGI.escape` underneath.

Something like this [gist](https://gist.github.com/ff6347/b9936b2892065272c1b6), seems to handle this use case, but curious if something already exists within the liquid library.

**Comment by ADTC** [comment]
Perhaps a "strict" option can be introduced to enforce converting everything non-alphanumeric to `%`-encoded version 🙂

**Comment by erkde** [comment]
Thank you @ADTC - I think that will do:

```
{{ "[en] Website Manual" | url_encode | replace: "+", "%20" }}
=> %5Ben%5D%20Website%20Manual
{{ "+ " | url_encode | replace: "+", "%20" }}
=> %2B%20
{{ " +" | url_encode | replace: "+", "%20" }}
=> %20%2B
```

e.g. in JavaScript

```
encodeURIComponent("[en] Website Manual")
=> %5Ben%5D%20WAI%20Website%20Manual
encodeURIComponent(" +")
=> %20%2B
encodeURIComponent("+ ")
=> %2B%20
```

**Comment by ADTC** [comment]
Great! Glad it helped! 😄 

I think this issue can be reopened because it's still a standards problem with the `url_encode` rules and logic. There needs to be a `strict` option to control it without having to rely on the `replace` hack.

**Comment by erkde** [comment]
It would be handy, but I'm really not that clear on what the standard is, there seems to be loads of discussion - interpretation - argument on whether it should be a `+` or `%20`, if it doesn't matter, or when it does, which parts of the URL should use one encoding or the other.

I just found using `+` encoding in the subject/body values of a `mailto`, weren't being decoded back to space when opening with the Mail app I tested it with, but I wouldn't be sure if the same limitation applies to other kinds of URL, or URL parts, or even other Mail apps.
