### ISSUE TITLE
`{% liquid %}` tag prevents `content_for_layout` being recognised

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/liquid#1429]
Adding the following code:

```liquid
    {%- liquid
      section 'header'
      echo content_for_layout
      section 'footer'
    -%}
```

Prevents Shopify from recognising the presence of `content_for_layout`.
Using ThemeKit, I'm given the error: `Missing {{content_for_layout}} in the body section of the template`

**Comment by ADTC** [comment]
Does it work when doing `{{ content_for_layout }}` outside the `liquid` tag?

**Comment by ConduciveMammal** [comment]
It does, yeah.
I compromised and changed it to

```liquid
    {%- liquid
      section 'header'
    -%}
    {{ content_for_layout }}
    {%- liquid
      section 'footer'
    -%}
```

**Comment by pushrax** [comment]
Fix going out soon.

**Comment by ADTC** [comment]
Have you also fixed it for `content_for_header`? I don't know what else is out there.

**Comment by pushrax** [comment]
Yes, `content_for_header` was fixed at the same time. Just the two of them were affected by this issue.

**Comment by ADTC** [comment]
@pushrax where do I report problems like the above with the Shopify Code Editor? I found another problem:

The syntax highlighting for `liquid` tag breaks when using `comment`. See how the highlighter doesn't resume from `endcomment`:

![image](https://user-images.githubusercontent.com/6047296/115832935-101e0180-a446-11eb-87c9-9642058326cb.png)
