### ISSUE TITLE
conditional loop

### ISSUE THREAD

**Issue by dcalixto** [Shopify/liquid#1432]
Hello, someone can inform if is possoble to make a conditional loop that depend if the attribute is nil?

for exemple:

{% for boat in site.boats %}

{{ boat.name }}

  {% endfor %}

boat.md
name: Azimut
sell: yes

if the sell is not nil, show the boat

**Comment by ADTC** [comment]
Either:
```
{% if boat.sell %}
{{ boat.name }}
{% endif %}
```
Or:
```
{% liquid
if boat.sell
  echo boat.name
endif
%}
```

**Comment by ADTC** [comment]
We have very little information to go on here. How can I contact you?

**Comment by dcalixto** [comment]
hello @ADTC thank you very much for your help. you can contact me by calixtodaniel@gmail.com or https://talk.jekyllrb.com/u/jjplack

**Comment by dcalixto** [comment]
@ADTC thank you very much!
that’s it worked smoothly, i did just forget to place after the loop! thank you 
```
{% if boat.sell %}
{{ boat.name }}
{% endif %}
```
