### ISSUE TITLE
No carriage return after declaring a custom rule in robots.txt.liquid

### ISSUE THREAD

**Issue by milkbottlelough** [Shopify/liquid#1464]
Hey,

So _strictly speaking_ this is not a liquid issue but the issue is occurring in a file with the extension of liquid so I'm noting the issue here.

When adding a new rule in robots.txt.liquid using this code (taken from the Shopify dev docs here: https://shopify.dev/themes/seo/robots-txt):

`  {%- if group.user_agent.value == '*' -%}
    {{ 'Disallow: /collections/some-collection-to-hide' }} 
  {%- endif -%}`

no carriage return occurs after the rule is rendered in robots.txt:

![new rule](https://user-images.githubusercontent.com/45833805/125112141-af19d780-e0de-11eb-8a61-98f6228856dc.jpg)

This results in:

![new_rule_result](https://user-images.githubusercontent.com/45833805/125112162-b80aa900-e0de-11eb-80aa-47ae4efcc07a.jpg)

There is no way (or at least my testing indicates as much) to enter a line-break (\n or <br/> etc) to ensure the sitemap returns to the next line.

Having the sitemap URL appearing as above has the potential to cause issues with some crawlers.

thanks
L.

**Comment by nresh** [comment]
hey @milkbottlelough, I just set up the dawn theme and updated `templates/robots.txt.liquid` here https://github.com/nresh/dawn-custom/blob/master/templates/robots.txt.liquid.  I cannot reproduce your issue.

when I serve the theme locally or when I view the published version of the dev store online, this is what I see in `/robots.txt`:
<img width="508" alt="Screen Shot 2021-07-12 at 2 23 03 PM" src="https://user-images.githubusercontent.com/9378055/125357745-e2e24080-e31c-11eb-8ebc-4343bcde8577.png">

my best guess is that (A) the issue has been fixed and you're working with an older version of the theme or liquid, (B) your liquid file has some hidden characters in the whitespace (perhaps from copy/pasting) that are screwing things up

**Comment by milkbottlelough** [comment]
Hi @nresh 

Thank you for looking into that for me.  Interesting, I double-triple checked my code for hidden chars or whitespaces that might be throwing things. Or so I thought.

Looking more closely I can indeed see an errant character that is not a standard line break/carriage return ( I have still to figure out what it is and where it came from )

![Image 2021-07-12 at 11 22 20 pm](https://user-images.githubusercontent.com/45833805/125363273-3e85eb80-e368-11eb-84d3-bcc58060478d.jpg)

Anyway, removing this character fixes my issue. 

Appreciate your time and the help!
L.
