### ISSUE TITLE
class Random already exists

### ISSUE THREAD

**Issue by fade2black** [Shopify/liquid#1591]
Could you please change the class name `Random` in [this](https://github.com/Shopify/liquid/wiki/Liquid-for-Programmers) example? Doesn't `Random` already exist in Ruby's core library?

The following definition my result in the following error: `superclass mismatch for class Random` because the `Random` class is already defined somewhere else (in the core lib in particular, at least for Ruby 3).

```ruby
class Random < Liquid::Tag
# ...
end
```

**Comment by dylanahsmith** [comment]
Sure, I've made the change
