### ISSUE TITLE
Make "truncatewords" and "truncate" work for non-English characters

### ISSUE THREAD

**Issue by hupili** [Shopify/liquid#166]
Hi, I built a the following site recently:

[http://hupili.github.com/](http://hupili.github.com/)

I use the following piece to present the excerpt in post index:

```
<p>{{ post.content | strip_html | truncatewords: 5 }}</p>
```

It seems `truncatewords` counts according to blanks, so the above means essentially 5 English words or 5 sentences if I'm writing in Chinese. If I set it as small as 5, the except does not look good for my post starting with English. If I set it bigger, e.g. 50, the Chinese post will look worse (too many lines for an excerpt). 

One solution is to use "truncate" instead:

```
<p>{{ post.content | strip_html | truncate: 5 }}</p>
```

It introduces another problem. Since the article is written in non-asccii characters, some characters in the end is chopped from the middle, resulting in a question mark inside a black square. Is there any way to tell the engine my encoding (e.g. 'utf-8') and let it operate on the correct boundary of characters? 

Redirected from [https://github.com/mojombo/jekyll/issues/732](https://github.com/mojombo/jekyll/issues/732)

**Comment by Marina-Ma** [comment]
It has been solved when the code is changed to {{post.content | strip_html | truncate:200}}

**Comment by jumbosushi** [comment]
Had the same issue but replacing `truncatewords` with `truncate` did the trick for me as well
