### ISSUE TITLE
Backporting Ruby 3.2 support to 4.x series

### ISSUE THREAD

**Issue by janko** [Shopify/liquid#1664]
It seems that Jekyll still has Liquid locked to versions 4.x, and it doesn't seem like this will change soon. It would be great if Ruby 3.2 support was backported to Liquid 4.x, as that should hopefully allow current Jekyll to run on Ruby 3.2 🙏🏻

**Comment by parkr** [comment]
Cc https://github.com/github/pages-gem/issues/859

**Comment by dylanahsmith** [comment]
I've opened https://github.com/Shopify/liquid/pull/1668 to backport ruby 3.2 support.  However, we should really implement https://github.com/Shopify/liquid/issues/1566 to get jekyll on liquid v5.

**Comment by dylanahsmith** [comment]
Fixed by #1668, and I've released liquid version 4.0.4 and liquid-c version 4.0.1

**Comment by parkr** [comment]
Hugely appreciated, Dylan!
