### ISSUE TITLE
Release a new gem version

### ISSUE THREAD

**Issue by isaacbowen** [Shopify/liquid#1715]
5.4.0 was the last version cut, and that [was back in July of 2022](https://github.com/Shopify/liquid/commit/6f8722a).

My specific motivation in filing this is that `{%- endraw -%}` didn't start working until https://github.com/Shopify/liquid/commit/74e505f, in February, and I'd like to be able to use that with an official stable release. :D

**Comment by drnic** [comment]
Now that it's nearing the end of September 2023 perhaps a new v5.5 release? Thanks in advance

**Comment by isaacbowen** [comment]
closed by #1791 ☺️ 🧘
