### ISSUE TITLE
Add Census to "Who uses Liquid?" wiki section

### ISSUE THREAD

**Issue by dcecile** [Shopify/liquid#1752]
👋 Hi! Here at [Census](https://www.getcensus.com/) we're huge fans of Shopify's contributions in the Ruby world and Liquid is now on that list!

We're using Liquid to let our users apply "last mile" transforms to their data on the way from their data warehouse sources (e.g. Snowflake, BigQuery) to their service destinations (e.g. HubSpot, Google Ads, Shopify).

We just finished publishing a new docs page here: https://docs.getcensus.com/basics/core-concept/liquid-templates

Can you add us to the [Who uses Liquid?](https://github.com/Shopify/liquid/wiki#who-uses-liquid) section on the wiki?

I'd be happy to volunteer to make the change and also work through the other [open wiki issues](https://github.com/Shopify/liquid/issues?q=is%3Aissue+is%3Aopen+wiki). (Unfortunately GitHub doesn't support [PRs for wikis](https://github.com/orgs/community/discussions/50163).)

**Comment by ianks** [comment]
Done! Thanks for the heads up
