### ISSUE TITLE
Add line numbers to error messages

### ISSUE THREAD

**Issue by trishume** [Shopify/liquid#245]
All other programming languages give line numbers in syntax errors, Liquid should too.

Basic outline of how it could be done:
- Implement new tokenizer that preserves line info.
    - The thing that splits a template into tags and text, currently it is a regex and abusing the split function.
    - The new tokenizer should generate an array of String subclasses that include a line number.
- Modify the SyntaxError class to include a line field, then modify the message method to append the line number to the message. Or something like that.
- At some point, catch all SyntaxErrors and append line info.
    - This could possibly be done in Block#parse.

**Comment by dylanahsmith** [comment]
This has been implemented by #419 and #455.
