### ISSUE TITLE
Insufficient documentation: "include with" and variable types

### ISSUE THREAD

**Issue by dalgard** [Shopify/liquid#252]
I'm having a hard time figuring out how to use variables in Liquid and the documentation is quite scanty. I realize I can do `{% assign foo = "bar" %}`, but how about arrays and objects? I know they exist as data types in Liquid, but I don't know how to create them inline. (I can use the `split` filter on a string, but is that all?)

What I'd really like to do is something like `{% include "module" with { items: 5, big: true } %}` - can this be achieved? Thanks.

**Comment by sebmaynard** [comment]
https://docs.shopify.com/themes/liquid-documentation/tags/theme-tags#include

Turns out you can now pass extra params with include:
{% include 'snippet', snippet_variable: 'this is it', snippet_variable_two: 'this is also it' %}

**Comment by tdhatcher** [comment]
Here's how I do it

Create a snippet named "dump.liquid" with the code
```
<script type="text/javascript">
 console.log("Dumping");
 console.log({{ dump | json }});
</script>
```

Usage in template files:
`{% include 'dump' with [OBJECT] %}`

Example.
Within product.liquid template file
`{% include 'dump' with product %}`

Open Chrome console and you will see an object that you can drill into and explore.

**Comment by seanwbarry** [comment]
For others that come across this - there is now good documentation here: 

https://help.shopify.com/themes/liquid/tags/theme-tags#include

If you search for 'include tag parameters' on that page you will find the documentation regarding the usage of 'with' (there is an example to further explain @tdhatcher code).
