### ISSUE TITLE
Do not support Ruby 1.9 Hash syntax

### ISSUE THREAD

**Issue by camsong** [Shopify/liquid#289]
``` ruby
Liquid::Template.parse("Hi {{name}}").render("name" => 'liquid')
```

works, while those two not work.

``` ruby
Liquid::Template.parse("Hi {{name}}").render(name: 'liquid')
```

``` ruby
Liquid::Template.parse("Hi {{name}}").render(:name => 'liquid')
```

Since they are standard ruby syntax, it's better to support them all.

@arthurnn

**Comment by huyderman** [comment]
Now that Ruby 2.2 has added GC for symbols, will support for symbols as keys be reconsidered for future versions?

**Comment by gjtorikian** [comment]
Would a PR to accept symbolized keys for 2.2+ be accepted? I'll do the work!

As suggested in https://github.com/Shopify/liquid/issues/82#issuecomment-33705446, I'd probably make this an opt-in choice so as not to blow-up backwards compatibility. 

/cc @tobi @fw42

**Comment by fw42** [comment]
I would consider it if there are performance benefits to that. If not then I don't really see what problem it solves.

**Comment by gjtorikian** [comment]
Cool, I'll whip something up and benchmark it.

> If not then I don't really see what problem it solves.

It's more about the element of least surprise, I feel.

**Comment by huyderman** [comment]
> If not then I don't really see what problem it solves.

There are a lot of libraries for models that `#to_hash` with symbolic keys. As it is now, you'll need to deep-stringify keys, which is kinda cumbersome and error-prone. The need to stringify the hash beforehand probably also adds some overhead.

**Comment by gjtorikian** [comment]
Eh. Maybe it's not worth it, performance-wise. Here's what I get after adding to the existing benchmarks test:

```
parse & run with strings:
                         19.849  (±10.1%) i/s -      1.184k
parse & run with symbols:
                         19.437  (± 5.1%) i/s -      1.160k
```

Here's my work if anyone wants to look it over: https://github.com/Shopify/liquid/compare/master...gjtorikian:symbol-keys

I didn't get around to checking options and parsing if this is on Ruby > 2.2. 

I do think that deep stringifying keys is problematic but given that the maintainers of this project are looking for performance gains before accepting such a change (and it's well within their right to do so) I'm not going to pursue this much further. 

If someone's more passionate about opening a PR around this, feel free to `git cherry-pick`.

**Comment by tobi** [comment]
One thing to look for is object creation. I can imagine that symbolized keys produce a lot less garbage because repeat use is just a reference to another symbol. 

- tobi
CEO Shopify

(mobile)

**Comment by fw42** [comment]
Thanks for trying this out and for showing us the code in your branch!

I could imagine that there might be a performance benefit to enforcing symbols (i.e. don't support string keys anymore and use/assume symbols internally everywhere). Supporting both at once, I would expect to be slower (or at least not faster).

**Comment by dylanahsmith** [comment]
I don't like the type checks in your branch (e.g. `key = key.to_s unless key.is_a?(String)`), since we should just unconditionally coerce to the type of key we store internally (e.g. `key = key.to_s`).  This would also avoid another thing that I don't like about your branch, which is that you store a mix of symbols and strings in the hashes, then have the lookup check for both, falling back on `nil`.

If we wanted to store symbols internally, we would probably want to wait until after we stop supporting ruby 2.1 or any older versions of ruby, so we would have to wait a while.  At that point we would just change the key coercion to use `.to_sym` instead of `.to_s`.
