### ISSUE TITLE
It went crazy when included partial share the same name with the hash key of an array parameter passed in.

### ISSUE THREAD

**Issue by IrvinFan** [Shopify/liquid#293]
I have a partial liquid as shown below in /tmp/_part.liquid:

```
In part: {% for d in part %} {{ d }} {% endfor %}
```

Set up liquid file system so that 'include' can find it:

```
> Liquid::Template.file_system = Liquid::LocalFileSystem.new('/tmp')
```

Now render a liquid string that include the partial and pass an array in using key 'part':

```
> Liquid::Template.parse("Hello: {% include 'part' %}").render('part' => ['one', 'two'])
 => "Hello: In part:  one In part:  two "
```

It looks like the partial was invoked twice and each time only one element was passed in.
If I change the hash key of the parameter to something different from the partial liquid name:

```
In part: {% for d in new_name %} {{ d }} {% endfor %}
```

everything works fine:

```
> Liquid::Template.parse("Hello: {% include 'part' %}").render('new_name' => ['one', 'two'])
 => "Hello: In part:  one  two "
```

Why was that? name conflict?

**Comment by shopmike** [comment]
Because Liquid has always been this way this is considered standard behavior that can not be removed. To accomplish the intended outcome the `{% include 'tags' tags: blog.all_tags %}` syntax should be used
