### ISSUE TITLE
Custom syntax

### ISSUE THREAD

**Issue by Fodoj** [Shopify/liquid#311]
It's more of a question than feature request, because my task is very specific. I need to write some template engine, but writing it from scratch is a pain, so I decided to just extend Liquid for my needs. So my question is - is there a way to define custom syntax for tags\blogs? So now tags are found by this characters - {% ... %}. What I need is ability to define my own tags and each of them with custom syntax. 

So for example I need to match this thing: mytag="..." and also somehow get parent of this thing, for example if I have `<li mytag="...">` I should get `<li>` node and contents of my tag and then render it as I want. 

I suppose explanation is slightly lame, but I hope you get an idea. Is there any way to do this thing using liquid or I should really go with writing my own templating engine? :)

**Comment by Tomarron** [comment]
I am interested in how the syntax "endfor" come from  ,if it not the syntax of ruby
