### ISSUE TITLE
Passing variable as argument directly on template to Liquid Tag

### ISSUE THREAD

**Issue by bonfocchi** [Shopify/liquid#360]
Hi all,

Is there a way to pass variables as arguments directly to a liquid tag?

Assume:

```
{{ assign sub_menu_parent = 'foo' }}
```

If I have a drop I can use this:

```
{{ my_drop.[sub_menu_parent] }}
```

**This will work for the Drop!**

But on my menu Tag the same WILL NOT WORK:

(**I get this error:** Liquid error: undefined local variable or method `sub_menu_parent' for #)

```
<h4>{{ sub_menu_parent }}</h4>
<aside>         
   {% menu {name: 'mainmenu', ul_id: '', parent_label: [sub_menu_parent]} %}
</aside>    
```

I also tried this and it DOESN'T WORK EITHER:

(**I get this error:** Liquid error: undefined local variable or method `sub_menu_parent' for #)

```
<h4>{{ sub_menu_parent }}</h4>
<aside>         
   {% menu {name: 'mainmenu', ul_id: '', parent_label: sub_menu_parent} %}
</aside>    
```

The thing is that the variable is there since if I remove the menu liquid Tag,  H4 will be 'foo' (`<h4>foo</h4>`):

```
<h4>{{ sub_menu_parent }}</h4>
```

I know I can use context inside the Tag code:

```
class Menu < Liquid::Tag
  def initialize(tag_name, params, tokens)
     super
    @params = eval( params.strip )

    @name = @params[:name] ? @params[:name] : nil
    @ul_id = @params[:ul_id] ? @params[:ul_id] : nil
    @parent_label = @params[:parent_label] ? @params[:parent_label] : nil

  end

  def render(context)

    # Do stuff...

    if @parent_label.present?
        # I know I can use this, but I don't like this solution
        if context[@parent_label].present?
             @parent_label = context[@parent_label]
        end 
        # Do stuff...
    else
        the_parent = nil
    end

    # Do stuff...

    output = output.html_safe
    output
      end
...
  end
```

Keep in mind that the Tag code works and is loaded.

Is there a way to pass a variable as argument to a tag directly on the template, without searching context on the tag code? Just like I exemplified on the drop code..

Sincerely,

Rich

**Comment by rafimd** [comment]
how  to post the values from invoice page
