### ISSUE TITLE
truncate filter returns ellipses instead of characters

### ISSUE THREAD

**Issue by budparr** [Shopify/liquid#366]
liquid (2.5.5)

Hi, I'm using Liquid in Jekyll and am experience unexpected behavior in the truncate filter.

In a for loop where value = foobar

```
 {{ item.value  | truncate: 1 }}
```

I get the following returned: `...` 

I would expect `f`. 

If I change the truncate filter to  `truncate: 4` it appears to remove the ellipses, but this gives me no result at all if my value is less than 4 characters, so is not an acceptable workaround. 

(_my use-case is last names that I'm trying to get just the first character of_)

**Comment by arthurattwell** [comment]
For anyone else stumbling across this desperate for a solution: `truncate` and `truncatewords` take a second parameter that appends a string. It defaults to `…`, and you can set it to something else, including `""` for no string. So you should be able to use

`{{ item.value  | truncate: 1, "" }}`

This second parameter is mentioned in [Liquid for Designers](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#standard-filters) but not in the official [Liquid docs](https://help.shopify.com/themes/liquid/filters/string-filters#truncate).

**Comment by admhlt** [comment]
Thanks @arthurattwell — I've added explanation of the second parameter of `truncate` and `truncatewords` to the [core Liquid docs](https://shopify.github.io/liquid/filters/truncate/) and [Shopify's Liquid docs](https://help.shopify.com/themes/liquid/filters/string-filters#truncate).
