### ISSUE TITLE
Support for raw include for inlining CSS, SVG, etc.

### ISSUE THREAD

**Issue by manastungare** [Shopify/liquid#370]
I’d like to inline tiny bits of CSS and a few SVG images for performance-critical paths. I found that `{% include file.css %}` tries to parse the inlined file as HTML, which, of course, fails for CSS & SVG.

`Invalid syntax for include tag. File contains invalid characters or sequences:`

`{% raw %}` doesn’t quite work either, since that prevents transclusion in the first place.

Something like `include_raw` or `include file.css raw=true` could include the raw files, but treat them as opaque non-markup text.

Is this something Liquid could support?

**Comment by mrkgnao** [comment]
I'm having some trouble with this. I have a small Jekyll blog hosted on GitHub Pages, and it features some math, so I have a LaTeX preamble file with some macros etc. that I `{% include %}` into the blog post body.

However, some LaTeX macros have a `{%` in their syntax, which obviously freaks Liquid out and makes Jekyll fail to compile the static files.

Is there any chance of an `include_unescaped_file` being a thing?

**Comment by mrkgnao** [comment]
Well, I can hack around it for now by just putting a `{% raw %}` at the beginning of the text file and an endraw at the end.

**Comment by jonhoo** [comment]
I have this as well when including a page that contains BibTeX descriptions, which often contain `{{`. The solution for now seems to be that I need to modify the file being included to be wrapped in `{% raw %}`, but that's hard as it is externally generated.

**Comment by admhlt** [comment]
If you're having this issue when using Jekyll, it might be an issue with Jekyll's implementation of `include`: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/tags/include.rb

Feel free to [open an issue in the Jekyll repository](https://github.com/jekyll/jekyll/issues).

**Comment by mhansen** [comment]
This is a very old issue, but in case anyone finds this googling, here's a solution:

Put `raw_include_relative.rb` in `_plugins/` directory at your Jekyll root:
```
# raw_include_relative.rb
module Jekyll
  module Tags
    class RawIncludeRelativeTag < IncludeRelativeTag
      # Overriding is explicitly allowed, to modify file content by subclassing:
      # https://github.com/jekyll/jekyll/blob/f5826eed3cde692f84e35140209d5a59ec3eb295/lib/jekyll/tags/include.rb#L178
      def read_file(file, context)
        # Hack: instead of including the file directly without liquid escaping,
        # simply wrap the entire file in a `raw` liquid tag, suppressing liquid
        # processing.
        "{% raw %}" + super + "{% endraw %}"
      end
    end
  end
end

Liquid::Template.register_tag("raw_include_relative", Jekyll::Tags::RawIncludeRelativeTag)
```

Then you can use `{% raw_include_relative somefile.txt %}` just as you would use `include_relative`.
