### ISSUE TITLE
Refresh Documentation Website

### ISSUE THREAD

**Issue by parkr** [Shopify/liquid#399]
Had a chat with @fw42 a couple days ago and one thing we'd like to see happen is a reboot of http://liquidmarkup.org. The current site was last updated on Sep 7, 2011. Additionally, the current docs that Shopify has put out have some proprietary filters and tags that aren't available to those using this library. It'd be great to be able to provide a distinction between "here's what we offer publicly" and "here's what is available only to Shopify customers."

It could also use some :lipstick:.

Ideally, we wouldn't have to reinvent the wheel for each docset. If there's a way to build Shopify's docs around this repo's docs (maybe using submodules?), that would be perfect.

- [ ] Add description, usage, & examples for each filter
- [ ] Ensure docs remain for integrating Liquid into Rails
- [ ] Point to help resources for Jekyll (if you're interested) so you don't get questions about this or that when it might be Jekyll's own tag or filter.
- [ ] Redesign for :sparkles: and :smile: ?
- [ ] Nail down the best way to keep Shopify's docs in sync with docs for this repo
- [ ] Where should we store the docs?

**Comment by parkr** [comment]
@Tetsuro Would you be willing to push a branch here? I really would like to see this.

**Comment by Tetsuro** [comment]
Apologies for the delay on this, @parkr. Admittedly I had to place this on the back burner during the busy period of Q4 :cry: 

Before I left off I was working on Sketch designs for the new docs site, which includes the layout as well as the styling of the markdown outputs. I'm going to hop right back on that and post here with updates. 

In the meantime, did you want to start thinking about the organization of content? For [Shopify's Liquid docs](http://docs.shopify.com/themes/liquid-documentation/basics), I broke down the content into the following four categories: 

- Basics
- Tags
- Objects
- Filters

Do you see this working for the core Liquid docs as well? I'm open to change things around if you feel it's necessary.

**Comment by parkr** [comment]
Thank you! No problem at all.

Yes, i was thinking we could create a collection for each category of items. We'd also want to clearly demarcate what is Shopify.com-only and what is Liquid core, and have a permalink for each component. Examples will be paramount.

**Comment by parkr** [comment]
Still into this?

**Comment by Tetsuro** [comment]
@parkr Indeed! Recently recruited @dtKinger to help me with sorting out the content. Let's aim to get this wrapped up by the end of July.

**Comment by parkr** [comment]
> Let's aim to get this wrapped up by the end of July.

+ :100: 

Thanks for the help, @dtKinger!
