### ISSUE TITLE
Can't Concatenate / Join Arrays

### ISSUE THREAD

**Issue by parkr** [Shopify/liquid#427]
Hey,

I was just reviewing the Jekyll issues and saw [this comment](https://github.com/jekyll/jekyll/issues/2793#issue-40882124) by @sylvaindurand:

> I couldn't find a way to perform a loop on both elements, by joining site.posts and site.pages (or site.posts and site.documents), or finding another variable. Is this possible ? It would be great and I don't think it would be too specific.

I agree that we should have a way to join arrays. I tried doing this with `+` but no dice. I tried doing this with `| plus: ` but also, no dice.

Do you think this is a worthy feature for the standard filters or for the `+` operand? Seems pretty straight forward and necessary to me.

**Comment by rohitpaulk** [comment]
+1 on this, #429 (improving `append` to handle arrays) looks like a good solution.

**Comment by thiagodebastos** [comment]
+1 to this! I am looking for a way to display all collections in one masonry grid

**Comment by fw42** [comment]
@pushrax I think https://github.com/Shopify/liquid/pull/540 addressed this issue, right? Can we close?
