### ISSUE TITLE
products global within shopify

### ISSUE THREAD

**Issue by reggi** [Shopify/liquid#438]
> **Note**, this issue is specifically for Shopify's implementation of liquid on their website.

We should be able to do this:
```
{{ products["austin-leaf-map-poster"].url }}
```

But we (developers) don't have access to a `products` global.

Instead of having access to the global. I have to hack something together like this:

`function.get_product.liquid`

```
{% assign return = false %}
{% if pass_product_handle and collections["all"] %}
  {% for product in collections["all"].products %}
    {% if pass_product_handle == product.handle %}
      {% assign return = product %}
    {% endif %}
  {% endfor %}
{% endif %}
```

`usage.liquid`

```
{% assign pass_product_handle = "austin-leaf-map-poster" %}
{% include "function.get_product" %}
{% assign product = return %}
{{ product.url }}
 
{% assign pass_product_handle = "boston-leaf-map-poster" %}
{% include "function.get_product" %}
{% assign product = return %}
{{ product.url }}
```

It can't be good for Shopify to have to interpret this loop every time I need product information, no?

**Comment by sinak** [comment]
Hi wonderful Shopify people. I just ran across the same issue, and thought I'd chime in and say I hope this gets implemented soon.

My specific use case: we have some products on our site that our discontinued. I'm using a custom metafield to allow an admin to redirect a product to a replacement, but I need the products global to be able to add an appropriate link.

In the meanwhile, my hack is going to be to create multiple "function1.get_product.liquid" "`function2.get_product.liquid`" etc files, each of which searches a 50 product range.

And while I've got your attention, I'll also point out another shopify-liquid shortcoming I've noticed: there doesn't appear to be a way to access the "page_title" and meta "page_description" of a particular collection/product/page etc from a *different* page. So, for example, I can't do `collections['all'].page_title` in my `theme.liquid` file. I'd be using it to add customized page titles based on the collection/tags selected. Not sure how much of an edge case this is, but I thought I'd mention it. I wasn't sure whether I should create a separate issue given that this is very much a Shopify-specific issue.

**Comment by sinak** [comment]
One more quick note in response to @kyleaparker's comment that product handle's may change:

I think it'd be generally useful to be able to globally search based on the object. So for example letting one to do something like `{{ collections[25201093].title }}`.

I'm not sure if this'd be useful for anything other than site-specific themes, but I'd love to be able to search for objects by something other than their handles.

**Comment by reggi** [comment]
Thanks for sharing the use-case @sinak. 

I think handle-based lookup is fine. We already use it for `blogs["example-handle"]`, `collections["example-handle"]`, `pages["example-handle"]` and it's not surprising that `products` should work the same. 

As for your issue with the title / meta description @sinak those Shopify puts those in as metafields so you should be able to access those via that was from 

```
{{ product.metafields.global.description_tag }}
```

and


```
{{ product.metafields.global.title_tag }}
```

**Comment by sinak** [comment]
Ah the metafields part is great, thanks @reggi. 

I agree it makes sense that products should support searching by handle, but I wonder if there are other users who'd appreciate the id-based lookup in addition (not as a replacement). Not a big deal by any means though.

**Comment by reggi** [comment]
@fw42 @carolineschnapp Just came up with a dire use case for this again. Would love to hear when / if this is gonna be put into production. =]

```
.d88888b  dP                         oo .8888b          
88.    "' 88                            88   "          
`Y88888b. 88d888b. .d8888b. 88d888b. dP 88aaa  dP    dP 
      `8b 88'  `88 88'  `88 88'  `88 88 88     88    88 
d8'   .8P 88    88 88.  .88 88.  .88 88 88     88.  .88 
 Y88888P  dP    dP `88888P' 88Y888P' dP dP     `8888P88 
                            88                      .88 
                            dP                  d8888P  
 888888ba   .88888.   a88888b. dP     dP .d88888b  dP 
 88    `8b d8'   `8b d8'   `88 88   .d8' 88.    "' 88 
a88aaaa8P' 88     88 88        88aaa8P'  `Y88888b. 88 
 88   `8b. 88     88 88        88   `8b.       `8b dP 
 88     88 Y8.   .8P Y8.   .88 88     88 d8'   .8P    
 dP     dP  `8888P'   Y88888P' dP     dP  Y88888P  oo 
                                                      
```

**Comment by rickydazla** [comment]
:+1:  for this, not least because of excellent case put forward by @reggi - identifying _related products_ is one use case, and grabbing products from tags within blog.articles another...

**Comment by Jolora** [comment]
I too hope this gets sorted soon. I keep coming across use cases for this.

**Comment by zoerooney** [comment]
+1 - this would be super helpful for accessing product data via API from other sites as well (e.g. featuring a specific product by handle on an external blog)

**Comment by rickydazla** [comment]
I just used the snippet that @reggi added above to link to a specific Product that was being given away as part of a competition, from a Page template...

**Comment by sinak** [comment]
Any updates on this? Would be so helpful!

**Comment by mrpunkin** [comment]
Any updates? It would seem with things like App Proxies that having a way to get a product from ID or handle on an API-based app page is a dire need, without hacking together a different solution.

**Comment by fw42** [comment]
This has been implemented as `all_products['my-handle']` in Shopify. Our documentation hasn't been updated yet, but will do that soon. Sorry this took so long.

**Comment by rickydazla** [comment]
Sweet! :cake:

**Comment by mrpunkin** [comment]
Excellent news! Excited to implement this later today.

**Comment by reggi** [comment]
Thanks to every @shopify + @fw42 that made this happen. :+1: :heart: :dolphin: :rainbow: :smile:

**Comment by mennyg** [comment]
it seems however, that there is a limit on how many unique product handles you can use the all_products filter for. I got this on my webpage after running through a couple of productHandles
`Liquid error: Exceeded maximum number of unique handles for all_products. `

Is this on purpose? I'm running a list of productHandles from a metafield and any metafield that has more than 5 producthandles, gets this error message

**Comment by fw42** [comment]
yes that's on purpose. if you want many products then this is the wrong tool, use a collection for that

**Comment by mennyg** [comment]
I'm just wondering why this is limited. I'm trying to list more than one product (sometimes many more than one) on a product as shown [Here](https://github.com/reggi/shopify/issues/18) Towards the bottom. How would I implement that using a collection?

**Comment by estrattonbailey** [comment]
Sweet! Thanks for the addition @shopify Team.

We're building a store with multiple different versions of the same product – tailoring of a shirt – plus variants – sleeve length, collar size, etc – making total variants around 140+ in some cases, which obviously doesn't work by default. This is handy because I can aggregate variant IDs and JSON from all three products onto one page without shooting off three separate AJAX requests after load. 

It'll end up being a mixture of both AJAX and Liquid once we build in add-to-cart functionality, but pretty useful, nonetheless. Cheers!

**Comment by resistorsoftware** [comment]
I find the current limit of 20 is too small. And I really beg to differ with fw42 saying if you want more than 20 you're doing it wrong, use a collection. Using a collection is not always the right solution. It is a solution but not the only one. It can be the wrong solution when it forces Apps to pollute a shop with collections that may piss off the merchant. 

It is possible you can write efficient SQL to address this weakness without giving up right away and writing this off as "use a collection". If it is demonstrably impossible, well holy smokes! SQL has met its match! Never heard of that yet, but I suppose that there is always a first time.

Please. Thanks.

**Comment by CarlowSEO** [comment]
Also have to agree that the limit is precarious at best, as well as the fact that doing this by ID would be extremely helpful (or improving the ajax calls to allow lookup by ID and/or SKU)

**Comment by fdsze** [comment]
@fw42 It would be really nice of you (or your colleagues) to update the documentation at: https://help.shopify.com/themes/liquid/basics/handle 
It will probably benefit a lot of new theme developers!

**Comment by admhlt** [comment]
@fdsze Thanks for the reminder. :)

I've updated our documentation for the `all_products` global object to include info on accessing single products using handles:

https://help.shopify.com/themes/liquid/objects#all_products

**Comment by coderapper** [comment]
Hello Everyone,

I'm also kind of stuck due to the limit on `all_products` global object. it would be nice to have it removed. in the shop that we are working on, each look product has multiple products within itself, for which we are using product handles and then iterate the products in look product page using `all_products`. Obviously, 20 unique handles for all_products would be very low for stores like this and there are quite many stores which use 'all_products'. i would like to know if its possible for you to remove this limit ?

**Comment by carolineschnapp** [comment]
@coderapper collections are best used for this. You can store the handle of the collection you need in a product metafield.

**Comment by coderapper** [comment]
@carolineschnapp  Actually, I found a better way using Jquery to generate dynamic data based on the handles for each product that we loop through in the collection page. it works!

**Comment by charlesemarsh** [comment]
This has been a massive help for me today, just showing off a single featured product on the homepage, I'm not able to grab this straight from theme settings, much easier for the client to understand. 

Awesome job Shopify!

**Comment by gina3five** [comment]
Any reason this doesn't seem to work in the checkout.liquid template?
