### ISSUE TITLE
New array filters for finding and selecting items without looping

### ISSUE THREAD

**Issue by jdlich** [Shopify/liquid#451]
Sometimes I would like to be able to select an item or items out of an array without having to loop through it. This is more or less for style points, but I think it would add a nice touch to liquid. For example, let's suppose I want to find a particular product image based on alt text. Instead of looping:

``` liquid
{% assign video = false %}

{% for image in product.images %}
  {% if image.alt contains "http" %}
    {% assign video = image %}
  {% endif %}
{% endfor %}

{% if video %}
  …
{% endif %}
```

We use a find filter which acts like contains:

``` liquid
{% assign video = product.images | map: "alt" | find: "http" %}
```

Of course this wouldn't work because the object is lost after map and the resulting value of video would be just a string, which got me thinking… What if we had dynamic find filters for each object property?

``` liquid
{% assign video = product.images | find_alt: "http" %}
```

That's probably too involved. Maybe find has two arguments?

``` liquid
{% assign video = product.images | find: alt, "http" %}
```

Or there's a separate filter for performing the match, so we could match a substring or exact match?

``` liquid
{% assign video = product.images | find: alt | contains: "http" %}
{% assign special = product.images | find: alt | is: "special" %}
```

There could also be a `select` filter which works the same way but returns an array.
Anybody have any thoughts on this?

**Comment by JarrettBillingsley** [comment]
Am I missing something or is there no documentation on the `where` filter? I've looked under all the pages [on here](https://help.shopify.com/themes/liquid/filters) and can't find it.

**Comment by jdlich** [comment]
@JarrettBillingsley The `where` filter is in Jekyll, not Shopify. Unfortunately…

**Comment by JarrettBillingsley** [comment]
Ohhhhhh. Okay. That's confusing! Thanks.

**Comment by hcmlopes** [comment]
I would love to see this capability added as well. Any status ?

**Comment by SergeyPavlovsky** [comment]
I would love to see this capability added as well. Any status ?

**Comment by richardmonette** [comment]
@jdlich I think this may have been added https://github.com/Shopify/liquid/pull/1026

**Comment by samdoiron** [comment]
:wave: Hi all, this feature is currently merged into the next (currently untagged) version of Liquid. You can see the documentation [here](https://shopify.github.io/liquid/filters/where/). We hope to release a new version including it soon.

**Comment by samdoiron** [comment]
:wave: Hi all. We've just cut the [`4.0.2`](https://github.com/Shopify/liquid/commit/8013df8ca2e25b72260d945f0d6bfb1484a7d04c) branch of Liquid which includes the `where` filter. You can find documentation for it [here](https://shopify.github.io/liquid/filters/where/).

As I understand it, this should cover the use case you outlined. Closing for now assuming that's true. If there's something I've missed, feel free to re-open.

**Comment by bakura10** [comment]
Hi @samdoiron ,

I'm re-commenting this issue. As of today, it seems the where filter is limited to scalar. However it would be handy (especially with JSON metafields) to be able to do it on array as well:

```
{% assign elements = shop.metafields.namespace.key | where: 'categories', 'vegetables' %}
```

Would that be doable? :)

**Comment by mohamedhaddi** [comment]
@bakura10 Did you find any workaround to this?
