### ISSUE TITLE
Shopify Search Type

### ISSUE THREAD

**Issue by gina3five** [Shopify/liquid#464]
It would be handy to be able to get the search type on the search.liquid template. A use case for this would be so you could style different types of returned content differently. Something like this:

{% if search.type == 'product' %}
   style result as a product, include price and a "Buy Now" button or whatever
{%  elsif search.type == 'article' %}
   style result as a blog post
{% endif %}

I know you can hack together a way to achieve this by checking for things only a product or article would have (e.g. price for product and comment_post_url for article), but this would make the code for this much cleaner.

I asked Shopify Support about this and they said search.type was not available. I don't know if this a feature that's being considered, but I thought maybe posting here would get it some support (or not). If this is the wrong place to suggest this feature, I apologize.

**Comment by fw42** [comment]
Closing this issue since it's not about Liquid (but about Shopify)
