### ISSUE TITLE
Interactive Liquid REPL

### ISSUE THREAD

**Issue by parkr** [Shopify/liquid#467]
I have often considered such a thing. It can sometimes take tens of seconds to regenerate a full Jekyll site -- in my opinion, that's too long to wait to see if your new Liquid will work properly. Instead, there should be a way for me to do:

``` liquid
>> {% assign page.url = "/2014/welcome-to-jekyll.html" %}
>> {{ page.url | prepend:"/example" }}
# => "/example/2014/welcome-to-jekyll.html"
```

What do you think? Is this a worthwhile addition?

**Comment by gatopan** [comment]
Any status on this?

**Comment by parkr** [comment]
Nothing so far, nope! Have to find a way to persist context and to handle blocks in the REPL.

**Comment by arthurnn** [comment]
In any case, I am reopening this so someone can work on it.
