### ISSUE TITLE
Addition to strict mode: fail on nonexistent variable dereferencing

### ISSUE THREAD

**Issue by parkr** [Shopify/liquid#490]
In https://github.com/jekyll/jekyll/issues/3008, @gjtorikian wrote of one woe of using Liquid: it swallows references to non-existent variables.

It would be amazing, when `error_mode = :strict`, to throw an error in this case. It would really help Liquid scale out to larger teams, I think, and would help surface annoying rip-your-hair-out issues that Liquid allows for today.

What do you think?

**Comment by Carpetsmoker** [comment]
FYI all, I did some basic work on this, see the commit above. I need to go fix our templates first, but just so that you know it's in the works ;-)

**Comment by gjtorikian** [comment]
Great! Thank you!

**Comment by parkr** [comment]
> @pushrax what do you think?

:point_up:

**Comment by pushrax** [comment]
@Carpetsmoker I added a few comments to your commit, feel free to submit a PR after you take a look at them.

**Comment by gjtorikian** [comment]
Any updates here? :stuck_out_tongue_winking_eye:

**Comment by parkr** [comment]
It would be nice. Very nice.

**Comment by fw42** [comment]
@Carpetsmoker: Are you interested in addressing the comments and finishing this? If not, I can take a look myself.

**Comment by fw42** [comment]
@parkr: Is this something you would want to include in Jekyll 3? If yes, I will take a look soon (since I know you want to release soon). If it can wait, then I will focus on other things for now :-)

**Comment by parkr** [comment]
> Is this something you would want to include in Jekyll 3?

It would be marvelous! We're more lenient in Jekyll 3 with our Liquid version so if it is added to Liquid later, we could turn it on later as well (if it is not automatically enabled).

**Comment by Carpetsmoker** [comment]
@fw42 I did this for my previous job, which is my, well, no longer my job ;-) I don't mind finishing this as such, but at the moment I'm using my girlfriend's OSX machine, and I don't really want to mess around with Ruby and such (apparently you need homebrew and whatnot, and I've never really used OSX).

So yeah, I'll work on it, but not in the next week orso. Anyone else can of course also work on it if she or he has the inclination to do so ;-)

**Comment by mikebridge** [comment]
So is it correct to say that when this is on, an error will be generated when a missing member of a hash or drop is dereferenced?  i.e. both these would always return errors if "missing" is a missing hash key or drop value:

```liquid
    {{ x.missing }}
    {{ x.y.missing.z }}
```

And would a collection return an error only when it's either unset OR has an index but no elements, e.g. `{{ a[1] }}` when `a` is set but empty?
