### ISSUE TITLE
use a variable as a variable name within shopify

### ISSUE THREAD

**Issue by reggi** [Shopify/liquid#493]
> **Note**, this issue is specifically for Shopify's implementation of liquid on their website.

Can we please get a way to create variables with variable names :)

```
{% assign myVar = "hello" %}
{% assign [myVar] = "hello2" %}
{{ hello }} <!-- hello2 -->
```

or

```
{% assign myVar = "hello" %}
{% assign global[myVar] = "hello2" %}
{{ hello }} <!-- hello2 -->
```

or create objects :)
or append to existing objects :)

```
{% assign shop.hello = "win" %}
{{ shop.hello }}
```

and

```
{% assign shop["hello"] = "win" %}
{{ shop["hello"] }}
```

**Comment by fw42** [comment]
Creating variables with a variable name doesn't seem like a very common use case to me. Sorry.

**Comment by JoshHighland** [comment]
I'd love to have this feature also

**Comment by guiguij** [comment]
would also like this feature. 
It's really important for anyone wanting to customise shoppify. customisation is the only thing shopify is really lacking

**Comment by ButsAndCats** [comment]
Me too!

**Comment by redtide** [comment]
the first case could be useful to me as well.

**Comment by meniltiac** [comment]
This would be incredibly helpful for times when in any other code you'd create a function to output a string or array for a page. I have pages where I loop through collections and compare those collections to user metafields, and when we do it more than once on a page, I can't reuse variable names. If I could dynamically set variable names, I wouldn't have to have an entire snippet dedicated to reproducing the same code over and over again with just a few variable names changed.

**Comment by MischaDeNola** [comment]
Man that would really help here as well with a way we're handling variable terminology. Looping over a CSV to create variables for terms that contributers could easily access by just using the {{ termreference }} on their page.

**Comment by lizsterine** [comment]
I too would find this helpful.  I'm currently struggling with avoiding too many for loops on a custom collection template that dynamic creation of variables would make the page WAY more performant.
