### ISSUE TITLE
Filters With Exclamation Mark

### ISSUE THREAD

**Issue by carsonreinke** [Shopify/liquid#501]
It would be nice if Liquid supported filters that end with an exclamation mark.  The current support is a little odd though, as the strict parser allows it, but the lax does not.

Lax
```ruby
$ > template = ::Liquid::Template.parse(%q({{'yep' | test!}}))
 => #<Liquid::Template:0x007fc93a8c1ad0 ... @filters=[["test", []]]>]>, @warnings=nil> 
```

Strict
```ruby
$ > template = ::Liquid::Template.parse(%q({{'yep' | test!}}))
 => #<Liquid::Template:0x007fc93a8fbf78 ... @filters=[["test!", []]]>]>, @warnings=nil> 
```

I have been able to patch it for a long time, but not sure if other implications would be or if other non-alpha numeric characters would be desired.  I can put in a PR if desired.

**Comment by pushrax** [comment]
In Liquid 3 the strict parser no longer supports this for consistency with the lax parser. At some point we decided that filters (being idempotent) shouldn't have a use for `!` suffixes.

Feel free to reopen this issue if you disagree.
