### ISSUE TITLE
Duplicate keys in hash

### ISSUE THREAD

**Issue by alfredxing** [Shopify/liquid#502]
I recently upgraded to Ruby 2.2.0, and it started warning me about a duplicate key in Liquid. The duplicates in question are in [`tags/table_row.rb:45`](https://github.com/Shopify/liquid/blob/d9ae36ec406432adbd2828e31c79731ebafc357b/lib/liquid/tags/table_row.rb#L45) in `master` and [`htmltags.rb:46`](https://github.com/Shopify/liquid/blob/deeb813d533d91de1aa94cfd5a3028fc8cc6236f/lib/liquid/htmltags.rb#L46) for `2.6-stable`.

I'm not sure if this is intentional or not, but after removal the Rake tests still pass.

**Comment by parkr** [comment]
@arthurnn People are coming to us and posting bug reports when they have warnings turned on. Would you mind releasing a 2.6.2 and a 3.0.1 with these fixes? Thank you!
