### ISSUE TITLE
Proof read of high level documentation

### ISSUE THREAD

**Issue by siscia** [Shopify/liquid#510]
Hi everybody,

for a small side project I am exploring the codebase of Liquid and I am writing some high level documentation for it.

I guess it can be usefull to anybody who want to contribute to the project, however ruby is not strongest languange, and I can have miss something.

I was wonder if anybody would be so nice to read this first drafts and be sure I didn't write anything wrong.

You can find the article here: https://github.com/siscia/open-hire/blob/gh-pages/liquid-template.md
Or if you like to read with a nicer pagination here: http://siscia.github.io/open-hire/liquid-template.html

Thank you everybody :)

**Comment by arthurnn** [comment]
cc @Tetsuro @fw42

**Comment by parkr** [comment]
http://siscia.github.io/open-hire/liquid-template.html

**Comment by parkr** [comment]
@siscia Jekyll consumed a bunch of your examples :smile: Wrap your Liquid with `{% raw %} ... {% endraw %}` to guard against Jekyll's processing.

**Comment by siscia** [comment]
Hi @parkr , thanks, I did wrap some section that was having issues, I guess that is better to wrap everything, just in case...

Anyway I was more interesting in the technical side of the document, it is good enough ? It is right ? Does it explain ?

Thanks for your time, 

Cheers

**Comment by fw42** [comment]
Closing this since it's not really an issue about the Liquid codebase.
