### ISSUE TITLE
Problem with checking formatted date string

### ISSUE THREAD

**Issue by kylejm** [Shopify/liquid#511]
Hey all,

I'm using Jekyll and therefore Liquid as well.

I've been trying to make an ordinal day string (e.g. 1st, 3rd, 22nd) to put on my posts and have been fiddling around with it throughout parts of the day. I finally came to a solution but found some strange/unexpected behaviour along the way.

Here is the solution I came to to create an ordinal day:

```
{% capture day %} {{ page.date | date: "%-d" }} {% endcapture %}
{% capture dayMod %} {{ day | modulo: 10 }} {% endcapture %}
{% if dayMod contains "1" %}
    {% assign ordinal = "st" %}
{% elsif dayMod contains "2" %}
    {% assign ordinal = "nd" %}
{% elsif dayMod contains "3" %}
    {% assign ordinal = "rd" %}
{% else %}
    {% assign ordinal = "th" %}
{% endif %}
{% capture ordinalDay %} {{ day | append: ordinal }} {% endcapture %}
{% capture ordDayNoSpace %} {{ ordinalDay | remove: " " }} {% endcapture %}  //Without doing this there would be a space between the day and ordinal string

<span class="post-date"> {{ page.date | date: "%a" }} {{ ordDayNoSpace }} {{ page.date | date: " %b, %Y" } </span>
```

There are two bits of this that I found unexpected:

- I couldn't use a case statement (either {% when "n" %} or {% when n %} and I had to use "contains" not "==" in my if statements
- I had to remove a space from between the day and the appended ordinal string

Is this expected behaviour to you guys? Why wouldn't an "==" in the if statements work? Is it something to do with their being a space on the end of the day variable when it is captured from the date format output (I did string removing the/a space at this point but it wouldn't work)?

Thanks! 

Kyle

**Comment by parkr** [comment]
> I couldn't use a case statement (either {% when "n" %} or {% when n %} and I had to use "contains" not "==" in my if statements

Your `capture` includes spaces, so you'd have a string `" 2 "`, not `"2"`.

Change your top line to

```liquid
{% capture day %}{{ page.date | date: "%-d" }}{% endcapture %}
```

and try again!

**Comment by kylejm** [comment]
omg. What a n00b error. I didn't realise the capture would grab the spaces. But of course it does. DUH.

It's working! And the switch statement looks so much better 😊.

Thanks for the super quick response!

**Comment by parkr** [comment]
My pleasure! Glad you got it working :smile:

**Comment by kylejm** [comment]
One more thing about the spaces @parkr. I noticed that this:

```
{{ page.date | date: "%a" }}{{ ordinalDay }}{{ page.date | date: "%b, %Y" }}
```

outputs spaces between each curly brace (sorry if I'm not using the name of what those things actually are 😅). Am I missing something here too? I guess if you didn't want spaces there you'd have to append them together?

**Comment by fw42** [comment]
FYI there is a "strip" filter that removes leading and trailing whitespace

**Comment by parkr** [comment]
> FYI there is a "strip" filter that removes leading and trailing whitespace

Is that in Liquid 2.6? Jekyll uses 2.6 (and it looks like Kyle is using jekyll) :smile:

**Comment by fw42** [comment]
I thought you guys switched already.. how long does that take? ;-)

**Comment by parkr** [comment]
> I thought you guys switched already.. how long does that take? ;-)

Upgrading? Takes a little while... We're working on 3.0! https://github.com/jekyll/jekyll/issues/3324
