### ISSUE TITLE
Indentation of includes

### ISSUE THREAD

**Issue by fulldecent** [Shopify/liquid#514]
Following is a page with includes:

````
<!DOCTYPE html>
<html>

  {% include head.html %}

  <body>

    {% include header-and-hero.html %}

    <!-- Page content -->
    <div class="row">
        <div class="large-12 columns">
            {{ content }}
        </div>
    </div>

    {% include footer.html %}

  </body>

</html>

````

I would recommend that when `head.html` is included then every line of that file would be prepended with two spaces.

**Comment by pathawks** [comment]
There are many ways in which Liquid could better handle white-space (collapsing empty lines, etc.).

**Comment by parkr** [comment]
There's an issue for whitespace concerns.

**Comment by fw42** [comment]
Closing this. Already (kind of) being tracked by https://github.com/Shopify/liquid/issues/216.

**Comment by adrientetar** [comment]
@fw42 Not really, #216 was about stripping whitespace around tags, not identing includes or content instructions.

**Comment by adrientetar** [comment]
Seems #925 is a newer instance of this issue.
