### ISSUE TITLE
{% assign %} does not work as expected when appending values

### ISSUE THREAD

**Issue by sabhiram** [Shopify/liquid#515]
Here is some (maybe) strange behavior I noticed with the `assign` macro. The issue I am facing is that the rhs of the assign statement seems to only accept either a string or another variable (and not another expression). Is this expected? Are nested prints w/in an assign decomposed before the assignment?

Consider we had the following assignment statements in a template:
```html
{% assign foo = "foo" %}
{% assign bar = "bar" %}
{% assign baz = "baz" %}
```
Then `{{ foo | append:bar }}` produces `"foobar"` which is expected.

However: `{% assign x = {{ foo | append:bar }} %}{{ x }}` produces `"bar"` what happened to the `foo` variable here?

Similarly `{% assign x = bar + baz %}{{ x }}` also produces `"bar"` :)

I can work around this by doing something like this:
```html
{% capture temp %}{{ foo | append:bar }}{% endcapture %}
{% assign x = temp %}
{{ x }}
```
Which results in the expected `"foobar"`

**Comment by sabhiram** [comment]
I am not a ruby dude, but I am guessing we need something like this commit https://github.com/Shopify/liquid/commit/a1a128db19907b4403e948daef2f963844eb38cc applied to the assign tag.

**Comment by fw42** [comment]
> ```{% assign x = {{ foo | append:bar }} %}{{ x }}```

this is not valid Liquid syntax, you can't "nest" tags like this. pretty sure the strict mode parser will complain about this.

**Comment by sabhiram** [comment]
So then is the only way around this what I suggest with using the {% capture %} to append into a variable?

What about {% assign x = foo + bar %}?

Ill enable the strict parser (not sure if this is the case w/ github pages et al).

**Comment by fw42** [comment]
```{% assign x = foo | append: bar %}``` should work, unless I'm misunderstanding you

**Comment by sabhiram** [comment]
@fw42, thats the syntax I was looking for. Perfect, thanks for that :+1: 

Now that I have peered into some of the code backing the formatters and filters, this makes a lot more sense. It also makes sense why "foo + bar" does not work. I appreciate the help, and your time.
