### ISSUE TITLE
Should `#to_liquid` deep-convert to a Liquid representation?

### ISSUE THREAD

**Issue by parkr** [Shopify/liquid#516]
If you take an object which has a `#to_liquid`, should that method also call `#to_liquid` on all its subcomponents? In Jekyll, one could have a Collection, whose `#to_liquid` method exposes certain properties, one of which is `docs`. At the moment, `Collection#to_liquid` creates the hash, but doesn't run `#to_liquid` on the value of the `"docs"` key in the Hash it creates. Should it? Is `#to_liquid` meant to be deeply-applied? Why doesn't Liquid call this method on all items passed to it?

**Comment by pushrax** [comment]
I feel like `to_liquid` is supposed to be recursive... @fw42?

**Comment by parkr** [comment]
We build `Filters#as_liquid` so we could use this in filters. https://github.com/jekyll/jekyll/blob/ae584e43ed11467290ab40b8557c77c07db17feb/lib/jekyll/filters.rb#L324-L343

**Comment by fw42** [comment]
> If you take an object which has a #to_liquid, should that method also call #to_liquid on all its subcomponents?

Hmm. I think it should, yeah...

**Comment by fw42** [comment]
but that's not really Liquid's responsibility but the responsibility of the thing that implements it's own `#to_liquid` method, isn't it?

**Comment by pushrax** [comment]
@fw42 yes but we implement `to_liquid` for built in types (hash, array etc).

**Comment by parkr** [comment]
> but that's not really Liquid's responsibility but the responsibility of the thing that implements it's own #to_liquid method, isn't it?

Totally. I thought that when you access something in liquid, it implicitly calls `#to_liquid` then tries to dereference.
