### ISSUE TITLE
Allowing blacklisted Object methods as filter names

### ISSUE THREAD

**Issue by nickpearson** [Shopify/liquid#518]
I'm updating to Liquid 3 from an older version in one of my projects, and some of my filters (e.g., `to_json`) don't work. Simply changing the filter names (e.g., by adding a `2` to them, like `to_json2`) makes them work again.

From what I can tell, [this commit](https://github.com/Shopify/liquid/commit/38b4543bf184cb2fcae743528d6a9b39c20bbd32) from two years ago is where these filters would have stopped working, caused by the new method name blacklisting logic.

Because I'm using Liquid 3 in a Rails app, and because Rails' ActiveSupport extends `Object` with several methods (`to_json` among them), these added methods are not allowed to be used as Liquid filter names.

For example, this code works when ActiveSupport's core extensions are not loaded. (Note that for simplicity the `to_json` filter outputs a static JSON string regardless of the input.)

```ruby
require 'liquid'

# to_json is not defined on Object
Object.instance_methods & [:to_json] #=> []

module MyFilters; def to_json(obj); '{"sample":"output"}'; end; end
tmpl = Liquid::Template.parse("{{ obj | to_json }}")
puts tmpl.render({ "obj" => { 'a' => 'b' } }, filters: MyFilters)
#=> {"sample":"output"}
```

Here's the same code, but this time after ActiveSupport's core extensions are loaded.

```ruby
require 'active_support'
require 'active_support/core_ext'
require 'liquid'

# to_json is defined on Object now:
Object.instance_methods & [:to_json] #=> [:to_json]

module MyFilters; def to_json(obj); '{"sample":"output"}'; end; end
tmpl = Liquid::Template.parse("{{ obj | to_json }}")
puts tmpl.render({ "obj" => { 'a' => 'b' } }, filters: MyFilters)
#=> {"a"=>"b"}
```

In this second example, the custom `to_json` filter is not added to the `Liquid::Strainer` due to the `@@method_blacklist`, which is initialized with `Strainer.instance_methods`, which includes `to_json` when ActiveSupport's core extensions are loaded. As such, Liquid simply outputs the `{"a"=>"b"}` hash as a string rather than the `{"sample":"output"}` string we expected.

I was able to work around this with a *very* ugly hack in a Rails initializer:

```ruby
Liquid::Strainer.class_variable_set(:@@method_blacklist,
  Liquid::Strainer.class_variable_get(:@@method_blacklist) -
  CustomLiquidFilters.instance_methods.map(&:to_s))
```

This essentially allows all methods defined by a `CustomLiquidFilters` module to bypass the blacklist. (This does not include `Object` methods; in the context of the example code above, `MyFilters.ancestors #=> [MyFilters]`, and `MyFilters.instance_methods #=> [:to_json]`.)

Is there a better way to whitelist method names for custom filters? I realize I could rename the filter to just `json`, but there are other filters that are being blacklisted by default. Plus—and this is my main reason for opening this issue rather than just relying on a hack—custom filters that work today could be inadvertently blacklisted by future versions of Rails, ActiveSupport, or any other gem that adds methods to `Object`.

This was not easy to track down ("why does this filter work and the one *right next to it* not work?"), and it could be a source of frustration when new methods are added to `Object`, causing some filters to no longer be registered, when nothing about Liquid was changed. For instance, running `bundle update rails` and then having tests for custom filters fail even though those filters are (seemingly) in no way related to the Rails update (just like the example `to_json` filter above that simply returns a static string) would be confusing.

I tried making `Liquid::Strainer` inherit from `BasicObject` (added in Ruby 1.9.1), but this means it loses useful things like `respond_to?`. Before going deeper, I wanted to see if anyone on the Liquid team had any insight or opinion on this, and whether a "fix" would even be considered. Perhaps something as simple as defining `Liquid::Strainer#whitelist_filters(filter_names_or_module)` would do the trick.

**Comment by fw42** [comment]
Interesting. @dylanahsmith FYI.
