### ISSUE TITLE
Slice filter refuses to work on negative indices

### ISSUE THREAD

**Issue by tyteen4a03** [Shopify/liquid#522]
Given the following code:

```
<span class="test1">{{ "abcde" | slice: 0, -2 }}</span>
<span class="test2">{{ "abcde" | slice: -2, 0 }}</span>
<span class="test3">{{ "abcde" | slice: 1, -2 }}</span>
<span class="test4">{{ "abcde" | slice: -2, 1 }}</span>
<span class="test5">{{ "abcde" | slice: 0, 1 }}</span>
<span class="test6">{{ "abcde" }}</span>
```

Test1 to 3 will output nothing while test 4 to 6 will work as normal.

**Comment by fw42** [comment]
This is not a bug but the intended behaviour. The second argument to the slice filter is not an index but a length specifier.

**Comment by tyteen4a03** [comment]
I expected something like Python. This makes slicing to the end a hassle as you would have to define a new variable just to slice the string completely.

Please add Python-style slicing.

**Comment by fw42** [comment]
> I expected something like Python

most users of Liquid (a Ruby gem) expect something like Ruby :-) And this is exactly the behaviour of [Ruby's slice method](http://www.ruby-doc.org/core-2.2.0/String.html#method-i-slice).
