### ISSUE TITLE
Variable inside javascript won't load

### ISSUE THREAD

**Issue by paskal** [Shopify/liquid#524]
Good day!

We have an issue with variable in liquid template. [Here](https://github.com/kAworu/octostrap3/blob/ecfe5415d21a376d63c4141d643ba25d53439ac0/source/_includes/asides/github.html#L19) is the source:

    <script type="text/javascript">
        $(document).ready(function(){
            if (!window.jXHR){
                var jxhr = document.createElement('script');
                jxhr.type = 'text/javascript';
                jxhr.src = '{{ root_url}}/javascripts/libs/jXHR.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(jxhr, s);
                }
    
            github.showRepos({
                user: '{{site.github_user}}',
                count: {{site.github_repo_count}},
                skip_forks: {{site.github_skip_forks}},
                target: '#gh_repos'
                });
            });
    </script>
    <script src="{{ root_url }}/javascripts/github.js" type="text/javascript"> </script>

Our problem is what variable `{{ root_url }}` in code which won't unfold:

    jxhr.src = '{{ root_url}}/javascripts/libs/jXHR.js';
    # became:
    jxhr.src = '/javascripts/libs/jXHR.js';
    # also was tested with quotation marks instead of apostrophs, doesn't work
    # yes, also was tested with {{ root_url }}

    # but following code few lines down unfolds right:
    <script src="{{ root_url }}/javascripts/github.js" type="text/javascript"> </script>
    # became:
    <script src="/octostrap3/javascripts/github.js" type="text/javascript"> </script>

Issue disscussion located there: kAworu/octostrap3#45
For test I was using `liquid (2.6.1)`.

**Comment by fw42** [comment]
I guess this is with Jekyll? @parkr any ideas?

**Comment by paskal** [comment]
@parkr, could you please take a look?

**Comment by fw42** [comment]
@parkr?

**Comment by parkr** [comment]
Where is `root_url` specified?

**Comment by paskal** [comment]
$ head -1 ./source/_layouts/default.html
    {% capture root_url %}{{ site.root | strip_slash }}{% endcapture %}{% include head.html %}
    $ fgrep root ./_config.yml
    # If publishing to a subdirectory as in http://site.com/project set 'root: /project'
    root: /

**Comment by parkr** [comment]
@paskal Are all your includes in the default layout?

**Comment by kAworu** [comment]
@parkr how a scope problem would expand `root_url` on line 32 but not on line 19 of the same file ?

FYI the file is, but a few html classes, the same as the one in the "classic" octopress theme (https://github.com/imathis/octopress/blob/master/.themes/classic/source/_includes/asides/github.html). From my latest test the classic theme suffer of the same issue. The "capture" of `root_url` is also the same as in the classic theme.

**Comment by parkr** [comment]
@kAworu I can't see where `asides/github.html` is included in your site? https://github.com/kAworu/octostrap3/search?utf8=%E2%9C%93&q=github&type=Code

**Comment by kAworu** [comment]
@parkr  Again, it's based on the "classic" octopress theme, see for example https://github.com/kAworu/octostrap3/blob/master/source/index.html#L36 for the index page.

**Comment by kAworu** [comment]
Still, `root_url` get expanded without issue in other "aside" that are included the same way (like "recent posts", see https://github.com/kAworu/octostrap3/blob/master/source/_includes/asides/recent_posts.html#L8) and, as already pointed out, in the same file too.

**Comment by kAworu** [comment]
Any news on this issue ? I don't think it's a liquid bug, I've been able to have liquid (2.6.1) render the template correctly:

```
irb(main):001:0> require "liquid"
=> true
irb(main):002:0> tpl = Liquid::Template.parse(File.read('.themes/octostrap3/source/_includes/asides/github.html'))
=> #<Liquid::Template:0x00000002e4bf40 @resource_limits={}, @root=#<Liquid::Document:0x00000002e4b928 @nodelist=[#<Liquid::If:0x00000002e4b6f8 @blocks=[#<Condition site.github_user>], @nodelist=["\n<section class=\"panel panel-default clearfix\">\n  <div class=\"panel-heading\">\n      <h3 class=\"panel-title\">GitHub Repos</h3>\n  </div>\n  <div class=\"list-group\" id=\"gh_repos\">\n    <p class=\"loading\">Status updating...</p>\n  </div>\n  ", #<Liquid::If:0x00000002e4b270 @blocks=[#<Condition site.github_show_profile_link>], @nodelist=["\n    <div class=\"gh-profile-link pull-right text-muted\">\n      <a href=\"https://github.com/", #<Liquid::Variable:0x00000002e4ae60 @markup="site.github_user", @name="site.github_user", @filters=[]>, "\">@", #<Liquid::Variable:0x00000002e4a7f8 @markup="site.github_user", @name="site.github_user", @filters=[]>, "</a> on GitHub\n    </div>\n  "], @tag_name="if", @markup="site.github_show_profile_link ">, "\n  <script type=\"text/javascript\">\n    $(document).ready(function(){\n        if (!window.jXHR){\n            var jxhr = document.createElement('script');\n            jxhr.type = 'text/javascript';\n            jxhr.src = '", #<Liquid::Variable:0x00000002e4a410 @markup=" root_url", @name="root_url", @filters=[]>, "/javascripts/libs/jXHR.js';\n            var s = document.getElementsByTagName('script')[0];\n            s.parentNode.insertBefore(jxhr, s);\n        }\n\n        github.showRepos({\n            user: '", #<Liquid::Variable:0x00000002e4a140 @markup="site.github_user", @name="site.github_user", @filters=[]>, "',\n            count: ", #<Liquid::Variable:0x00000002e49f10 @markup="site.github_repo_count", @name="site.github_repo_count", @filters=[]>, ",\n            skip_forks: ", #<Liquid::Variable:0x00000002e49c90 @markup="site.github_skip_forks", @name="site.github_skip_forks", @filters=[]>, ",\n            target: '#gh_repos'\n        });\n    });\n  </script>\n  <script src=\"", #<Liquid::Variable:0x00000002e499e8 @markup=" root_url ", @name="root_url", @filters=[]>, "/javascripts/github.js\" type=\"text/javascript\"> </script>\n</section>\n"], @tag_name="if", @markup="site.github_user ">, "\n"]>>
irb(main):003:0> puts tpl.render('site' => { 'github_user' => 'kAworu'}, 'root_url' => '[ROOT]')

<section class="panel panel-default clearfix">
  <div class="panel-heading">
      <h3 class="panel-title">GitHub Repos</h3>
  </div>
  <div class="list-group" id="gh_repos">
    <p class="loading">Status updating...</p>
  </div>
  
  <script type="text/javascript">
    $(document).ready(function(){
        if (!window.jXHR){
            var jxhr = document.createElement('script');
            jxhr.type = 'text/javascript';
            jxhr.src = '[ROOT]/javascripts/libs/jXHR.js';
            var s = document.getElementsByTagName('script')[0];
            s.parentNode.insertBefore(jxhr, s);
        }

        github.showRepos({
            user: 'kAworu',
            count: ,
            skip_forks: ,
            target: '#gh_repos'
        });
    });
  </script>
  <script src="[ROOT]/javascripts/github.js" type="text/javascript"> </script>
</section>

=> nil
irb(main):004:0> Liquid::VERSION
=> "2.6.1"
```

**Comment by fw42** [comment]
If this is not a Liquid bug, can we close this issue?

**Comment by kAworu** [comment]
@fw42 yes feel free to close it, the octopress folk should get their hands on it if they're willing to fix it @parkr
