### ISSUE TITLE
Liquid's boolean logic does not support not, so is not functionally complete

### ISSUE THREAD

**Issue by Blaisorblade** [Shopify/liquid#526]
Liquid should support `not` — not only because it is the obvious thing to do, but also because it is required to write arbitrary boolean conditions. `unless` is not sufficient for nested negations --- @nickpearson shows how to compile `not` by hand in [this comment](https://github.com/Shopify/liquid/issues/138#issuecomment-8529289), and the amount of extra needed code is significant.

Moreover, [the documentation claims](http://docs.shopify.com/themes/liquid-documentation/basics/operators):

> Liquid has access to all of the logical and comparison operators. 

but because of the absence of not, that's not true.

(I know that there is https://github.com/Shopify/liquid/issues/138, but it was closed without sufficient discussion).

**Comment by fw42** [comment]
I agree that it would be nice to have (same way having support for parentheses would be nice to have). Unfortunately it's not on our roadmap at the moment. But feel free to submit a PR and we will check it out.

**Comment by fw42** [comment]
I'm reopening the other one
