### ISSUE TITLE
Status of the changelog

### ISSUE THREAD

**Issue by pushrax** [Shopify/liquid#527]
It seems that we have stopped really updating the changelog. Is this by design, or should we make sure to keep updating it in the future?

(https://github.com/Shopify/liquid/blob/master/History.md for reference)

**Comment by fw42** [comment]
yeah I don't know, it's hard to remember :-) We should have some guidelines on what kind of things should be in there and what shouldn't...

**Comment by parkr** [comment]
I created a tool, https://byparker.com/go/merge-pr, which is a command line tool for streamlining this process. It merges a given PR on GitHub, opens up your editor with the changelog file so you can add a line. Then, it commits that changelog change. We use it extensively in Jekyll.

**Comment by arthurnn** [comment]
>  Is this by design
No, I try to keep the History up-to-date. We all should do the same.
