### ISSUE TITLE
else tag is required in if or case blocks

### ISSUE THREAD

**Issue by boobooninja** [Shopify/liquid#528]
This is probably an issue with the language syntax itself and not the ruby gem but I just found out the hard way that an "if" "elseif" "else" "endif" block MUST have the "else" or it will blow up. Same issue for "case" "when" "else" "endcase".

If you just have "if" "elseif" "endif" then it will display an error saying:
Liquid syntax error: Unknown tag 'endif'

This doesn't follow ruby syntax where "else" is optional.

**Comment by pushrax** [comment]
The language definitely doesn't have this rule, can you post an example where you're running into this?

```rb
irb(main):001:0> require 'liquid'
=> true
irb(main):002:0> Liquid::Template.parse("{% if true %}foo{% endif %}").render
=> "foo"
```

**Comment by parkr** [comment]
@pushrax Try adding an elseif instead of an else.

**Comment by boobooninja** [comment]
Solved this issue.
Your example doesn't represent my problem however, it is not a problem. The error I was receiving was not helpful however.
The following cases are valid:
Liquid::Template.parse("{% if true %}foo{% endif %}").render
Liquid::Template.parse("{% if true %}foo{% elsif false %}bar{% endif %}").render
Liquid::Template.parse("{% if true %}foo{% elsif false %}bar{% else %}foo bar{% endif %}").render

If you however have a tag that is not closed properly the error you receive may point you in the wrong direction.
{% case something %}{% when true }foo{% else %}bar{% endcase %}

notice the missing %

Sorry for the trouble. :)
