### ISSUE TITLE
Add case-insensitive sort

### ISSUE THREAD

**Issue by tkrotoff** [Shopify/liquid#529]
Currently ["the order of the sorted array is case-sensitive"](http://docs.shopify.com/themes/liquid-documentation/filters/array-filters#sort). It would be useful to also have a case-insensitive sort.

Use case I'm aiming: listing categories or tags on a Jekyll site in the proper order. Example without proper order: http://blog.lanyonm.org/tags.html
To get around this lack, some downcase all tags: http://www.jokecamp.com/tag/ http://www.jokecamp.com/blog/listing-jekyll-posts-by-tag/

**Comment by arthanzel** [comment]
Is the addition of a case-insensitive sort filter something that Shopify would approve in a PR? We already seem to have a few solutions:

- `some_list | sort: 'downcase'`for strings (jekyll/jekyll#2135)
- `some_list | map: 'title' | sort: 'downcase'` for hashes and objects (jekyll/jekyll#2135)

Both of these don't retain capitalization, aren't the most user-friendly for non-Rubyists.

`sort`'s case-sensitive behaviour is now [documented] (https://docs.shopify.com/themes/liquid-documentation/filters/array-filters#sort).

I have a fork that adds a case-insensitive sort, but if this is something that won't be merged then this issue and #404 should be closed. There's also jekyll/jekyll-help#255 and jekyll/jekyll#2135 that remain open and need a more definitive resolution.

 @boourns, @fw42 thoughts?

**Comment by pushrax** [comment]
I don't think there's a good reason to not have this, feel free to send in a PR.

**Comment by arthanzel** [comment]
PR #554

**Comment by daslicht** [comment]
Is there any solution for this ?

Lets say I have this:
```
 {% assign _linklists = linklists[child_list_handle].links | sort: 'title' %}
```
how to sort this not case sensitive , just in alphabetic order ?
