### ISSUE TITLE
Keyword arguments for tags

### ISSUE THREAD

**Issue by Dorian** [Shopify/liquid#530]
eg: `{% information_dot x:1 y:2 %}`, `{% bubble src:"bubble.png" %}`, etc...

Doesn't seem to work:

```ruby
class LiquidTags::InformationDot < Liquid::Tag
  def initialize(_tag_name, x:, y:)
    super
    @x = x
    @y = y
  end
  
  def render(_context)
     "1. #{@x}, 2. #{@y}, 3. ???, 4. Profit!"
  end
end

Liquid::Template.register_tag('information_dot', LiquidTags::InformationDot)

Liquid::Template.parse(" {% information_dot x:1 y:2 }) %}")
# => ArgumentError: missing keywords: x, y
# lib/liquid/tag.rb:9 in 'new'
```

Any thoughts? Should I implement it or is it already there but I can't see it for some reason?

Pretty much like for filters: https://github.com/Shopify/liquid/pull/175

**Comment by Dorian** [comment]
Same doesn't seem to work as an options hash: eg: `def initialize(_tag_name, options = {})`

**Comment by Dorian** [comment]
Ok, I see it's done manually for `cycle` for instance, based on some regexp, I'm kind of surprised by that: https://github.com/Shopify/liquid/blob/master/lib/liquid/tags/cycle.rb#L48 but I guess that's what I will do too.

**Comment by Dorian** [comment]
eg, my current solution:

```ruby
  def initialize(tag_name, markup, _options)
    super
    @tag_name = tag_name
    @x = markup.scan(/ x: ?"([^"]+)"/).flatten.first
    @y = markup.scan(/ y: ?"([^"]+)"/).flatten.first
  end
```

**Comment by pushrax** [comment]
Related discussion in #560. The current status quo sucks, it would be nice if you didn't have to do this.

**Comment by fw42** [comment]
Closing in favour of https://github.com/Shopify/liquid/issues/560
