### ISSUE TITLE
Use variable as variable name

### ISSUE THREAD

**Issue by Chopsueyer** [Shopify/liquid#531]
Hi,

Is there any way to use a variable as a variable name or object attribut? 
An example:

```

{% for product in collection.products %}

    {{ settings.product[forloop.index] }}

{% endfor %}

```

I tried to capture it, but even if the concatenation is already done, I can't find any way for using this variable as an attribut name or else.

Thanks for the help

**Comment by pushrax** [comment]
The syntax in your example should work, what is the output you're seeing?

**Comment by Chopsueyer** [comment]
Nothing... settings.product[forloop.index] seems to not transform into settings.product1, settings.product2, settings.product3 and being considered as a variable (or as an attribut name in this case)

**Comment by carsonreinke** [comment]
I think you are looking for something like this:

{% assign key = forloop.index | prepend:'product' %}
{{ settings[key] }}

**Comment by Chopsueyer** [comment]
Thanks a lot, it's working this way!

We should probably have this somewhere on the documentation, without your help I would probably never have found it!

Thanks again ;)

**Comment by pushrax** [comment]
For completeness, the syntax you originally used means `settings.product.1` if the index is 1.
