### ISSUE TITLE
Boolean algebra is really weird in Liquid

### ISSUE THREAD

**Issue by marten** [Shopify/liquid#534]
Example:

```ruby
Liquid::Template.parse("{% if false and false or true %} foo {% endif %}").render
# => ""

false and false or true
# => true
```

As best I can gather, Liquid simply reduces left-to-right, finds a `false and X` and short-circuits to `false`? I'm more than happy to work on a pull request to fix this, but I don't think you can do it backwards-compatibly, so I want to check if it would be merged.

If not, maybe this behaviour should have a big bold warning sign somewhere.

Note that you also can't fix this by adding parens:

```ruby
Liquid::Template.parse("{% if (false) or (true) %} foo {% endif %}").render
# => ""
Liquid::Template.parse("{% if false or true %} foo {% endif %}").render
# => " foo "
```

**Comment by pushrax** [comment]
More discussion in #138.

**Comment by fw42** [comment]
Closing this, since we have https://github.com/Shopify/liquid/issues/138 to track this.
