### ISSUE TITLE
Parantheses break if evaluation

### ISSUE THREAD

**Issue by mariusa** [Shopify/liquid#536]
On Shopify, this should show "liquid works", but results in "nope":

```
TEST
{% if 1==1 and (5 > 1) %}
liquid works
{% else %}
nope
{% endif %}
```

Change to 
```if 1==1 and 5 > 1 ```
and it works.

**Comment by fw42** [comment]
Liquid doesn't support parentheses (and if Shopify's documentation says that it does, then that's a bug. please let us know if that's the case.)
