### ISSUE TITLE
Slice documentation incorrect on Shopify

### ISSUE THREAD

**Issue by mikebridge** [Shopify/liquid#542]
I think the [example on Shopify](https://docs.shopify.com/themes/liquid-documentation/filters/string-filters#slice) for negative start indices is incorrect:

```liquid
    {{ "hello" | slice: -3, 2  }}  --> "el"
```

It should render 'll', since it's modelled after [ruby](http://ruby-doc.org/core-2.2.0/Array.html)
   
The documentation on [Liquid For Designers](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers) looks correct, though.

**Comment by fw42** [comment]
Yeah you are right. The docs are wrong here. @tkirrane can you take a look?

**Comment by tkirrane** [comment]
Will do

**Comment by fw42** [comment]
@tkirrane can this issue be closed?

**Comment by fw42** [comment]
@tkirrane: did anyone fix this yet?

**Comment by mikebridge** [comment]
This is still outstanding.

**Comment by tkirrane** [comment]
Sorry folks, raising a ticket now.

**Comment by admhlt** [comment]
Thanks, Mike. I've fixed this in our docs and it will soon be visible on the live site.

**Comment by mikebridge** [comment]
@admhlt NP - I went through most of the documentation and the rest was pretty accurate.
