### ISSUE TITLE
Split documentation uses undocumented array features "first" and "last"

### ISSUE THREAD

**Issue by mikebridge** [Shopify/liquid#543]
In the [Shopify documentation for split](https://docs.shopify.com/themes/liquid-documentation/filters/string-filters#split) the example dereferences an array element using `.first` and `.last`.  This seems to work, but I don't see it documented anywhere.  

I would assume it should be [here](https://docs.shopify.com/themes/liquid-documentation/basics/types) or [here](https://github.com/Shopify/liquid/wiki/Liquid-for-Designers)

**Comment by fw42** [comment]
@tkirrane: can someone update the docs?

**Comment by fw42** [comment]
@admhlt: Has this been addressed? If not, would you mind taking a look?

**Comment by admhlt** [comment]
I can take care of this -- I'd say the best option is to move explanation of `.first` and `.last` into the main text rather than hiding it in an example. I think it should stay on the string filters page though.

**Comment by admhlt** [comment]
Thanks for reporting this, @mikebridge. `.first` and `.last` can be used on most arrays and shouldn't have been hidden in that example. I've added a link from that section to the [array filters](https://docs.shopify.com/themes/liquid-documentation/filters/array-filters) page where those methods are explained.

Changes should be live in the next day or so.

**Comment by fw42** [comment]
Thanks Adam
