### ISSUE TITLE
Liquid::Variable.name is returning a Liquid::VariableLookup in version 3.0.0 and above

### ISSUE THREAD

**Issue by willlahr** [Shopify/liquid#547]
This code snippet behaves differently between 2.6.2 and versions 3.0.0 and above:

    puts Liquid::Template.parse("{{test_var}}").root.nodelist[0].name 

In 2.6.2 it prints out the variable name, which is what I was expecting:
    test_var 

In 3.0.0 and 3.0.1 it prints out the following:
    #<Liquid::VariableLookup:0x007f9f0419e830>

Is this a bug?  Or have I misunderstood the API?

**Comment by pushrax** [comment]
Expression parsing (i.e. determining what to do with `test_var`) used to happen in the rendering step, now it happens in the parsing step. There is no bug, just a breaking change in the API.

**Comment by willlahr** [comment]
Thanks for responding.  This change is creating a problem for me because I was using a list of variables to trigger re-rendering of templates,  I've explained it  a bit more here:  
http://stackoverflow.com/questions/29696259/how-to-get-list-of-variables-referenced-in-a-liquid-template
Is there a way to do this with >3.0.0?   VariableLookup doesn't seem to have any methods to get the variable name, even though it is being held in the object.

**Comment by pushrax** [comment]
There isn't a correct way as we hadn't considered that use-case, but I think it would be reasonable to expose the name/lookups/command flags as read-only methods.

@Shopify/liquid what do you think?

**Comment by fw42** [comment]
I'm ok with exposing this information :+1:

**Comment by willlahr** [comment]
What's the timescale for this merge going into a release on RubyGems?  I'm wondering if to pull from github for production or just wait until rubygems.org has been updated.

**Comment by fw42** [comment]
Just released [v3.0.2](https://github.com/Shopify/liquid/releases/tag/v3.0.2) to [Rubygems](https://rubygems.org/gems/liquid/versions/3.0.2) (see https://github.com/Shopify/liquid/pull/553).
