### ISSUE TITLE
Given a LiquidException on render, how do we correlate with input template?

### ISSUE THREAD

**Issue by frkline** [Shopify/liquid#548]
When a runtime problem occurs while performing a "render" on a parsed template, resulting in a thrown LiquidException, how do we determine where in the original template script the evaluation issue occurred? The ruby error seems to correlate with the location in the parsed template, rather than the original script.

When evaluating a large script, upon an unexpected exception, this is a decent headache given the trial-and-error process of removing the script's contents and adding it back piece-by-piece until the error is encountered.

**Comment by fw42** [comment]
There is currently no way to get something like line numbers on the template to see where exactly an error occured :-( this is very high on our wish list too.

**Comment by pushrax** [comment]
This is definitely possible to implement, I may look into doing so soon.

**Comment by fw42** [comment]
@pushrax @dylanahsmith is one of you guys already looking at implementing this?

**Comment by dylanahsmith** [comment]
I think https://github.com/Shopify/liquid/pull/574 fixed this
