### ISSUE TITLE
New test failure - no changed code

### ISSUE THREAD

**Issue by pushrax** [Shopify/liquid#549]
Previous master build: https://travis-ci.org/Shopify/liquid/builds/56905131

A current run with no changed code: https://travis-ci.org/Shopify/liquid/builds/59182747

Presumably a dependency changed that broke that test. The Ruby patchlevel is the same across the two builds. Happens on my laptop and in my dev VM.

**Comment by arthurnn** [comment]
the main dependency difference I can spot is minitest.. which was 5.5.1 and on the broken one is 5.6.0

**Comment by pushrax** [comment]
Tested again with 5.5.1 and it does indeed work, will look into the changes.

**Comment by pushrax** [comment]
ok... in the diff between minitest 5.6.0 and master it starts working again (specifically https://github.com/seattlerb/minitest/commit/00268427a258d7565c57c0a4b625e459bc59e80b).

So, I guess we wait for a release.
