### ISSUE TITLE
document on rubydoc.info, have some issue

### ISSUE THREAD

**Issue by zhso** [Shopify/liquid#552]
http://www.rubydoc.info/gems/liquid/Liquid/Unless
in the "Overview" Part
The Sample Code is this:
`{% unless x < 0 %} x is greater than zero {% end %}`
real code is:
`{% unless x < 0 %} x is greater than zero {% endunless %}`

**Comment by fw42** [comment]
Hmm this was already fixed in https://github.com/Shopify/liquid/pull/489. Not sure why Rubydoc hasn't picked it up yet.

**Comment by pushrax** [comment]
Rubydoc is using Liquid 3.0.1 - the latest stable.
