### ISSUE TITLE
Strict parser builds conditionals in the opposite order

### ISSUE THREAD

**Issue by pushrax** [Shopify/liquid#569]
```ruby
Liquid::Template.parse("{% if true or true and false %} TRUE {% else %} FALSE {% endif %}").render
=> " TRUE "
Liquid::Template.parse("{% if true or true and false %} TRUE {% else %} FALSE {% endif %}", error_mode: :strict).render
=> " FALSE "
```

conversely,

```ruby
Liquid::Template.parse("{% if false and false or true %} TRUE {% else %} FALSE {% endif %}").render
=> " FALSE "
Liquid::Template.parse("{% if false and false or true %} TRUE {% else %} FALSE {% endif %}", error_mode: :strict).render
=> " TRUE "
```

This is because the lax parser [pulls tokens off the end of the list](https://github.com/Shopify/liquid/blob/3372ca8136a13af28c80b1cbe4e11be82ffbed5e/lib/liquid/tags/if.rb#L71).

I noticed this while testing out the formatter – if the AST was parsed with the strict parser it would spit out the conditions backwards.

Since `and` doesn't have precedence in Liquid, there is no obvious answer to which one is correct. Note: in general both `and` and `or` are commutative when alone, so giving one precedence over the other (as commonly done in programming languages) makes the whole expression commutative, which is why usually this ambiguity is never seen.

@Shopify/liquid @trishume

**Comment by pushrax** [comment]
From my testing of Shopify templates before, I'm fairly sure I never saw this pop up. So that means this actually won't be an issue in Shopify. Still :poop: though. This is what the ASTs look like:

```liquid
{% if a or b and c %} TRUE {% else %} FALSE {% endif %}
```

```diff
diff --git 1/lax 2/strict
index 8faa575..40be43d 100644
--- 1/lax
+++ 2/strict
@@ -4,7 +4,7 @@ markup:
 options: &1
   :locale: !ruby/object:Liquid::I18n
     path: "/Users/jli/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/liquid-3.0.2/lib/liquid/locales/en.yml"
-  :error_mode: :lax
+  :error_mode: :strict
 blank:
 nodelist:
 - !ruby/object:Liquid::If
@@ -13,17 +13,17 @@ nodelist:
   options: *1
   blocks:
   - !ruby/object:Liquid::Condition
-    left: a
+    left: c
     operator:
     right:
-    child_relation: :or
+    child_relation: :and
     child_condition: !ruby/object:Liquid::Condition
       left: b
       operator:
       right:
-      child_relation: :and
+      child_relation: :or
       child_condition: !ruby/object:Liquid::Condition
-        left: c
+        left: a
         operator:
         right:
         child_relation:
```

**Comment by pushrax** [comment]
One option is to diverge the strict/lax syntax and finally add operator precedence (including parentheses), full expressions, etc, and have the upgrade path be to use the formatter. Not sure if we're ready for that yet or not.

**Comment by trishume** [comment]
:crying_cat_face:

If it doesn't affect any existing templates then we could just change the behaviour of the lax parser to be the same as the strict parser (which is more correct IMO by math rules for evaluating things with the same precedence). Then later we could add a simple precedence model where everything is the same preference (for compatibility) but brackets actually matter.
