### ISSUE TITLE
blank check not working

### ISSUE THREAD

**Issue by basex** [Shopify/liquid#589]
I'm using liquid 3.0.3.

Was blank removed from liquid?

```ruby
> require 'liquid'
> Liquid::Template.parse('{% if test == blank %}yes{%else%}no{% endif %}').render 'test' => nil
=> "no" 
> Liquid::Template.parse('{% if test == blank %}yes{%else%}no{% endif %}').render 'test' => ''
=> "no"
> Liquid::Template.parse('{% if test  == blank %}yes{%else%}no{% endif %}').render 'test' => ' '
 => "no" 
> Liquid::Template.parse('{% if test == blank %}yes{%else%}no{% endif %}').render 'test' => 123
=> "no"
```

Another blank example: https://docs.shopify.com/themes/liquid-documentation/basics/true-and-false

**Comment by fw42** [comment]
This might be https://github.com/Shopify/liquid/issues/224

**Comment by basex** [comment]
I tried adding active_support before liquid and got the same result.

**Comment by fw42** [comment]
Hm try `require 'active_support/all'` or `require 'active_support/core_ext/object/blank'`, both of those work for me.

**Comment by basex** [comment]
Thanks :thumbsup:

**Comment by fw42** [comment]
Closing this issue since this bug is already being tracked via #224.
