### ISSUE TITLE
Using "blank" as a variable name

### ISSUE THREAD

**Issue by fw42** [Shopify/liquid#591]
Weird things happen. Saw something like this in production:
```
{% assign blank = "" %}
...
{% assign something = blank %}
...
{{ something }}
```

which renders `"Liquid error: undefined method 'to_liquid' for :blank?:Symbol"`, which is kinda shitty.

Should have some better behaviour.

**Comment by nickpearson** [comment]
I've always thought the `== blank` check was strange, since it's not really testing for equality.

If going forward Liquid allows `blank` to be used as a variable name, how about adding `is` as an alternative to `==` for special checks like `blank` and `empty`? `{% if something is blank %}`

**Comment by pushrax** [comment]
`blank` is a keyword in liquid, like `true`, and is parsed in the exact same way. I don't think it should be assignable. There are two issues here, the first (outputting `blank`) is fixed by #592, the second (assigning to `blank`) should work in the same way as assigning to `true`.

**Comment by pushrax** [comment]
If people agree with my thoughts on the treatment of assigning to `blank` then we can close this, since it's what the current behaviour is.

**Comment by fw42** [comment]
I think the current behaviour (you can't assign to a variable named "blank") seems fine to me.

**Comment by fw42** [comment]
Arguably we should error and not be silent...

**Comment by fw42** [comment]
I think we can close this issue for now since I wouldn't consider this a "bug" at this point. Please reopen if you disagree.

**Comment by pushrax** [comment]
Yeah, in the same way that we should error if you assign to `true` or `14` (but we don't).
