### ISSUE TITLE
form.posted_successfully? doesn't work for address forms

### ISSUE THREAD

**Issue by admanami** [Shopify/liquid#597]
According to the liquid docs:
https://docs.shopify.com/themes/liquid-documentation/objects/form#form-posted_successfully

form.posted_successfully? should work within the {% form %} tag.

However this does not work:

{% form 'customer_address', address %}

{% if form.posted_successfully? %}
Success
{% else %}
{{ form.errors | default_errors }}
{% endif %}

{% endform %}

—————— And nor does this: ——————

{% form 'customer_address', address %}

{% if form.posted_successfully? %}
Success
{% else %}
{{ form.errors | default_errors }}
{% endif %}

{% endform %}

--------------------

Neither the add, edit or delete functions seem to be able to return a success/failure which can be output on the front end.

**Comment by fw42** [comment]
Thanks for reporting this issue, it's actually a known bug that is already being tracked in our Shopify bug tracker. I will close this issue since this is not a Liquid bug (but a Shopify bug).

**Comment by admanami** [comment]
Ah - ok, thanks for letting me know. Can you provide a link to the bug so I can follow and be advised when fixed?

**Comment by carolineschnapp** [comment]
The Shopify project is not public so we are not able to share such link with you, but we have added a note to our documentation now — you will see that note published some time tomorrow here: https://docs.shopify.com/themes/liquid-documentation/objects/form#form-posted_successfully for the next deployment of our docs.

**Comment by admanami** [comment]
Ah, ok, thank you for letting me know and publishing the note. Much appreciated.
