### ISSUE TITLE
Escaping Liquid Tags

### ISSUE THREAD

**Issue by benubois** [Shopify/liquid#6]
Is there a way to escape a liquid tag so it can be printed rather than parsed?

**Comment by nasht00** [comment]
Is this documented anywhere?

**Comment by nasht00** [comment]
I have a Jekyll 3 site, and I want to use `jsrender` as well.

I want to print:

```
<script id="myTemplate" type="text/x-jsrender">
Name: {{:name}}
</script>
```

What's the correct way?
I tried `{{{{:name}}}}`, `{{ "{{:name}}" }}`, nothing works...

**Comment by nasht00** [comment]
I found the doc: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#raw
