### ISSUE TITLE
Ability to access more Shopify shop data

### ISSUE THREAD

**Issue by zoerooney** [Shopify/liquid#606]
There are already a handful of things you can access via the shop object, but there are way more available via the API that aren't available via Liquid:

Shop object (Liquid): https://docs.shopify.com/themes/liquid-documentation/objects/shop
Shop object (API): https://docs.shopify.com/api/shop

It would be lovely if these objects were more equal. For my specific use case, I want to be able to access the shop address details so that I can include them as meta properties for SEO purposes, but generally speaking it seems like they'd be useful to access via Liquid for other theme/ display purposes. Things like address, latitude, longitude, zip, city, state, country, phone.

**Comment by fw42** [comment]
@zoerooney: This isn't really the place for requests like this. This repository is about Liquid itself, not about how Shopify uses Liquid. Liquid itself doesn't know anything about shops.

Unfortunately it's not easy to change the API response or the Liquid Shop object in Shopify since that would break backwards compatibility with existing apps and themes.

**Comment by zoerooney** [comment]
Hmm I was basing posting it here on this useful Shopify-specific conversation: https://github.com/Shopify/liquid/issues/438#issuecomment-108989466

I'm not suggesting changing the API and my suggestion is not going to have issues with backwards compatibility. All I'm suggesting is that the liquid object gain more features that are already in the API object.

**Comment by fw42** [comment]
I see. We opened an internal shopify issue to discuss this.

**Comment by quelledanielle** [comment]
Will do! :smile:

**Comment by quelledanielle** [comment]
Hi @zoerooney! I've just added the `shop.address` object to liquid. The fields `street`, `address1`, `city`, `zip`, `province`, `country`, and `summary` are accessible like `shop.address.street`.

**Comment by zoerooney** [comment]
Awesome, thanks @quelledanielle !
