### ISSUE TITLE
undefined.empty? is not true or false

### ISSUE THREAD

**Issue by mikebridge** [Shopify/liquid#609]
I don't understand why [this test](https://github.com/Shopify/liquid/blob/master/test/integration/tags/standard_tag_test.rb#L157) is not returning "false":

```
    assert_template_result('else',
      '{% case a.empty? %}{% when true %}true{% when false %}false{% else %}else{% endcase %}',
      {})
```

The test is asserting that it's neither true nor false.  Shouldn't this eval to `false` since nil != empty....?

**Comment by pushrax** [comment]
`a` is not defined, so its value is `nil`. `nil` does not have an `empty?` method, so the result of the whole keypath is `nil`, which doesn't match any of the cases so the `else` is hit.

**Comment by mikebridge** [comment]
@pushrax Ah, so you're saying that the `case` statement does not actually compare based on [truthiness](https://docs.shopify.com/themes/liquid-documentation/basics/true-and-false), correct?  I see that the following does not use truthiness as a basis for comparison either:

```
    {% case nil %}{% when false %}FALSE{% when true %}TRUE{%else%}NOT TRUE OR FALSE{% endcase %}
    --> NOT TRUE OR FALSE

    {% case 0 %}{% when true %}TRUE{% when false %}FALSE{%else%}NOT TRUE OR FALSE{% endcase %}
    --> NOT TRUE OR FALSE
```

Without knowing that, I would have expected those to return "FALSE" and "TRUE", respectively....

**Comment by pushrax** [comment]
It works similarly to ruby, using equality rather than truthiness (in ruby `nil != false`).

**Comment by mikebridge** [comment]
Ok, thanks for the clarification!
