### ISSUE TITLE
Implicit custom filter?

### ISSUE THREAD

**Issue by PositiveAlex** [Shopify/liquid#619]
Hey thank you for your awesome gem.

Please, tell me, can I create somehow my own background processing of {{  }} vairables ? 

For instance, if i have {{ var }} and passing var = "" to the render function, I want it to be rendered as null 

I can create my own filter and write {{ var | nullable }} everywhere but I'm actually feel lazy about it.

So the question is: can I say that if var is "" then print out "null" without changing templates at all?

**Comment by fw42** [comment]
I believe this is being addressed in https://github.com/Shopify/liquid/pull/610.

**Comment by PositiveAlex** [comment]
@fw42 wow, it's been developed so fast that it happened before I've asked about it :+1:

**Comment by parkr** [comment]
Can be closed.

**Comment by PositiveAlex** [comment]
Ya sure, and what is release date with global filters?

ср, 23 сент. 2015, 7:13, Parker Moore <notifications@github.com>:
