### ISSUE TITLE
Is there a filter that let's you convert a number to a string?

### ISSUE THREAD

**Issue by d3netxer** [Shopify/liquid#622]

**Comment by pushrax** [comment]
Most filters call `to_s` on their input, so most of the time you can just use them directly. What case are you thinking of that isn't covered?

If you really need a string for some reason, you could use the `append` or `prepend` filters (similarly to how `"" + 3 === "3"` in JS).

**Comment by d3netxer** [comment]
I basically want this tag to work:

{{ site.tags[this_word].size }}

I have tags in my YAML front matter. The tags can be year dates like 2014; but I want it to work if the user puts in 2014 or '2014' as a string. The size filter only returns the correct result if the input type is correct.

Maybe there is a liquid tag that can tell you if a variable is a number or a string?

**Comment by fw42** [comment]
you can use the capture tag for this
