### ISSUE TITLE
Hi Guys I need help Form If/Else Statements

### ISSUE THREAD

**Issue by Shadroi** [Shopify/liquid#629]
What i want to do is to create a form with radio buttons that has a condition that for example

<input type="radio" id="download" name="guide" >
<input type="radio" id="download" name="guide" >

{% if radio1.selected %}
      show input1;
{% if radio2.selected %}
      show input2;

How can I make it work? I've been trying to figure this out since yesterday. Thanks guys! :)

**Comment by fw42** [comment]
This seems like something you should do with JavaScript. Liquid itself knows nothing about radio buttons or forms or anything like that.
