### ISSUE TITLE
test_date may fail in certain timezones

### ISSUE THREAD

**Issue by boutil** [Shopify/liquid#630]
Hi,

As part of the effort of the Debian GNU/Linux distribution to provide reproducible binary packages, it has been noticed that the test_date test case can fail when run in a certain timezone (TZ=UTC-14), because of some arithmetic problems around midnight. See
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=788694
for the Debian report and 
https://reproducible.debian.net/rb-pkg/unstable/amd64/ruby-liquid.html
for the full build log.

I don't know exactly what would be the best way to deal with that. Is fixing deterministically the timezone during the test could be considered?

Cheers,

Cédric

**Comment by fw42** [comment]
Thanks for the bug report!

**Comment by pushrax** [comment]
Do you mean UTC+14? It looks to me like UTC-14 isn't a standard timezone.

**Comment by boutil** [comment]
I think that they used on purpose a non standard timezone (hence the 'weird' adjective in the Debian bug report).

**Comment by dylanahsmith** [comment]
`TZ=UTC+14` also reproduces the test failure.

**Comment by boutil** [comment]
thank you!

**Comment by pushrax** [comment]
@boutil fix is present in v2.6.3 and v3.0.5.
