### ISSUE TITLE
nodelist doesn't show the if part of the statement

### ISSUE THREAD

**Issue by robinmonjo** [Shopify/liquid#634]
Using version 2.6.3 of the gem:

````ruby
irb(main):001:0> t = Liquid::Template.parse('{% if true %} "in if" {% else %} "in else" {% endif %}')
=> #<Liquid::Template:0x007fadb2e32cb0 @resource_limits={}, @root=#<Liquid::Document:0x007fadb2e32800 @nodelist=[#<Liquid::If:0x007fadb2e322d8 @blocks=[#<Condition true>, #<Condition >], @nodelist=[" \"non hello\" "], @tag_name="if", @markup="true ">]>>
````

in the `nodelist` I only have the "non hello" statement but don't have the "hello" one. I see the same behaviour with the `{% elsif %}` tag.

**Comment by dylanahsmith** [comment]
What version are you using?

```
irb> Liquid::Template.parse('{% if true %} "in if" {% else %} "in else" {% endif %}').root.nodelist.first.nodelist
=> [#<Liquid::BlockBody:0x007faa1c72afb0 @nodelist=[" \"in if\" "], @blank=false>, #<Liquid::BlockBody:0x007faa1c72adf8 @nodelist=[" \"in else\" "], @blank=false>]
```

that looks right to me.

> I only have the "non hello" statement

I don't even see where that comes from in your example.

**Comment by robinmonjo** [comment]
Using version 2.6.3.

Yep sorry, I thought I would change my example but only changed the first line of the example. Here is a proper example:

````ruby
irb(main):001:0> t = Liquid::Template.parse('{% if true %} "hello" {% else %} "non hello" {% endif %}')
=> #<Liquid::Template:0x007fadb2e32cb0 @resource_limits={}, @root=#<Liquid::Document:0x007fadb2e32800 @nodelist=[#<Liquid::If:0x007fadb2e322d8 @blocks=[#<Condition true>, #<Condition >], @nodelist=[" \"non hello\" "], @tag_name="if", @markup="true ">]>>
```` 

The issue I have is that in the `nodelist` of the If tag, I only see the "non hello" statement. I'm expecting to see `["hello", "non hello"]`, "hello" coming from the if block and "non hello" from the else block.

**Comment by dylanahsmith** [comment]
Sounds like commit ca5bc5d75b6328225686c2cdd549a12255954073 already fixed that for you.  Use any 3.0.x version and you will get what you expect.

**Comment by robinmonjo** [comment]
Great ! thank you for your very fast answer.
