### ISSUE TITLE
Product look up using handle

### ISSUE THREAD

**Issue by gopinathpara** [Shopify/liquid#641]
I've a curious case where my client wants to show different products for different blog post. So i was thinking if I can use the blog excerpt filed to define all the handles of the products that he want to show on that blog post , then we can do the rest using some liquid mimic.

in excerpt , libero-quis-enim-vehicu | lalibero-quis-enim-vehicula
in article.liquid
```
{% assign handles =  article.excerpt  | split: "|" %}
    {% for i in handles %}                                 
       {{ all_products['i'].title  }}                          
    {% endfor %}

```

But for some reason this way is not working. Any suggestions on this ?
@carolineschnapp @Shopify/design-gurus @fw42

**Comment by pushrax** [comment]
Try removing the quotes around 'i', otherwise it is treated as a string literal.

**Comment by gopinathpara** [comment]
Yes i did tried doing that. But no luck :(

**Comment by pushrax** [comment]
If you just output the value of `i`, is it correct?

**Comment by gopinathpara** [comment]
Yes. I'm getting the two handles in excerpt for *i*.

**Comment by pushrax** [comment]
And if you try calling `all_products` directly with an existing handle does it work?

(btw to be clear, you definitely also have to remove the quotes in `'i'` or it won't work)

**Comment by gopinathpara** [comment]
Yes. I tried '''all_products['libero-quis-enim-vehicu']''' and its working!

**Comment by nickpearson** [comment]
There are spaces in your example excerpt `libero-quis-enim-vehicu | lalibero-quis-enim-vehicula`, and spaces are not discarded in `split`. If the excerpt is correct, your code is actually calling `all_products['libero-quis-enim-vehicu ']`. Try removing the spaces or calling `strip` when assigning a new variable inside your `for` loop.

**Comment by pushrax** [comment]
Good catch @nickpearson

**Comment by carolineschnapp** [comment]
Revised code:

```liquid
{% assign handles =  article.excerpt | split: '|' %}
{% for handle in handles %}
  {% assign handle = handle | strip %}                                 
  {{ all_products[handle].title  }}                          
{% endfor %}
```

Try that ^^

**Comment by carolineschnapp** [comment]
Or:

```liquid
{% assign handles = article.excerpt | remove: ' ' | split: '|' %}
{% for handle in handles %}                                
  {{ all_products[handle].title  }}                          
{% endfor %}
```

**Comment by gopinathpara** [comment]
Thanks @carolineschnapp !
I tried both but none of them seems working :(

**Comment by gopinathpara** [comment]
I really appropriate for taking your time to answers this question and i know that you guys have million things right now to do to make shopify awesome platform but I would really appreciate if any one can help me with their further thoughts on this issue ? @carolineschnapp

**Comment by carolineschnapp** [comment]
I tested the code I gave you in a sandbox and it works great. I am able to list all the products' titles. No issue there. Why don't you start a thread here: https://ecommerce.shopify.com/c/ecommerce-design, and place a link to your store over there, and I will have a look and follow up with you. This repo here is for Liquid, not Shopify's Liquid.

**Comment by gopinathpara** [comment]
:+1:  Awesome! it is working! :dancers: 
My bad. I've entered the handle as text not through excerpt html edit :laughing:

**Comment by nym1k** [comment]
Thank you! This was driving me crazy. Didn't think to try using strip
