### ISSUE TITLE
slice filter doesn't work

### ISSUE THREAD

**Issue by Shadowen** [Shopify/liquid#643]
I am using the wiki's example on a GitHub Pages Jekyll blog.

> `slice` - slice a string. Takes an offset and length, e.g. `{{ "hello" | slice: -3, 3 }}` #=> `llo`

The filter doesn't appear to be recognized as the output is simply

    hello

**Comment by pushrax** [comment]
GitHub Pages is still using an older Jekyll which uses Liquid 2.6. The slice filter was added in Liquid 3, so it's not available there.

You can use a newer version of Jekyll, but you will need to generate the site locally and push compiled HTML files.

**Comment by Shadowen** [comment]
Ahh. I thought it might have been something like that. Thanks for the clarification.
