### ISSUE TITLE
Insert script in page

### ISSUE THREAD

**Issue by livertonli12** [Shopify/liquid#647]
Hello, 

I would like to insert script at one page that use's liquid and i'm always receiving this message:

Script tags are not allowed in this include

i'm trying to do right this:

<script type="text/javascript">
my scripts here
</script>

What am I doing wrong ? =/

**Comment by fw42** [comment]
Liquid knows nothing about "script tags". Is this in Shopify?

**Comment by livertonli12** [comment]
It's in VTEX that also uses liquid. 

I thought that would be possible to insert inline javascript =/

**Comment by fw42** [comment]
I don't know what VTEX is but this doesn't seem like an issue with Liquid but an issue with VTEX.
