### ISSUE TITLE
bundle/ruby/2.2.0/gems/liquid-2.5.5/lib/liquid/htmltags.rb:43

### ISSUE THREAD

**Issue by DouglasAllen** [Shopify/liquid#648]
: warning: duplicated key at line 46 ignored: "index0"
And my sinatra app using it just loops and loops with this warning and I never get any pages.
I'll try to use a newer version but I have not too old gems that are dependent on this version.
Here are some parts of my Gemfile.lock
jekyll (1.2.1)
      classifier (~> 1.3)
      colorator (~> 0.1)
      commander (~> 4.1.3)
      directory_watcher (~> 1.4.1)
      liquid (~> 2.5.2)
      maruku (~> 0.5)
      pygments.rb (~> 0.5.0)
      redcarpet (~> 2.3.0)
      safe_yaml (~> 0.7.0)
so it loaded
liquid (2.5.5)

**Comment by fw42** [comment]
> duplicated key at line 46

what's on line 46?

**Comment by pushrax** [comment]
This was fixed in later liquid versions, just update and the warning will go away.
