### ISSUE TITLE
Adding an object_type to all resources

### ISSUE THREAD

**Issue by bakura10** [Shopify/liquid#650]
Hi,

I was asked by the Theme team to post the suggestion here.

Sometimes, I need to display things differently based on the inner type of the object (for instance in search results, where blog could be mixed with products). Therefore, it would be nice if all Shopify objects had a new attribute "object_type" that would be the type of the object (so "product", "collection", "article"… and so on).

Currently, the only way is to "hack" around by checking the existence of some properties, but this is definitely not optimal.

Let me know if you need more info about the context of that!

Thanks!

**Comment by cshold** [comment]
I just came across the same use case, also on search.liquid.

To figure out if you have an article as `item` in `{% for item in search.results %}` you have to check if `item.moderated?` is specifically set to `true` or `false`, not just boolean values. Pages and products won't have that attribute set at all.

Check for a product by looking if `item.price` exists. Remaining `item`s in `search.results` must be pages.

Definitely not ideal to have to resort to this.

cc @Shopify/themes-team @Shopify/storefront

**Comment by fw42** [comment]
Yeah that sounds terrible, don't do that. That will break in the future for sure...

**Comment by fw42** [comment]
I'm closing this here since this issue has actually nothing to do with the liquid Ruby gem

**Comment by cshold** [comment]
Should I open this in core then?

**Comment by fw42** [comment]
yes please

**Comment by bakura10** [comment]
Thanks @cshold for opening a new issue :).

**Comment by rickydazla** [comment]
Ooh 🍏

**Comment by Thibaut** [comment]
@bakura10 @rickydazla  `object_type` is now available on search result objects :fireworks:

Thanks for the feedback/suggestion!

**Comment by bakura10** [comment]
Awesome! Thanks a lot :)
