### ISSUE TITLE
Dynamic property lookup?

### ISSUE THREAD

**Issue by StevenLangbroek** [Shopify/liquid#651]
I can't find any documentation about this, but is it possible to lookup a property on an object based on another value? Something along these lines?

```liquid
{{ post[current_category]["post_count"] }}
```

Assuming a data-structure like so:

```
current_category = "tech"
post = {
  tech: {
    post_count: 1
  }
}
```

**Comment by pushrax** [comment]
The syntax for this is exactly as you have in your example.

**Comment by pushrax** [comment]
Note: if you want to have nested square bracket lookups (e.g. `x[y[z]]`), you need to use the strict parser due to an issue in the lax one: https://github.com/Shopify/liquid/pull/473.
