### ISSUE TITLE
jsonify filter is not displaying quotes correctly

### ISSUE THREAD

**Issue by d3netxer** [Shopify/liquid#654]
In Jekyll I am trying to create my posts in json format and I am using this filter:

"content":{{ story.content | jsonify }}

but it is giving me a weird output for the single and double quotation marks I have in my content. Also, in the previous version I made I think this was working correctly, but I don't think my latest change could have affected the new output. 

Here is an example of the first few line of the json file it is outputting:

"content":"<p>Kepha Ngito grew up in Kenya in a neighborhood of Nairobi called Kibera, where hundreds of thousands live in poverty. â€œI grew up in that time when we didnâ€™t have a physical address. My house was never numbered. It wasnâ€™t existent; it was not on the map.â€ Ngitoâ€™s father worked in a factory to pay his tuition through high school. "

**Comment by dylanahsmith** [comment]
`jsonify` isn't a filter provided by liquid, so it sound like this may be an issue with jekyll.  It would probably also help them if you provided the input string and encoding that produced that output.

**Comment by parkr** [comment]
@d3netxer Try adding `encoding: utf-8` to your `_config.yml` file and re-running Jekyll.

**Comment by d3netxer** [comment]
I just tried adding the encoding: utf-8 to my config.ml file and re-running Jekyll, but it didn't work @parkr

**Comment by d3netxer** [comment]
here is my input string:

---

Kepha Ngito grew up in Kenya in a neighborhood of Nairobi called Kibera, where hundreds of thousands live in poverty. “I grew up in that time when we didn’t have a physical address. My house was never numbered. It wasn’t existent; it was not on the map.” Ngito’s father worked in a factory to pay his tuition through high school. Education gave Ngito the option to leave Kibera. Instead, he stayed and became a community activist, starting Map Kibera Trust, a non-profit that uses OpenStreetMap technology. Maps provide hard data to justify allocation of resources. He says no maps equals no data and therefore no political power. “For many years Kibera was not on the map despite the fact that hundreds of thousands of people live there. It means they were not quantified as people.”

**Comment by d3netxer** [comment]
I noticed that in Chrome when I browse to stories.json and try to switch the encoding to utf-8 it is greyed out. In Jekyll, in the _site folder of my project I opened the stories.json file and it look good for the most part. Here is a snippit:

{
      "title": "Empowering People, Developing Communities",
      "excerpt": "Maps led to validation and more government resources for the people of Kibera in Nairobi Kenya.",
      "author": "MapGive",
      "date": "2009-11-01",
      "lat": -1.312797,
      "lon": 36.7882827,
      "image": "assets/img/kepha-ngito.jpg",
      "tags": "[Kenya,Kibera,Case Study,slums]",
      "baseurl": "http://mapgive.state.gov/",
      "content":"<p>Kepha Ngito grew up in Kenya in a neighborhood of Nairobi called Kibera, where hundreds of thousands live in poverty. “I grew up in that time when we didn’t have a physical address. My house was never numbered. It wasn’t existent; it was not on the map.” Ngito’s father worked in a factory to pay his tuition through high school. Education gave Ngito the option to leave Kibera. Instead, he stayed and became a community activist, starting Map Kibera Trust, a non-profit that uses OpenStreetMap technology. Maps provide hard data to justify allocation of resources. He says no maps equals no data and therefore no political power. “For many years Kibera was not on the map despite the fact that hundreds of thousands of people live there. It means they were not quantified as people.”
}

Maybe the output is not perfect utf-8, so the browser isn't able to read it in uff-8?

**Comment by parkr** [comment]
Oh! Maybe we aren't defaulting to charset=utf-8 for the server. Let's move this over to jekyll/jekyll.

**Comment by parkr** [comment]
https://github.com/jekyll/jekyll/issues/4003

**Comment by pushrax** [comment]
Thanks for responding so quickly @parkr :smile:

**Comment by parkr** [comment]
:smiley:
