### ISSUE TITLE
incorrect description in Shopify Documentation for default filter

### ISSUE THREAD

**Issue by mikebridge** [Shopify/liquid#657]
The description for the default filter reads "Sets a default value for any variable with no assigned value. Can be used with strings, arrays, and hashes." and the comment reads `<!-- if customer.name is nil -->`

   https://docs.shopify.com/themes/liquid-documentation/filters/additional-filters#default

As per https://github.com/Shopify/liquid/pull/267, It should indicate that for strings, the default value is returned if it is assigned nil or if it assigned an empty string (but not a string with whitespace).  I.e.:

```liquid
{{ nil | default: "NIL TEST" }}
=> NIL TEST
{{ "" | default: "ES TEST" }}
=> ES TEST
{{ "   " | default: "SPACES TEST" }}
=>    
```

**Comment by pushrax** [comment]
@Shopify/documentation

**Comment by admhlt** [comment]
This is a great suggestion. Thanks, Mike. I've made the fix and it should be in our live docs very soon.

**Comment by mikebridge** [comment]
@admhlt Great, thanks!
