### ISSUE TITLE
Parser raises Syntax Error even in lax mode

### ISSUE THREAD

**Issue by davidgf** [Shopify/liquid#659]
Using Ruby 1.9.3 and Liquid 3.0.6, even if lax mode is set, an exception is raised when the syntax is not correct. Is that the expected behavior? For instance:

```ruby
1.9.3-p551 :041 > Liquid::Template.error_mode = :lax
 => :lax
1.9.3-p551 :042 > Liquid::Template.error_mode
 => :lax
1.9.3-p551 :043 > Liquid::Template.parse("Thank you for your purchase at {{shop_name}")
Liquid::SyntaxError: Liquid syntax error: Variable '{{shop_name}' was not properly terminated with regexp: /\}\}/
    from /Users/david/.rvm/gems/ruby-1.9.3-p551/gems/liquid-3.0.6/lib/liquid/block.rb:104:in `create_variable'
    from /Users/david/.rvm/gems/ruby-1.9.3-p551/gems/liquid-3.0.6/lib/liquid/block.rb:44:in `parse'
    from /Users/david/.rvm/gems/ruby-1.9.3-p551/gems/liquid-3.0.6/lib/liquid/tag.rb:10:in `parse'
    from /Users/david/.rvm/gems/ruby-1.9.3-p551/gems/liquid-3.0.6/lib/liquid/document.rb:5:in `parse'
    from /Users/david/.rvm/gems/ruby-1.9.3-p551/gems/liquid-3.0.6/lib/liquid/template.rb:122:in `parse'
    from /Users/david/.rvm/gems/ruby-1.9.3-p551/gems/liquid-3.0.6/lib/liquid/template.rb:108:in `parse'
    from (irb):43
    from /Users/david/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.17/lib/rails/commands/console.rb:47:in `start'
    from /Users/david/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.17/lib/rails/commands/console.rb:8:in `start'
    from /Users/david/.rvm/gems/ruby-1.9.3-p551/gems/railties-3.2.17/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

**Comment by fw42** [comment]
Yes, that's the expected behaviour

**Comment by Premanandh-S** [comment]
Still I am confused what is the purpose of error_mode here. 

Got the following error even though set the error_mode as `:lax` or `:warn`

`Liquid::SyntaxError (Liquid syntax error: Variable '{{subscriber.first_name}' was not properly terminated with regexp: /\}\}/):`

If there is no use then please update readme.md file.

**Comment by pushrax** [comment]
Liquid works by first parsing a tag (either `{{ ... }}` or `{% ... %}`) and then running a second parser on the contents of that tag. `error_mode` refers to the behaviour of that second parser: use the older quirky regex-based parser that ignores lots of errors (but not all of them), or use the newer strict parser that doesn't ignore errors.

In either case, the first parser will throw errors.
