### ISSUE TITLE
HTML Comments on liquid syntax doesn't work

### ISSUE THREAD

**Issue by Amay22** [Shopify/liquid#666]
If you use the HTML comments () on liquid syntax; It still compiles and runs and works. For instance for Loops still run. Maybe this is how it is intended to be cause liquid has it's own comment tag but since it is embedded in HTML it would seem sensible that it inherits the comment of the encapsulating language and become inactive itself.

**Comment by dylanahsmith** [comment]
This is expected behaviour.  Use a liquid comment to comment out liquid markup, and an HTML comment to comment out HTML.
