### ISSUE TITLE
Make asset_url size aware

### ISSUE THREAD

**Issue by bakura10** [Shopify/liquid#670]
Hi everyone :),

With the new very high resolution screen like iMac 5K, I realize that some of our theme customers start to want uploading very high resolution slider image.

However, when it comes to mobile, loading a 2000 or 2500 px wide image is... awful.

Therefore, it would be nice if asset_url would support an optional size (medium, large, grande...), as for img_url. Shopify architecture already supports that actually (if your image is 'slider_image_1.jpg', using 'slider_image_1_large.jpg' for asset_url properly generate the proper image). But it's not documented, forces to do some Liquid string manipulation, so I'm a bit afraid in using this for our published themes in the Theme Store, albeit all the benefits.

Would it be possible to add this feature? Along with srcset, it definitely opens a lot of exciting mobile possibilities.

Thanks

**Comment by fw42** [comment]
asset_url is not part of Liquid core, this is about Shopify, not about Liquid
