### ISSUE TITLE
Liquid is stripping out non english characters

### ISSUE THREAD

**Issue by schaeken** [Shopify/liquid#674]
## Problem

Greek shop is displaying everything in Greek. They have a product tag filter option on the collection page. Something similar to screenshot below. The tag outputs correctly but the link to the tag is stripped of all non english characters. For example using something like `{{ tag | handle }}` for the tag `ΔΕΡΜΆΤΙΝΟ_Κάσας` outputs `_` . 

Same with `{{ tag | remove_first: cat_item | remove_first: '_' | link_to_add_tag: tag }}`

![https://screenshot.click/Screen_Shot_2015-11-24_at_1.34.56_PM.jpg](https://screenshot.click/Screen_Shot_2015-11-24_at_1.34.56_PM.jpg)

cc @Shopify/theme-support

**Comment by fw42** [comment]
This seems like a Shopify bug to me, not a Liquid core problem. Closing until proven otherwise :-)

**Comment by NathanPJF** [comment]
Doesn't appear to be a problem with liquid.  It's Shopify trying to give you the handle/url of a page that has non-english characters in it.  In the screenshots below you can see that while liquid doesn't handle the Greek letters well (can't uppercase the letters like CSS does for the title), but it's doesn't strip the output of the characters.

@schaeken In your example, you have the filter `link_to_add_tag`.  That is trying to give the URL of the page - which is actually accurate if you see the last screenshot.  Accurate, but not great.

![http://take.ms/bEQrU](http://take.ms/bEQrU)

![http://take.ms/GnQit](http://take.ms/GnQit)

**Comment by NathanPJF** [comment]
@schaeken Worth opening a new issue in the shopify repo and reference this past PR about link list handles have non-english characters: https://github.com/Shopify/shopify/pull/5185/files
