### ISSUE TITLE
Integrate "Pluralize" into Liquid for Designers

### ISSUE THREAD

**Issue by Xspirits** [Shopify/liquid#675]
Hey everyone!

Kudos for the excellent work done on this projet so far, very impressive!
I tried to use the **Pluralize** filter ( `{{ my_var | Pluralize: 'hour', 'hours' }}`) but later discovered that it is not included in https://github.com/Shopify/liquid/wiki/Liquid-for-Designers.

Do you think it would be possible to implement this, as it is on the [Shopify Doc](https://docs.shopify.com/themes/liquid-documentation/filters/string-filters#pluralize)?

Best,
Thomas

**Comment by mikebridge** [comment]
I added a line for this here: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers#standard-filters.  

I think anyone can edit that page if there's something missing.
