### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by parkr** [Shopify/liquid#676]
Hello friends! In anticipation of new docs ( #513 ), what do you think about doing another release? 3.0.6 is 222 commits behind master. We don't use `master` in Jekyll (I hear Shopify just uses `master`?) so making releases as changes can be pushed out seems like a good idea.

What do you think about creating a release schedule such that every month or two a new release is pushed out?

**Comment by dylanahsmith** [comment]
Shopify isn't always on `master`, but we do normally reference liquid by sha, and bump the sha to point to master whenever we want to take advantage of one of our changes in Shopify.

I'm not opposed to a release, but I think we have breaking changes that would mean the next release of master would be `4.0.0`.  Notice that [lib/liquid/version.rb](https://github.com/Shopify/liquid/blob/5f8086572b5e3f6003d207fed902eee59f1bd03b/lib/liquid/version.rb) currently has `VERSION = "4.0.0.alpha"`

**Comment by parkr** [comment]
Ok, thanks for that info Dylan. Is 3.x debunked? What has changed in 4.0 that is breaking?

**Comment by Wasserschlange** [comment]
If there is a release to be provided, would it be possible if it has not already been done to provide a versioning structure? I have tried looking for liquid's versioning structure, but I unfortunately found none.

**Comment by parkr** [comment]
@dylanahsmith What are the breaking changes? I'll test Jekyll master against Liquid master and see if we have anything that breaks. Not ready for Jekyll 4 but want to get all the latest updates in Liquid! Good to keep things fresh and bugs fixed.

**Comment by basex** [comment]
Is there a list of breaking changes to v4?

**Comment by dylanahsmith** [comment]
https://github.com/Shopify/liquid/blob/master/History.md for list of changes, although perhaps we should separate the changes into 3 categories based on which component of the version number needs to be bumped for it:
1. breaking changes
2. added features
3. bug fixes

For now you can probably ignore any change that starts with "Add"

**Comment by parkr** [comment]
> perhaps we should separate the changes into 3 categories based on which component of the version number needs to be bumped for it

This is a spectacular idea – would love to see this change made for 4.0.

**Comment by parkr** [comment]
https://github.com/jekyll/jekyll/pull/4348

**Comment by fw42** [comment]
We have [v4.0.0.rc1](https://github.com/Shopify/liquid/releases/tag/v4.0.0.rc1) now, so closing this

**Comment by parkr** [comment]
@fw42 What's your plan for a full 4.0.0 release?

**Comment by fw42** [comment]
no plan yet :(
