### ISSUE TITLE
Get all variables used in a template

### ISSUE THREAD

**Issue by anitsirc** [Shopify/liquid#685]
Hi, 

Is there a way of finding out all variables being used in a template, or at least the ones that it couldn't replace when rendering the template? Both, the ones used as `{{ name }}` and also the ones used in other tags `{% if name == 'John' %}` 

Thanks :)

**Comment by fw42** [comment]
Not that I know of, no. Sorry :(

**Comment by pushrax** [comment]
You could add some hooks to the variable lookup function if you are ok with running a custom liquid version.

**Comment by dsignr** [comment]
Hi, is there a solution for this yet? I'd also like to find all variables used in a template. Thank you.

**Comment by fw42** [comment]
No solution, sorry. And nothing planned so far. But I'm open to look at suggestions.

**Comment by dsignr** [comment]
Somewhat hacky, but I put together this for my use case:

```ruby
def get_variables(t)
      variables = []
      nodes = Liquid::Template.parse(t).root.nodelist
      nodes.each do |n|
        variables << n.name.name if n.is_a? Liquid::Variable
      end #End loop
      #Return
      variables
 end #End method

>> get_variables("{{client_name}} is such a {{animal}}")
>> ["client_name", "animal"]
```

Not even sure if this is ok. What do you think? :D

**Comment by pushrax** [comment]
Assuming you only care about top level variables that will work. You also need to check that `n.name` is a `VariableLookup` though, if you have something like `{{ "foo" }}` then it'll be a string.

**Comment by dsignr** [comment]
Wow, I didn't know that you could have variables like that. Thanks for the suggestion, thanks!

**Comment by hugopl** [comment]
If you export all your variables using Liquid::Drop, you can run your liquid template against mock liquid drop with same methods as the usual liquid drop, but registering what variables were used.

**Comment by JanStevens** [comment]
With https://github.com/Shopify/liquid/pull/1025 being available in 4.0.2 this can now be achieved using the following code

```ruby
Liquid::ParseTreeVisitor.for(Liquid::Template.parse(liquid_string).root).add_callback_for(Liquid::VariableLookup) do |node|
  [node.name, *node.lookups].join('.')
end.visit.flatten.compact
```

**Comment by viral810** [comment]
```ruby
liquid_string = "Hi {{ name }}"

vars = Liquid::Template
.parse(liquid_string)
.root
.nodelist
.select { _1.is_a? Liquid::Variable }
.map(&:name)
.map(&:name)
.uniq

vars # => ["name"]
```

**Comment by marctorrelles** [comment]
@fer9305 I'm also interested in this. Did you find a way to filter them out?
