### ISSUE TITLE
"Canonical" documentation of Liquid

### ISSUE THREAD

**Issue by chrisdpeters** [Shopify/liquid#686]
I have chosen Liquid as the templating engine for a project that I'm working on. As I write documentation about Liquid for my project, I have had a couple ideas.

First, some background:

*  I find Shopify's documentation of using Liquid to be rather good, but I feel that I need to write my own documentation without just a straight copy and paste of Shopify's content.
*  There are some cases where my project will omit some things that are documented on docs.shopify.com because they aren't needed, so linking from my site to Shopify's would cause confusion for my users.
*  It's unclear to me if copying and pasting parts of Shopify's content into my own site would get me into trouble if you get what I'm saying.

In the spirit of supporting open source, I'm wondering if there's a way that I can help lead the development of a "canonical" set of descriptions for core tags, filters, etc. that are in a base install of Liquid. I understand that the wiki has some descriptions, but I find many of them to be incomplete or lacking, and I somewhat distrust that they are up-to-date.

This documentation would be released Creative Commons or similar and would encourage developers to be able to link to, redistribute, and extend the content for their own projects, commercial or not. Perhaps a subdomain of liquidmarkup.org would be a good place to host a polished, readable version.

What format would be best for this sort of thing, if you know what I'm asking? The wiki? A Rails Guides-style setup? I ask because I am not super experienced in working with these sorts of setups but am willing to invest some time to learn and would welcome guidance and/or pointers on how you would do it if you had infinite time. I do know how to write at least. :)

A key question: how much of its own content from docs.shopify.com is Shopify willing to contribute to this end? Or would that be off-limits? Personally, I understand either way.

I welcome ideas or a rejection of this idea altogether of course.

**Comment by fw42** [comment]
@Tetsuro, @parkr, and @admhlt might be interested in this. Also, take a look at https://github.com/Shopify/liquid/pull/513 and the ongoing discussion there.

**Comment by chrisdpeters** [comment]
@fw42 Thank you for the pointer. I will definitely review the discussion and perhaps contribute to it myself. Looks like maybe we should close this issue in lieu of that one.

**Comment by admhlt** [comment]
Hi @chrisdpeters! As Flo said, documentation for "core" Liquid is in the works and we're getting very excited and close to having something ready to ship soon.

Feel free to check out #513 and contribute there if you like. Thanks for the interest! :+1:

**Comment by chrisdpeters** [comment]
@admhlt Thank you! I didn't even think to look at Pull Requests.
