### ISSUE TITLE
Hidden product accessible through all_products object

### ISSUE THREAD

**Issue by gina3five** [Shopify/liquid#690]
Not sure if this is the right place to ask about this, but I was getting nowhere with the Shopify chat support.

I've noticed that I can access a hidden product's attributes, is that intentional?

{% assign demo_product_handle = product.handle | append: '-demo' %}
{% assign demo_product = all_products[demo_product_handle] %}
{% if demo_product != empty and demo_product.available %}
  {{ 'Purchase Demo' | link_to: demo_product.url }}
{% endif %}

In the above example, if the demo product exists but is hidden, the Purchase Demo link is output and takes you to a 404. I figured out a workaround of also checking the published_at attribute (not in the list of product attributes: https://docs.shopify.com/themes/liquid-documentation/objects/product).

Anyway, I was wondering if this is intentional or a bug. Thanks.

**Comment by fw42** [comment]
@carolineschnapp any thoughts here? how should people test for products being hidden?

**Comment by fw42** [comment]
or should we make the global thing not return hidden products (and return an empty value instead)?

**Comment by carolineschnapp** [comment]
I think the global thing should return an empty value. Hidden products, or hidden collections, or pages, act the same way as if they were perfectly non-existent, from a Liquid / theme point of view.

**Comment by gina3five** [comment]
It's an interesting loophole that might have edge-case usefulness, but for consistency sake, I agree with Caroline.

**Comment by fw42** [comment]
Ok, I will get this fixed. Thanks for bringing it up.

**Comment by fw42** [comment]
This should be fixed now.

**Comment by gina3five** [comment]
On a somewhat related note... should hidden products be showing up in the list of products when you create a product dropdown in theme settings?

https://docs.shopify.com/themes/theme-development/storefront-editor/settings-schema#product

**Comment by dlannan** [comment]
Could someone explain why this is a good idea?
How can you modify metafields on a hidden product, or "prepare" a hidden product in liquid now, if its not available anywhere in any collections?

**Comment by fw42** [comment]
It's not a good idea. It was a bug (that has been fixed). You can no longer access hidden products this way.

**Comment by dlannan** [comment]
I understand some people would see it as a bug, and others would not. 
Thats fine, its your system. But what is the solution for handling hidden products then? Write an app  I assume? Wouldnt a "good idea" be able to allow people to iterate their products, check for publication and use that to determine inclusion in a list or what ever? 
From our usage as a service type, we need to setup product information before publication and even have the customer review it before publication, so this means all sorts of limitations to our development - just makes moving to another system an easier choice.

**Comment by fw42** [comment]
I'm not familiar enough with this area of Shopify to give a qualified answer to that question. And this repository isn't really the right place to discuss this "feature request". This repository is about Liquid. Not about Shopify. Feel free to reach out to our theme support team though (assuming this is a theme-related question, I'm not sure I understand you correctly).
