### ISSUE TITLE
PHPStorm support

### ISSUE THREAD

**Issue by dereuromark** [Shopify/liquid#692]
This template engine would get a huge users increase when available as PHPStorm (and other IDEs?) plugin.
Right now only Twig is available, making the choise usually pretty quick.
But if IDE support for this engine would be available, I bet quite a lot would chose differently.

IDE support really helps development, and especially beginners.

Refs https://plugins.jetbrains.com/wishlist/show?pr=&wid=404

PS: There is also the idea to use liquid (MIT license is better than the Twig one) for CakePHP Bake plugin ( https://github.com/cakephp/bake/issues/185 ), which could also vastly increase usage and popularity. But without good IDE support this will also be quite unlikely.

**Comment by fw42** [comment]
I'm gonna close this issue since this is not really a bug nor a feature request for Liquid core... I don't think someone at Shopify will take this on, but if you decide to do it yourself, I'm happy to add a link to our README or something like that.
