### ISSUE TITLE
The "include" tag raises Ruby error when non existing variable is passed as attribute

### ISSUE THREAD

**Issue by tanelj** [Shopify/liquid#697]
The `include` tag raises Ruby error on render when non existing variable is passed as attribute.

Example code:

```ruby
{% assign foo = "my-partial" %}
{% include bar %}
```

Returns error:

```
undefined method `split' for nil:NilClass
liquid (4.0.0.rc1) lib/liquid/tags/include.rb:47:in `render'
liquid (4.0.0.rc1) lib/liquid/block_body.rb:90:in `render_node'
```

At the moment there is line:

```ruby
context_variable_name = template_name.split('/'.freeze).last
```

It seems that `to_s` should be enough here. Am I right?

```ruby
context_variable_name = template_name.to_s.split('/'.freeze).last
```

**Comment by fw42** [comment]
Hm not sure what the correct behaviour should be. Do nothing? With `strict_variables: true`, it should probably raise? @pushrax thoughts?

**Comment by pushrax** [comment]
As much as I don't like it, nothing should happen when you do to this, as that's the precedent set by Liquid in general. I agree that with `strict_variables` it should raise, in fact should already.

**Comment by pushrax** [comment]
@tanelj if we are going with that behaviour, the correct change is to check if `template_name` is nil and return `''.freeze` from `render`.

**Comment by dylanahsmith** [comment]
It sounds like this is primarily a bug in the template which should get fixed, so why does it sound like you are trying to workaround this bug?  What does the file system that you are using do in this case?  LocalFileSystem will render `Liquid error: Illegal template name ''` in this case.

> As much as I don't like it, I think that nothing should happen when you do to this, as that's the precedent set by Liquid in general.

We don't need to keep repeating that mistake.  By doing nothing it makes it harder for template developers to debug the error and makes it more likely that a template will not notice and possibly even depend on that error.  It is much harder to make things strict later on, so let's just improve the error message.

Perhaps we should explicitly raise in this case from Liquid::Include#render.

**Comment by tanelj** [comment]
Thanks!

Yes its better to improve our error handling. We have custom FileSystem implementation and now it raises `FileSystemError` when something is missing or included name is missing.
