### ISSUE TITLE
Shopify filters?

### ISSUE THREAD

**Issue by willlahr** [Shopify/liquid#700]
Is there a way to all all of the standard Shopify filters to liquid?  . For example url_param_escape is 
described here:

https://docs.shopify.com/themes/liquid-documentation/filters/string-filters#url_param_escape

This does not seem to be included as part of the standard liquid gem

```
$irb
require 'liquid'
Liquid::Template.parse('{{ " & " | url_param_escape }} ').render 
=> " & "
```

Also posted here: http://stackoverflow.com/questions/35287185/how-to-add-all-the-shopify-filters-to-standard-liquid

**Comment by pushrax** [comment]
As the response to that StackOverflow post recommended, you can add your own custom implementations.

If there are some specific filter you think are appropriate for Liquid itself, feel free to open individual issues with use cases in mind.
