### ISSUE TITLE
Allow checking if a tag exists

### ISSUE THREAD

**Issue by jeaye** [Shopify/liquid#704]
(note: this was originally created here https://github.com/jekyll/jekyll/issues/4573 and has been relocated)

###### What version of Jekyll are you using (`jekyll -v`)?

Github Pages (jekyll 3.0)

###### What did you do?

I have a shared header include across multiple jekyll sites. One of them is to use an [Atom Feed](https://help.github.com/articles/atom-rss-feeds-for-github-pages/) and requires `{% feed_meta %}` within `<head>`. I'd like to be able to check for the existence of tags and conditionally use them. When this didn't work with `if`, like so:

```liquid
{% if feed_meta %}
  {% feed_meta %}
{% endif %}
```

I tried wrapping it in a variable for the if expression instead, adding a bool to my `_config.yml`:

```liquid
{% if site.has_feed %}
  {% feed_meta %}
{% endif %}
```

###### What did you expect to see?

I expected that meta-programming on tags would be permitted, allowing more code reuse, in my case.

###### What did you see instead?

In both cases shown above, the jekyll build fails, as `feed_meta` is an unknown tag. I haven't yet found a way to share this header which may or may not use the `feed_meta` tag.

Note that this isn't bound to the effects or origins of `feed_meta` itself; the lack of meta-programming capabilities with tags is the issue I'm bringing up. `feed_meta` is used for illustration and context.

**Comment by fw42** [comment]
Hm. I don't think we should support this kind of metaprogramming in Liquid. Using an invalid tag should be a syntax error, imho. @pushrax thoughts?

**Comment by pushrax** [comment]
I agree that we shouldn't add a reflection API and I don't want to couple parsing with rendering. Since the parsing rules for a tag are defined by the tag itself, the tag needs to exist at parse time

A workaround is to put the tag call into a partial, and conditionally include it. Partials are independently parsed (at render time of the parent).

**Comment by fw42** [comment]
I think that workaround is good enough. @jeaye does that work for you?

**Comment by jeaye** [comment]
@fw42 I can do that. Thanks for the input, folks.
