### ISSUE TITLE
Leap day issue ({% date startDate, first this month %}) resolves as March 1st on 2/29/2016

### ISSUE THREAD

**Issue by michaeltreynolds** [Shopify/liquid#706]
Leap day issue

{% date startDate, first this month %}

Resolves as March 1st on 2/29/2016

**Comment by fw42** [comment]
Can you give some more details? What's the actual code you are using?

**Comment by michaeltreynolds** [comment]
I'll look that up. I actually am using a service that uses "liquid tags". The code I pasted is my interface to their service. I'll ask them for the "actual code".

**Comment by michaeltreynolds** [comment]
Checked with the service I use and they said they said "first this month" resolved to "3/1" instead of "2/1" on leap day.

**Comment by michaeltreynolds** [comment]
Ack. Looks like I misunderstood which library was doing this for them. They've posted an issue here for a different project: 
https://github.com/mojombo/chronic/issues/327
