### ISSUE TITLE
Include dynamic filename is not working

### ISSUE THREAD

**Issue by ismnoiet** [Shopify/liquid#715]
When i use

```
{% include folder1/folder1_1/img.jpg %}
```

it works perfectly, But when i try to generate the filename dynamically let's say :

```
{%capture filename %} {{'folder1/folder1_1/'}}{{ images[0] }}{{ '.jpg' }}{% endcapture %}

{% include {{ filename }}  %} 
```

with `images[0] = 'img'` for example, i get the error that says :

```
Liquid Exception: Invalid syntax for include tag. File contains 
invalid characters or sequences ...
```

I Don't understand why including file by providing the complete path(static path) works whereas generating the filename dynamically won't work !

Any help would be more than appreciated.

**Comment by fw42** [comment]
The syntax you are using is for the Jekyll include tag, which (confusingly) is not the same as the Liquid include tag. In Liquid it's just `{% include filename %}`.

**Comment by fw42** [comment]
also you have a leading space in your filename, so that might be the reason too

**Comment by ismnoiet** [comment]
@fw42  i've tried to use only ``{% include filename %}`` but it says that **filename** doesn't exist which means that it took the lateral meaning of filename and not the value of the variable filename.

**Comment by fw42** [comment]
are you using jekyll or liquid directly?

**Comment by fw42** [comment]
> but it says that filename doesn't

what's your exact error message? can you post it here please?

**Comment by pushrax** [comment]
It must be Jekyll, `{% include folder1/folder1_1/img.jpg %}` is meaningless in Liquid.

**Comment by fw42** [comment]
hm if it's Jekyll then the include tag syntax looks correct to me though

**Comment by ismnoiet** [comment]
@fw42  Here is the error message : 
```
Liquid Exception: Included file '_includes/filename' not found in _includes/footer.html, included in _layouts/default.html
```
and i'm using liquid with jekyll.

**Comment by fw42** [comment]
Pretty sure it's the space (see [here](https://github.com/jekyll/jekyll/blob/4048b8e2a735565de2f515f55036c859415a06ae/lib/jekyll/tags/include.rb#L58-L60)).

Please try without it. Also your capture can be simplified.. Try this:
```
{% capture filename %}folder1/folder1_1/{{ images[0] }}.jpg{% endcapture %}
{% include {{ filename }} %}
```

**Comment by fw42** [comment]
kinda weird of jekyll not to allow spaces though...

**Comment by ismnoiet** [comment]
@fw42  the same thing here is the error message : 
```
Liquid Exception: Invalid syntax for include tag. 
File contains invalid characters or sequences:
 folder1/folder1_1/img.jpg Valid syntax:
 {% include file.ext param='value' param2='value' %}

```

**Comment by fw42** [comment]
@parkr?

**Comment by parkr** [comment]
hi hi! Did you try 

```
{% capture filename %}folder1/folder1_1/{{ images[0] }}.jpg{% endcapture %}
{% include {{filename}} %}
```

**Comment by ismnoiet** [comment]
yups @parkr  i get the same error!

**Comment by fw42** [comment]
Can you put your Jekyll site online somewhere so we can try to reproduce the problem? And what exact version of Jekyll are you using?

**Comment by ismnoiet** [comment]
@fw42  i'm using jekyll version ``3.1.2`` with a fresh new blog generated using `` jekyll new blog_name`` command. to develop some jekyll plugins :)

**Comment by poblabs** [comment]
I'm experiencing this issue as well. My setup is on Ubuntu 16.04 and Jekyll is installed using the simple method `sudo apt-get install jekyll`. 

I'm trying to do dynamic author bios at the bottom of each post. The idea is to grab the `{{ page.author }}` and then include their bio with the below code. 

```
  {% capture filename %}author-{{ page.author }}.html{% endcapture %}
  {% include {{filename}} %}
```

When I build the site I get this error:

```
  Liquid Exception: Included file '_includes/author-.html' not found in _layouts/post.html
jekyll 3.0.1 | Error:  Included file '_includes/author-.html' not found
```

Anything I'm missing?

**Comment by dylanahsmith** [comment]
It sounds like this is a jekyll issue, so please file the issue against that project instead.
