### ISSUE TITLE
[Docs] Breaking non-wrapping code blocks

### ISSUE THREAD

**Issue by opattison** [Shopify/liquid#724]
`<pre>` code samples extend past the boundaries of the parent `.highlight` container. Not a bug – rather some missing CSS, or perhaps layout that needs to be re-worked.

![2016-03-21 00 47 41](https://cloud.githubusercontent.com/assets/885300/13910837/bf24d5d0-eefe-11e5-93ef-cde05e79176e.png)

Screenshot via https://shopify.github.io/liquid/filters/truncatewords/ (can be reproduced between ~768-960px on Google Chrome, Firefox and likely all others)

Can be fixed with `white-space: pre-wrap` but I’m not sure if that’s the ideal fix for the Liquid docs.

**Comment by Tetsuro** [comment]
Thanks for reporting this @opattison! I will take a look once I am back from vacation.
