### ISSUE TITLE
Error when including UTF-8 filenamed files

### ISSUE THREAD

**Issue by jeffreyantony** [Shopify/liquid#752]
I have a html file as shown ( മലയാളം.html ). If I try to include this html file using the below code, I am getting the below shown error.

`{% include blog_comments/മലയാളം.html %}`

By the way I am using Jekyll. But I believe the error is from Liquid

Regenerating: 1 file(s) changed at 2016-05-05 09:49:14   Liquid Exception: Invalid syntax for include tag. File contains invalid characters or sequences: blog_comments/മലയാളം.html Valid syntax: {% include file.ext param='value' param2='value' %} in _includes/post_comments.html, included in _layouts/post.html

Does anyone know how to get the file മലയാളം.html included ?

**Comment by pushrax** [comment]
Jekyll has its own implementation of include with different syntax. Try checking over there for any existing issue and open one if there are none.
