### ISSUE TITLE
escape | (pipe) in liquid templates

### ISSUE THREAD

**Issue by jdfouse** [Shopify/liquid#753]
I have a number of values that contain **"| News"** and I want to strip them out via split. I have done this in the past without issue, however when adding the | pipe. It throws: "Liquid error: Cannot read property 'shift' of null"

Here is an example of the liquid I am using:

`{{ variableX | split: '| News' | first }}`
I have tried `\| News` & `\\| News` and the error remains.

**Comment by admhlt** [comment]
Why are you stripping the pattern using `split` and not something like [`remove`](https://shopify.github.io/liquid/filters/remove/)? That's not the intended function of `split`.

**Comment by jdfouse** [comment]
Thank you. In this case you are correct. How would I go about splitting on `|` for future reference?

**Comment by admhlt** [comment]
Splitting on `|` works just fine for me using `split: "|"`. For example:

``` liquid
{% capture menu %}
website.com | News | About | Contact
{% endcapture %}

{% assign items = menu | split: "|" %}

{% for item in items %}
- {{ item }}
{% endfor %}
```

Produces:
```
- website.com
- News
- About
- Contact
```

**Comment by jdfouse** [comment]
I see. One more question for you. Why does `{{ variableX | split: '- News' | first }}` work but not {{ variableX | split: '| News' | first }}?

**Comment by admhlt** [comment]
What's the content of `variableX`, in this case? Or some of the possible values?

**Comment by jdfouse** [comment]
"This is a long title with lot's of words | News site name"

**Comment by fw42** [comment]
Is this maybe a bug similar to https://github.com/Shopify/liquid/issues/344 and https://github.com/Shopify/liquid/issues/213? @pushrax?

**Comment by admhlt** [comment]
Sorry to sound like a broken record, @jdfouse, but again, it works fine for me. 😅 

I'm not sure how reliable droppen links are, but here's your example: http://droppen.org/?droppen=z0seydfvlukqu39rg4x6r

**Comment by jdfouse** [comment]
Hmm, I get the same error with `remove` perhaps the version of liquid that is part of the compiled library I am using. I will investigate further and advise. Thanks for your assistance.

**Comment by jdfouse** [comment]
I believe I may have been posting in the wrong place what is being used is: https://github.com/mattmccray/liquid.js

Apologies for wasting your time and many thanks for the information @admhlt.
