### ISSUE TITLE
liquidmarkup.org isn't redirecting properly

### ISSUE THREAD

**Issue by zeljkofilipin** [Shopify/liquid#754]
The link to http://liquidmarkup.org/ is in repository description at https://github.com/Shopify/liquid

**Comment by isaacrg** [comment]
Both URLS use 301(redirect: file moved permanently) to redirect to the other URL. This may well be a problem on Github's end(maybe linked to caching?).

**Comment by isaacrg** [comment]
Update: The custom url appears not to be handled by a Github-run server

**Comment by zeljkofilipin** [comment]
http://liquidmarkup.org/ now redirects to https://shopify.github.io/liquid/
