### ISSUE TITLE
shop.locale to return locale in language_TERRITORY format

### ISSUE THREAD

**Issue by kasrakhosravi** [Shopify/liquid#758]
I came across few situations that I needed the current shop locale in `language_TERRITORY` format. So right now `{{ shop.locale }}` returns the `locale` with `language` format but for use cases such as `Open Graph Meta Tags` they need the `locale` to be in `language_TERRITORY` format.

For instance instead of returning `en`, Open Graph meta tag needs `en_US` or `en_GB` format.

Using `language_TERRITORY` seems more common. I came across the exact implementation in `Sylius` project which is an ecommerce solution designed upon Symfony2 framework.

Do you think this is a valid need and if yes what is the best way to approach to change the format (considering that it might affect other section of framework)?

**Comment by fw42** [comment]
I don't think this is a Liquid question. Sounds more like a Shopify question. This repository is for issues related to the Liquid Ruby gem.

**Comment by jameshall-gh** [comment]
@kasrakhosravi 

Did you find a way of achieving this?
