### ISSUE TITLE
Is it possible to split currency icon and price apart for product.price?

### ISSUE THREAD

**Issue by spring-91** [Shopify/liquid#768]
I'm developing a store design and for the product price the designer would like the currency icon (£, $ etc) to be situated on the line above the actual product price, so displayed like this for example:

£
2000

_and not_

£2000

I'm unsure of any way to break apart the money filter so that I can position the £ above the number. There is a currency converter in play with this store so I'm unable to simply place the currency icon in statically. 

Does anyone have a solution where this would be possible? Many thanks

**Comment by pushrax** [comment]
Try using `slice`.

```rb
tpl = "{% assign x = '£2000' %}{{ x | slice: 0, 1 }}\n{{ x | slice: 1, 10 }}"
puts Liquid::Template.parse(tpl).render
```
