### ISSUE TITLE
comment conditional issue

### ISSUE THREAD

**Issue by reggi** [Shopify/liquid#775]
The compile code won't compile which is super odd.

```
{% assign test = true %}

{% if test %} {% comment %} {% endif %}

{% if test %} {% endcomment %} {% endif %}
```

**Comment by fw42** [comment]
This is invalid syntax, you can't "nest" tags like this, i.e. you can't close the `if` tag while the `comment` tag is still open. I'd say that's intentionally and the expected behaviour.
