### ISSUE TITLE
Shopify Payment Option

### ISSUE THREAD

**Issue by AfricanProgrammer** [Shopify/liquid#776]
Hi.I would like to add a payment option which is a customized option.The user will be asked to select between six payment instllaments options.After selecting the a certain amount of money will be deducted from the cart inline with the option they have selected.(Exmple Product Costs 800usd User selects 3 Months Layby = Price*1.05/3).Similar function to laybuy.How best can create such a function?Should use ruby or i can add the code on the shop?Please help

**Comment by fw42** [comment]
This doesn't sound like a question about the Liquid Ruby gem to me, more like a Shopify question maybe?
