### ISSUE TITLE
elsif control flow tag.

### ISSUE THREAD

**Issue by NourDT** [Shopify/liquid#782]
So this may sound dull and pointless, but I can't seem to figure out why it was decided to implement this as "elsif" and not as "elseif" 

I've been working with liquid on a daily basis for the past 4 months. and I get this one wrong EVERY time I write an else if statement. 

by all means, ignore this if it's just me having this issue. 

thanks!

**Comment by mouhannad-sh** [comment]
I agree, first time I used liquid, I spend 30 minutes debugging my code, without a single clue to why my elseif isn't working.

Once I found about "elsif" I felt like Liquid developers thought of the perfect way to troll short tempered devs and came up with "elsif"...

http://i597.photobucket.com/albums/tt55/brewsben8/Evil/mr_burns.gif

**Comment by admhlt** [comment]
Liquid is written in Ruby, which uses `elsif`. In a lot of ways, Liquid simply implements things the way Ruby does.

I think, that said, this isn't a Liquid issue, as Liquid is just inheriting its language from Ruby and will likely continue to follow that pattern.
