### ISSUE TITLE
Whitespace added to include

### ISSUE THREAD

**Issue by baberuth22** [Shopify/liquid#783]
My include file automatically gets a whitespace character added onto the end.   I am using the value of the include as a variable and find it tedious to have to assign the result to a new variable and strip it.

For example, I have the following include file shortcode-test.liquid:

`testout`

Then I have a page page.test.liquid:

`--{% include 'shortcode-test' %}--`

And the output is

`--testout --`

I don't want to have to capture and strip every time because there might be 10 variables on the page and I am trying to keep code tight.  

```
{% capture handle %}{% include 'shortcode-test' %}{% endcapture -%}
{%assign realhandle = handle | strip %}
--{{realhandle}}--
```

**Comment by dylanahsmith** [comment]
I tried the following

```ruby
require 'liquid'

Liquid::Template.file_system = Liquid::LocalFileSystem.new(Dir.pwd)
File.write(Dir.pwd + "/_partial.liquid", "included")
puts Liquid::Template.parse("---{% include 'partial' %}---").render.inspect
```

which produced the output

```
"---included---"
```

so it doesn't seem like a liquid issue.

How are you using liquid?  Are you using it through Shopify, jekyll or using the gem directly?

I tried it on Shopify and was able to get the output `--testout--` as expected.

Also, please make sure you don't have a newline or spaces at the end of your shortcode-test.liquid file.  Note that I didn't find that Shopify's theme editor added any trailing spaces.
