### ISSUE TITLE
Filters page shows raw code for examples after 'floor'

### ISSUE THREAD

**Issue by admhlt** [Shopify/liquid#784]
For the filters 'join' and onward, the [aggregated list of filters](http://shopify.github.io/liquid/filters/) is showing raw tags and unhighlighted Liquid instead of nicely formatted examples.

This page isn't super findable, so it's not terrible but it should be fixed. Maybe there's a stray `raw` tag somewhere.

**Comment by kainjow** [comment]
I built the site locally and was able to reproduce using Jekyll 3.1.6 and then updated to 3.3 and still reproduced. I removed all but the "url_encode" files from the "filters" directory, yet the issue still persisted. I noticed filters such as "abs" worked fine, the tags would parse. I then renamed "url_encode" to "encode" and now it parses.

I'm throughly confused.

**Comment by admhlt** [comment]
The broken page was removed by #820.
