### ISSUE TITLE
confused how passing objects is supposed to work.

### ISSUE THREAD

**Issue by twillis** [Shopify/liquid#794]
based on the introduction in the docs and the readme for this repo, I would expect this to work, but it doesn't.

```
[1] pry(main)> class OpenStruct
[1] pry(main)* def to_liquid
[1] pry(main)* self
[1] pry(main)* end
[1] pry(main)* end
=> :to_liquid
[2] pry(main)> Liquid::Template.parse("hello {{person.name}}").render("person" => OpenStruct.new(name: "tom"))
=> "hello "
[3] pry(main)> 
```

What am I missing?

**Comment by twillis** [comment]
so the docs aren't clear on this, but only hash with strings as keys can be used, not objects. the intro could be clearer.

**Comment by fw42** [comment]
You could use something like this:
```ruby
class OpenStruct
  def to_liquid
    Hash[to_h.map{ |key, value| [ key.to_s, value ] }]
  end
end
```
Kinda hacky, but works.

**Comment by fw42** [comment]
Also a bit hacky, but this works too:
```ruby
class OpenStruct
  def key?(key)
    to_h.key?(key.to_sym)
  end

  def to_liquid
    self
  end
end
```
Liquid expects those objects to have a "hash-like interface".

The intended way to do this is to just use a Liquid::Drop subclass though.

**Comment by twillis** [comment]
hey thanks for the feedback. I saw the Liquid::Drop stuff on the wiki but I didnt understand them fully. Maybe I'll play around with them today.
