### ISSUE TITLE
Failure: Tag 'translate_file' or 'tf' is not a recognized Liquid tag (on GitHub pages)

### ISSUE THREAD

**Issue by rpaweb** [Shopify/liquid#800]
I edited my personal site (made with Jekyll) for include multi-language option. Locally, works fine. But when I push on GitHub, the page isn't running well and answer me the error line: "Failure: Tag 'translate_file' is not a recognized Liquid tag". I try many things but nothing works yet.

> The line: `{% translate_file about.md %}`

**Comment by fw42** [comment]
That doesn't sound like a Liquid issue to me. @parkr?

**Comment by parkr** [comment]
@rpaweb Sounds like you're trying to use a plugin on GitHub Pages which isn't supported. This Help article describes what you can use: https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
