### ISSUE TITLE
How to add external Json as variables to shopify

### ISSUE THREAD

**Issue by isaacrajaei** [Shopify/liquid#802]
In my online shop I want to show some more data about each product. I have managed to do this by adding an extra nodes to `settings_data.json` file. Like this:

```
{
  "current": {
    ...
    ...
    "7887193478": {    //Product ID
        "has-badge" => true,
        "show-image" => false
        ...
    },
    "7887193479": {    //Product ID
        "has-badge" => true,
        "show-image" => true
        ...
    },
  }
}
```

It is working and I am getting the data and showing it successfully. 

> The good thing about this solution is the page load is very fast.

But the problem is when some one updates the theme setting it overrides the `settings_data.json` file. Is there any way that I can import this extra json settings separably into my Shopify?

> **Please do not advise me with Metadata App. Metadata app is very slow and I am not interested to use it.**

http://stackoverflow.com/questions/39406923/how-to-add-extra-json-settings-to-shopify

**Comment by pushrax** [comment]
This isn't related to Liquid itself, if you are still interested in an answer try Shopify's theme support.
