### ISSUE TITLE
Open tag `{%-` for whitespace control doesn't work properly

### ISSUE THREAD

**Issue by MaksimBazarov** [Shopify/liquid#807]
`{%- include 'parameters' -%}` 
throws the error:
```
block.rb:41:in `parse': Liquid syntax error: Tag '{%- include 'parameters' -%}' was not properly terminated with regexp: /\%\}/ (Liquid::SyntaxError)
```

meanwile `{% include 'parameters' -%}` works fine

**Comment by fw42** [comment]
what version of Liquid are you on?

**Comment by MaksimBazarov** [comment]
@fw42 liquid-3.0.6

**Comment by fw42** [comment]
Whitespace control tags were added in Liquid 4 and are not available in version 3.

**Comment by etolstoy** [comment]
@fw42 Thanks for the quick answer! Do you have any roadmap or approximate date of 4.0 stable release?

**Comment by simonc** [comment]
A warning in the documentation would be welcome then.

The current documentation presents whitespace-control as an existing feature but it's not in a stable release yet 😕 it should either be absent or maked as "since v4" 😉
