### ISSUE TITLE
Unprocessed filters in documentation

### ISSUE THREAD

**Issue by noscript** [Shopify/liquid#811]
Scroll to the end on https://shopify.github.io/liquid/filters/ and see:
```
Input
{% raw %}
{{ "john@liquid.com" | url_encode }}
{% endraw %}

Output
{{ "john@liquid.com" | url_encode }}

Input
{% raw %}
{{ "Tetsuro Takara" | url_encode }}
{% endraw %}

Output
{{ "Tetsuro Takara" | url_encode }}
```
Output is same as input.

Then go the the filter sub page https://shopify.github.io/liquid/filters/url_encode/:
```
Input
{{ "john@liquid.com" | url_encode }}

Output
john%40liquid.com

Input
{{ "Tetsuro Takara" | url_encode }}

Output
Tetsuro+Takara
```

**Comment by admhlt** [comment]
Already reported here: https://github.com/Shopify/liquid/issues/784

Thanks for noticing, though. If you can figure out what's going on, we'd happily accept a PR to fix that page.

**Comment by noscript** [comment]
#815 PR submitted, any feedback?

**Comment by kainjow** [comment]
@noscript take a look at my comment at #784, something weird is going on. Also I would recommend commenting your code. If it does get accepted, and then someone looks at this code later on, it'll be quite confusing as to why it's doing what it's doing.
