### ISSUE TITLE
pluralize filter does not exist

### ISSUE THREAD

**Issue by nladd** [Shopify/liquid#814]
I couldn't get the pluralize filter to work for me and searching the code I couldn't find any implementation for that filter. I worked around it using an if-else, but either it should be removed from the wiki docs or the filter should be implemented as documented.

**Comment by pushrax** [comment]
`pluralize` indeed doesn't exist in Liquid, just in Shopify (since it uses ActiveSupport). I deleted it from the wiki, since that's just supposed to be for core liquid.

**Comment by nladd** [comment]
Thanks!
