### ISSUE TITLE
LIQUID WITH CARRIERWAVE

### ISSUE THREAD

**Issue by lethunder** [Shopify/liquid#816]
Hello everyone,
i'm using rails 5 with liquid 3.0.6 and liquid-rails 0.1.3
i'm trying to render a template in which i included a picture field (carrierwave).
I have an error "Liquid error: undefined method `to_liquid' for #<PictureUploader:0xa91e2f0>"

My question is how to render an image inside template using carrierwave ?

Thanks in advance

**Comment by pushrax** [comment]
Either define `to_liquid` on `PictureUploader` and make it return whatever Liquid should output for instances of that class, or create a drop for it (https://github.com/Shopify/liquid/wiki/Introduction-to-Drops).
