### ISSUE TITLE
The roadmap for 4.0 release

### ISSUE THREAD

**Issue by etolstoy** [Shopify/liquid#818]
Hi! Do you have a roadmap for the next stable release, or at least an approximate release date? I'd like to use new features introduced in new versions but don't want to include non-stable dependency in my tool.

**Comment by fw42** [comment]
There's no roadmap.. I'm ok with releasing 4.0 as soon as @parkr is done with testing the 4.0 release candidate against the latest version of Jekyll.

**Comment by etolstoy** [comment]
@fw42 thanks! If there'll be any feature to implement for the next release - I can help with it.

**Comment by parkr** [comment]
Just waiting for CI in https://github.com/jekyll/jekyll/pull/4362. If that's all 🍏 , then a v4.0.0 release should be good to go. Thanks for the due diligence and sorry it took so long!

**Comment by admhlt** [comment]
v4.0.0 has been released. 🎆
