### ISSUE TITLE
link_to_remove_tag issue

### ISSUE THREAD

**Issue by chollimee** [Shopify/liquid#824]
link_to_remove_tag works wrong way.

I have two tags 'Q36.5' and 'Clothes-Q36.5-New'

/collections/Q36.5+Clothes-Q36.5-New

When I use link_to_remove_tag with Q36.5, It removed all Q36.5 in the link.
I expected /collections/Clothes-Q36.5-New, but resulted /Clothes--New.

Unacceptable!

**Comment by chollimee** [comment]
also, Is it possible to add/remove multiple tags at once?

is there any link_to_remove_tags? or link_to_add_tags?

**Comment by fw42** [comment]
This is not an issue with the liquid Ruby gem (but rather an issue with Shopify's custom liquid filters).
