### ISSUE TITLE
Liquid::Template.register_filter(...) doesn't work if the filter has already been used

### ISSUE THREAD

**Issue by willlahr** [Shopify/liquid#825]
I've been using liquid and discovered that if a filter is used before the register_filter call is made then not only does the filter not work - as you would expect - but also adding that filter using register_filters does not work at any point after that.  As if liquid is remembering the filter does not exist and making it unavailable for registering ever again.  Here is an example - note that url_arg_prefix puts a question mark on the end of the string.

$irb
>require 'liquid'
>Liquid::Template.parse("{{'example' | url_arg_prefix }}").render
 => "example" 
> require './lib/taxi_liquid_filters.rb'
> Liquid::Template.register_filter(TaxiLiquidFilters)
=> #<Set: {"size",.....  "url_param_escape"}> 
> Liquid::Template.parse("{{'example' | url_arg_prefix }}").render
 => "example" 

Take 2 - this time register the filters first:

 > require 'liquid'
> require './lib/taxi_liquid_filters.rb'
 > Liquid::Template.register_filter(TaxiLiquidFilters)
 => #<Set: {"size" ..... "url_param_escape"}> 
> Liquid::Template.parse("{{'example' | url_arg_prefix }}").render
 => "example?"

**Comment by dylanahsmith** [comment]
Here is a full script that reproduces the problem

```ruby
require 'liquid'

module MyFilters
  def myfilter(arg)
    'filtered'
  end
end

source = "{{ 'input' | myfilter }}"
template = Liquid::Template.parse(source)
puts template.render!
Liquid::Template.register_filter(MyFilters)
template = Liquid::Template.parse(source)
puts template.render!
```

which outputs

```
input
input
```

instead of

```
input
filtered
```
