### ISSUE TITLE
How to use liquid with Sails.js

### ISSUE THREAD

**Issue by JeyKeu** [Shopify/liquid#827]
Liquid is listed as a supported template engine for **consolidate.js** but as soon as i installed it and updated the `engine`  property to `liquid` or `tinyliquid` in `config/views.js` and did  `sails lift` it give this error :

Could not find module: liquid in path node_modules

Whats the right way to use liquid with sails.js?

**Comment by fw42** [comment]
That seems like a question you should ask in the consolidate.js project. Liquid itself doesn't know anything about JavaScript.
