### ISSUE TITLE
Sure it's simple but I don't get it...

### ISSUE THREAD

**Issue by Animus2012** [Shopify/liquid#830]
I'm editing this code in Shopify. I want it to add a frozen surcharge to the basket when an item tagged as 'frozen' is added. It's a snippet for a gift wrapping option. It works if you check the box but I'm trying to remove the option and make it mandatory for all frozen tagged items.

Thank you.

https://github.com/Shopify/liquid/commit/8126969b444bf3882ce4c0b937169c0f8506b9a1

**Comment by admhlt** [comment]
Hi Animus, this repo is for code issues with the core Liquid library, and not Shopify issues. Please feel free to check the [themes section of the Shopify documentation](https://help.shopify.com/themes) or contact Shopify support.
