### ISSUE TITLE
Can't calculate a percentage because divided_by rounds

### ISSUE THREAD

**Issue by timwis** [Shopify/liquid#831]
Hey folks, I'm trying to calculate a percentage using liquid and, to my surprise, it seems to be a bit impossible :-/

```liquid
{{ 3470 | divided_by: 8441 | times: 100 | round }}
```
expected: `41`
actual: `0`

It seems to be caused by the fact that liquid's `divided_by` filter [rounds the result "for you"](https://help.shopify.com/themes/liquid/filters/math-filters#divided_by). I was surprised that this behaviour is default, especially given there's a `round` filter, but more surprised that I can't seem to find a way around it :O

Is there no way to calculate a percentage?

**Comment by ashmaroli** [comment]
## Temporary Workaround
*Posting this again here for relevance*

You can calculate percentage by multiplying first and dividing next:
```
{{ 3470 | times: 100 | divided_by: 8441 }}
```

**Comment by admhlt** [comment]
It may seem odd, but this is working as intended.

If you divided by an **integer**, the result is an integer. If you divide by a **float**, the result will be a float. So this works:

```
{{ 3470 | divided_by: 8441.0 | times: 100 }}
```

and returns `41.10887335623741`.

**Comment by timwis** [comment]
Interesting. Thanks for the clarification @admhlt. In that case, is there a way to convert an integer to a float? In the example I posted, I used numeric values for demonstration / test case purposes, but in my real world example, I'm using variables with integer values.

**Comment by admhlt** [comment]
The last section of the page I linked has a workaround for that. It's a bit ugly, but you can 'convert' a variable to a float by multiplying it by 1.0:

```
{% assign my_variable = 8841 %}

{% assign my_float = my_variable | times: 1.0 %}

{{ my_float }}
```

returns `8841.0`.

**Comment by ashmaroli** [comment]
Nice.. 
So, for this particular use-case, my workaround above can be modified to simply:
```
{{ 3470 | times: 100.0 | divided_by: 8441 }}
```

**Comment by timwis** [comment]
Oh, wow, I haven't seen that site before --  I was using the shopify.com docs and the "liquid for designers" wiki page -- this is far more helpful. Thanks.

Oh, while I'm at it, would it be worth proposing that `divide_by` not round, and that users simply pass the result to the `round` filter if they want to round?

**Comment by admhlt** [comment]
Think of that site as a replacement for the 'Liquid for Designers' page. I'd really like to get rid of that page at some point.

It would be hard to change a filter that's worked one way for years. Changing the way `divided_by` works would no doubt cause things to break in thousands of Shopify stores and Jekyll sites all over the place.

Besides, this is the way division works in Ruby, the language that Liquid is built with. In Ruby, the result you get from a division operation depends on the types of the numbers you put in. If you're dividing by an integer, you'll get an integer result.

Take a look [here](https://repl.it/EePv) where I've set up your original equation in Ruby. The result is the same as in Liquid — `0`.

**Comment by ashmaroli** [comment]
Though this particular case can be solved by:
```sh
{{ 3470 | times: 100.0 | divided_by: 8441 }}
# => 41.10887335623741
```
@admhlt will a PR implementing a dedicated filter for this welcome?
```sh
{{ 3470 | percent_of: 8441 }}
# => 41.10887335623741

{{ 3470 | percent_of: 8441 | round }}
# => 41

{{ 3470 | percent_of: 8441 | round: 2 }}
# => 41.11
```

**Comment by timwis** [comment]
Thanks @ashmaroli! In fact, you don't even need `.0` with your method -- `times: 100` works too

**Comment by ashmaroli** [comment]
You're welcome @timwis 
Yes both works. But multiplying by `100.0` gives you a percentage as a **float**
```
{{ 3470 | times: 100 | divided_by: 8441 }}
# => 41

{{ 3470 | times: 100.0 | divided_by: 8441 }}
# => 41.10887335623741
```
The percentage as float can additionally be further filtered using the *round* filter:
```
{{ 3470 | times: 100.0 | divided_by: 8441 | round }}
# => 41

{{ 3470 | times: 100.0 | divided_by: 8441 | round: 2 }}
# => 41.11
```

**Comment by admhlt** [comment]
@ashmaroli you're welcome to prepare a PR implementing that filter, but I can't speak with any authority on whether it'll get merged. I'm mostly just the documentation guy. :)
