### ISSUE TITLE
The tag set on line 213 in [...] is not a recognized Liquid tag

### ISSUE THREAD

**Issue by mirceaulinic** [Shopify/liquid#838]
Hi,

I am using Jekyll and raised the following error when posting:

```
The tag set on line 213 in _posts/2016-12-15-configuration-management.md is not a recognized Liquid tag. For more information, see https://help.github.com/articles/page-build-failed-unknown-tag-error.
```

The raw original document that triggered the error is: https://raw.githubusercontent.com/mirceaulinic/mirceaulinic.github.io/POST%232-FIX%233/_posts/2016-12-15-configuration-management.md

Please let me know what info you'd need to debug this.

Cheers,
Mircea

**Comment by fw42** [comment]
not sure about the line numbers, but this:
```
{% set router_vendor = grains.vendor -%}
```
is not valid Liquid. Did you mean `{% assign ... %}`?

**Comment by fw42** [comment]
you could try using the `{% raw %}` tag

**Comment by mirceaulinic** [comment]
Yes, that worked! I wrapped the whole Jinja stuff inside the raw tag.

Thanks very much @fw42!
