### ISSUE TITLE
Please document minus symbol usage {%- ... -%}

### ISSUE THREAD

**Issue by mariusa** [Shopify/liquid#841]
Recently, more and more themes are using an extra minus symbol, e.g.

>  {%- if product.price_min < product.compare_at_price_min -%}
>		<span class="sale"><strong>Sale</strong></span>
>  {%- endif -%}

Please document at
https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
what does the minus do.

Thanks

**Comment by fw42** [comment]
@admhlt

**Comment by admhlt** [comment]
Hi @mariusa!

The minus symbol, when added to a tag, lets you strip whitespace from the left or right sides of the output of that tag. You can find documentation on it here:

http://shopify.github.io/liquid/basics/whitespace/

Please consider the website linked above a full replacement of "Liquid for Designers". There should be no need to check that wiki page anymore.

**Comment by fw42** [comment]
we should probably delete the wiki if we consider it to be unnecessary and out of date?

**Comment by admhlt** [comment]
I can only be an authority on that "For Designers" page, but that should definitely go. What do you all think of getting rid of the other pages?

**Comment by kainjow** [comment]
The "Liquid for Programmers" page is useful. Maybe it could be moved to the main Liquid docs?
