### ISSUE TITLE
Comparation condition bug on type check

### ISSUE THREAD

**Issue by bogdan** [Shopify/liquid#842]
Reproduce:

``` ruby
t = Liquid::Template.parse("{% if a > b %} Yes {% endif %}")
t.render!({a: {}, b: 2}.with_indifferent_access)
```

It can be fixed by adding `TypeError` besides `::ArgumentError` to the rescue block.

**Comment by dylanahsmith** [comment]
I think `Liquid error: no implicit conversion of Fixnum into Hash` would be a confusing error message if we just used the error message from TypeError as is.

**Comment by maartenvg** [comment]
Seems like this is only failing for ruby versions 2.3 and higher. It fails to raise in 2.2 or 2.1 (and CI is testing against 2.1)

**Comment by dylanahsmith** [comment]
Looks like on ruby 2.2 `{} > 2` caused a NoMethodError but in ruby 2.3 it causes a `TypeError`.

This is also in contrast to `2 > {}` which causes an ArgumentError.

**Comment by maartenvg** [comment]
Yea, was playing around with that in https://github.com/Shopify/liquid/compare/fix-hash-comparison. Will need to rescue from a larger number or errors for compatibility.

**Comment by dylanahsmith** [comment]
We do a respond_to? check, which is why we don't have a problem on ruby 2.2

**Comment by dylanahsmith** [comment]
Also, we have a behaviour change where in ruby 2.2 we returned `nil` but now it is a liquid error, so maybe we should be returning `nil` in this case to fix broken templates from the ruby upgrade.
