### ISSUE TITLE
Liquid syntax error (Expected end_of_string but found id) when using reverse vs reversed

### ISSUE THREAD

**Issue by mrmanc** [Shopify/liquid#843]
Running Jekyll (v3.2.1 with Liquid v3.0.6) locally has been giving me this warning on some code I got from a template site years ago:

```
Liquid Warning: Liquid syntax error (line 2): Expected end_of_string but found id in "post in site.posts reverse" in blog/archives/index.html
```

The code at fault was this:

```liquid
{% for post in site.posts reverse %}
```

I’ve just worked out that the problem was that `reverse` does not work—it should be `reversed`. This may be a change to functionality since I don’t think I used to get this error. I have searched and verified that plenty of existing code exists out there using `reverse` instead of `reversed` (including fragments in issues in this repo!), but since there was no issue I could find with a resolution I wanted to leave a post behind for the next reader.

The syntax error in this case wasn’t particularly helpful—something indicating a missing keyword / filter might have been more useful. Alternatively something specific to highlight that `reverse` should be `reversed`.

**Comment by admhlt** [comment]
`reverse` is the correct name for the filter.

There are a few things happening here:

1.  To use a filter you need to prepend it with a pipe `|` character, so that line of Liquid should read:

    ```
    {% for post in site.posts | reverse %}
    ````

2.  Liquid might not be able to apply a filter within a `for` declaration (I'm not able to test right now). So you'll need to create the object to iterate through by applying the filter on another line, _then_ looping through it:

    ```
    {% assign reverse_posts = site.posts | reverse %}
    {% for post in reverse_posts %}
    ```

As this isn't a Liquid issue, I'm going to close it, but feel free to reply with more comments if you need more clarification.

**Comment by nickpearson** [comment]
I think @mrmanc was talking about the `reversed` flag of the `for` tag itself rather than the `reverse` filter. A usage example is shown on [line 26 of `for.rb`](https://github.com/Shopify/liquid/blob/ffb0ace30315bbcf3548a0383fab531452060ae8/lib/liquid/tags/for.rb#L26).

**Comment by fw42** [comment]
yea the flag is called "reversed", not "reverse" (and the usage without the pipe is correct)

**Comment by admhlt** [comment]
Whoops! Don't I feel sheepish now, then. My apologies @mrmanc. Here are the docs on the 'reversed' flag for `for`: http://shopify.github.io/liquid/tags/iteration/#reversed

**Comment by pushrax** [comment]
So the question is, have we supported "reverse" in the past and why have we dropped support if so. I'm on my phone so it is hard to check, but I bet it never worked but would not throw any error before (silently ignore).

**Comment by mrmanc** [comment]
@admhlt no need to apologise! I hadn’t disambiguated filters and flags in my head… I’m not familiar with the syntax.

I think the use of `reverse` as a filter and `reversed` as a flag has likely confused a number of people! In reply to @pushrax I’m fairly confident that this used to work—the first 70 pages of this search for `for posts in site.posts reverse` have examples, all of which I think come from blogs generated using [Octopress](https://github.com/imathis/octopress) (Jekyll framework). See the offending code in it’s [blog archives page](https://github.com/imathis/octopress/blob/5717a50f4e4964ea8423997d6456b04c653f0348/.themes/classic/source/blog/archives/index.html).

**Comment by pushrax** [comment]
Going back all the way to Liquid 2.0, `reverse` was not supported https://github.com/Shopify/liquid/blob/v2.0.0/lib/liquid/tags/for.rb. It never has been, and all those examples are wrong. The old regex parser ignored it. What changed is that we now have "strict mode" which uses a real parser instead of the regex parser. This no longer ignores trailing characters.

**Comment by mrmanc** [comment]
@pushrax ah, that makes sense… so it would work, but it would not be reversed as intended. Thanks for digging!

Would it be palatable to a note to the iteration docs at http://shopify.github.io/liquid/tags/iteration/#reversed to say something along the lines of “note the different spelling to the filter `reverse`”?

**Comment by pushrax** [comment]
That's a good idea.

**Comment by mrmanc** [comment]
@admhlt What do you thin? Would you like a PR for the docs to clarify this? If so let me know where the docs are as I couldn’t find them easily.

**Comment by admhlt** [comment]
I think that's a great idea. The docs are on the `gh-pages` branch of this repo: https://github.com/Shopify/liquid/tree/gh-pages

You're welcome to submit a PR if you like! I'd appreciate it.

**Comment by mrmanc** [comment]
Thanks everyone, and apologies for the double commits—actually made the same mistake in the original commit message and couldn’t bear not to correct it. 2017 is not a year year for spelling and grammar so far.
