### ISSUE TITLE
Variables with dynamic, interpolated dereferenced values

### ISSUE THREAD

**Issue by DaveJarvis** [Shopify/liquid#844]
## Replicate
Consider the following Markdown (e.g., `README.md`):

```
![Logo]($application.directory.images$/logo.png)
$application.title$
===
$application.description$
![Screenshot]($application.directory.images$/screenshot.png)
```

Along with the following standalone YAML file (_neither_ `_config.yaml` _nor_ document front matter):

```
application:
  title: Application
  directory:
    images: images
  description: $application.title$ is almost as amazing as Liquid.
```

Prior to the markdown (e.g., `README.md`) being displayed, some [recursive pre-parsing](http://www.yaml.org/YAML_for_ruby.html) and [substitution](https://github.com/timcowlishaw/aho_corasick) would help eliminate some duplication within the document.

## Expected Results

```
![Logo](images/logo.png)
Application
===
Application is almost as amazing as Liquid.
![Screenshot](images/screenshot.png)
```

## Actual Results

No substitution is preformed, so the `README.md` file is displayed as:

```
![Logo]($application.directory.images$/logo.png)
$application.title$
===
$application.description$
![Screenshot]($application.directory.images$/screenshot.png)
```

---

## Additional Details
Using YAML as a bridge between documentation and applications is a slick way to avoid duplication. Since the YAML file is machine-readable, it would be trivial for an application to read its name from the same YAML source as the documentation. Changing the app name would be a simple matter of updating a single YAML file, which simultaneously updates all references in the documentation.

This could be an option passed into Liquid to maintain backwards compatibility.

Using `_config.yaml` is insufficient here because of namespace clashes. There are a couple of options:

* Liquid can read all the Markdown files alongside `_config.yaml` and pass them through a pre-processor; or
* `_config.yaml` can specify the pre-processor file(s) to use against all, or specific, Markdown files.

The first is easier, the second is more flexible.

---
## Regarding Collections
Consider:

```
collections:
  my_collection:
    foo: bar
```

This would mean changing `$application.title$` to `$collections.my_collection.application.title$`; such a prefix wouldn't necessarily make sense in other contexts (external to Jekyll/Liquid), and would require a lot of effort to refactor variable names across many Markdown documents (and verify that the refactor was performed correctly).

Also, part of the problem is that the variables must be able to reference other variables, with a variable interpolator to extract the correct dereferenced value (see `$application.description$`, above). (Aside, this aspect often gets overlooked whenever I describe the problem.)

The collection attributes almost fits the bill, but has the stringent requirement of not being a standalone YAML file (i.e., must be part of Markdown front matter).

---

## Variable Name Delimiters
Another issue is that it should be possible to define the variable delimiters and separators, such as:

* `{{ application.title }}` -- `{{` and `}}` with a `.` separator;
* `$application.title$` -- `$` and `$` with a `.` separator; or
* optionally,  `` `r#x( v$application$title )` `` -- `` `r#x( v$`` and `` )` `` with a `$` separator, which would be useful for evaluating inline R statements, evaluated using [knitr](https://yihui.name/knitr/) or [RinRuby](https://sites.google.com/a/ddahl.org/rinruby-users/).

---

## Not a Template Language
What is being proposed is not another template language, but two related ideas.

First, variable substitution for arbitrary definitions using a dot-separated notation and recursive interpolation. Second, the ability to set a prefix and suffix delimiter used for finding and replacing variables with a [resolved value map](https://github.com/DaveJarvis/scrivenvar/blob/master/src/main/java/com/scrivenvar/definition/yaml/YamlParser.java#L185).

I've developed both of these in Java. The first is about [19 lines of code](https://bitbucket.org/djarvis/yamlp/src/master/src/main/java/com/whitemagicsoftware/yamlp/Main.java?fileviewer=file-view-default#Main.java-231). The second requires a kind of [variable decorator pattern](https://github.com/DaveJarvis/scrivenvar/tree/master/src/main/java/com/scrivenvar/decorators), which is also fairly trivial in terms of LoC (fewer than 50 lines).

Code that deals with variable substitution sometimes hard-codes variable delimiters in multiple places, which is a violation of DRY. Using a constants is better practice, but still violates DRY when those constants are referenced in multiple places, rather than being constructed dynamically using a factory pattern based on some arbitrary criteria (such as a file name extension).

**Comment by pushrax** [comment]
I can't quite figure out what you're getting at and how it's related to Liquid. As far as I can tell you are suggesting three things:

1. YAML definition of Liquid variables
2. YAML parsing with interpolated variables from the same file
3. Alternate syntax for Liquid interpolation (`$` instead of `{{`)

The first one is out of scope. If you need this, use an existing YAML parser and pass the resulting hash into Liquid.

The second idea would be cool but I believe is also out of scope. Implementing this would require making Liquid aware of YAML syntax. If you feel that such a feature should exist, try raising it with a YAML project.

These first two ideas seem like they would be appropriate for an application framework rather than the templating language itself.

The third idea would inevitably conflict with existing templates. We could consider making it configurable, but it makes the parser code more complicated.

**Comment by DaveJarvis** [comment]
> The second idea would be cool but I believe is also out of scope. Implementing this would require making Liquid aware of YAML syntax. If you feel that such a feature should exist, try raising it with a YAML project.

Could also be a generic "data source" with a [factory](https://github.com/nslocum/design-patterns-in-ruby/tree/master/factory) that creates the appropriate reader based on a filename extension. For example, `settings_schema.json` would invoke the JSON reader while `settings_schema.yaml` would instantiate the YAML reader. Same for TOML, XML, and so forth.

> The third idea would inevitably conflict with existing templates. We could consider making it configurable, but it makes the parser code more complicated.

If there's only one spot in the parser where `{{` and `}}` are referenced, then the code wouldn't be that much more complicated. A factory or kind of inverse decorator pattern would be trivial. If, however, there are multiple locations where the delimiters are referenced, that's probably a sign that the parser could use some refactoring, depending on whether it's a hand-built parser or generated using a  grammar. I'm guessing the former, because if it was the latter, it'd be trivial. ;-)

> I can't quite figure out what you're getting at and how it's related to Liquid.

Some background. I sent a note to GitHub staff asking if it was possible to use interpolated variables  from an external data source within Markdown. They said that it should be possible because they are using Jekyll and Liquid. I posted a similar feature request to the Jekyll team and they suggested I pass it along to the Liquid team.

Now you've suggested passing it along to a YAML team, when YAML really has nothing to do with the general idea. The variables could be defined in any file format; it's trivial to convert from one structured format to another.

**Comment by pushrax** [comment]
I am not familiar with how Jekyll works but can you not already interpolate into markdown files? And does it not already provide a way to define variables from file?

Liquid knows nothing about configuration files or anything of the like - it's a library that provides an API for interpolating the parameters to the render method into the template provided to the parse method. This repo contains the language implementation and not much more.

**Comment by DaveJarvis** [comment]
Looks like it's not possible with the current architecture.

It's really not that difficult to leverage the chain-of-command design pattern to give multiple processors the chance to parse a document before generating a final output document. A simple Aho-Corasick algorithm as one of the links in the processing chain could provide a mechanism to search and replace variables. This would then pass the document along to the next processor in the chain.
