### ISSUE TITLE
How to get at objects in drop

### ISSUE THREAD

**Issue by resistorsoftware** [Shopify/liquid#848]
I have a simple drop for an order. An order has many line items. Line items have a title and a name. 

So when I send the order drop an order, and ask for the line items in a Liquid for loop, my items are returned but I cannot access their values... eg:

    {% for item in order.line_items %}
        <p> Item {{ forloop.index}} ---  {{ item.title }} {{ item.name }}  {{ item['title'] }}  {{ item['name'] }}  </p>
    {% endfor %}

So this just outputs Item 1 --- and nothing else. 

If I dump out just {{ Item }} in the loop, I get the raw hash... oops.. not what I expected.

Item 1 --- {:title=>"Booze", :name=>"Booze"}

 I see my values as a hash... not exactly what I am looking for. What is the trick to having the objects in a drop also render as liquid? So that item.name or item.title would extract the key?

**Comment by dyspop** [comment]
I'm not sure what the data you're working on really looks like from your output but did you try
`{{ item[0] }}` and `{{ item[1] }}`?

You could get fancy and assign them if you're doing more stuff with them.

**Comment by resistorsoftware** [comment]
I fixed it... when I iterate items, it was complaining that ShopifyAPI::LineItem had no to_liquid. 

So I hacked module ShopifyAPI, module LineItem to have a to_liquid that simply instantiated an ItemDrop for me. That drop exposed the item fields... and voila... in my iterator now item.title dumped out it's text. 

Why that took me so long to figure out is beyond me... having a slow slow day it seems...

**Comment by forsbergplustwo** [comment]
Dave, if you want a more complete to_liquid implementation on the API, you can check out: https://github.com/forsbergplustwo/pixelprinter/blob/master/lib/extensions/shopify_api_ext.rb for inspiration.

It's from the old PixelPrinter app, from years ago but the concept is good. I have a more updated and complete version I could share via DM if it would be helpful.
