### ISSUE TITLE
NoMethodError: undefined method `line_number'

### ISSUE THREAD

**Issue by Apokly** [Shopify/liquid#853]
Hi,

While integrating unit tests to my project, I'm confronted to this error : 

`NoMethodError: undefined method line_number for "hi ":String`

I use README test :

```
@template = Liquid::Template.parse("hi {{name}}") # Parses and compiles the template
@template.render('name' => 'tobi')
```

I use liquid 4.0.0 and I use `Minitest::Test` and include Liquid into my tests. Rails version 4.2.5.1

Thank you.

**Comment by pushrax** [comment]
Can you include the backtrace?

**Comment by Apokly** [comment]
Hi @pushrax,

Here is the backtrace :
```
NoMethodError: undefined method `line_number' for "hi ":String
    /home/fabien/.rvm/gems/ruby-2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:99:in `rescue in block in render'
    /home/fabien/.rvm/gems/ruby-2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:79:in `block in render'
    /home/fabien/.rvm/gems/ruby-2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `each'
    /home/fabien/.rvm/gems/ruby-2.3.0/gems/liquid-4.0.0/lib/liquid/block_body.rb:75:in `render'
    /home/fabien/.rvm/gems/ruby-2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:208:in `block in render'
    /home/fabien/.rvm/gems/ruby-2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:242:in `with_profiling'
    /home/fabien/.rvm/gems/ruby-2.3.0/gems/liquid-4.0.0/lib/liquid/template.rb:207:in `render'
    /home/fabien/Workspace/boost-julie.fr/test/models/liquid_template_content_test.rb:14:in `test_generate_body_from_content'
```

**Comment by Apokly** [comment]
Any update / fix ?

**Comment by dylanahsmith** [comment]
Could you provide the error cause?  Since it looks like it is failing to render a string, which isn't something that I have ever seen happen.

If this is only happening in your tests, then it could be from mocks or stubs that are somehow causing liquid to fail to render a string node.  Either way, I guess we could check if the node is a string in this rescue block and not call line_number on it.

**Comment by Apokly** [comment]
The only way I succeed passing tests are by using only interpolated elements into my fixtures.
For example, fixture using :

`{{ last_name }}`

will pass, same for :

`{{ last_name | default 'LastName' }}`.

If I set my fixture with :

`{{ last_name }} ` (notice the space after last '}'), it fails, same for :

`Test{{ last_name }}`.

My only conclusion is that it fails if I set something else than a Liquid variable.
