### ISSUE TITLE
Split filter doesn't behave as I would expect?

### ISSUE THREAD

**Issue by jbsulli** [Shopify/liquid#862]
I am not sure if this is the right place to report this issue, but Shopify's [split filter](https://help.shopify.com/themes/liquid/filters/string-filters#split) seems to remove all null strings after the split.

```liquid
{{ "abcccc" | split:"c" | json}}
```

This liquid results in `["ab"]` and not the `["ab","","","",""]` that I would expect.

```liquid
{{ "abcccc" | split:"c" | size }}
```
This liquid prints `1`. So it's not the json filter.

**Comment by admhlt** [comment]
This is expected behaviour, as far as I can tell.

You get the same result with the `split` method on a string in Ruby.

**Comment by jbsulli** [comment]
That seems so wrong. Reading about it [here](http://ruby-doc.org/core-2.4.0/String.html#method-i-split), split seems straight up maddening. 

For my use case, this behavior will probably be OK. I had to add a separator and additional character to the end to force the correct length and just ignore the last value. 

Probably no way of passing a "limit" value to fix this? Looks like passing a negative value for the limit gets me close to what I would expect. Then there's just the null string returning an empty array that I wouldn't expect.

**Comment by dylanahsmith** [comment]
It just feels wrong for your use case.  The behaviour makes more sense for the case where you are splitting on separators between words, where you don't want empty words from multiple separators that are together.

**Comment by jbsulli** [comment]
Well... to be fair, I am doing something a little crazy. I wrote a snippet that takes html and splits it on tags. For example:
```html
<h1>Hello world!</h1><p>This is a test.</p>
```
Returns:
```json
["","Hello world!","<p>This is a test.</p>"]
```
So now I can do something like a page with that html (allowing the content editors to easily modify the html), and then throw it into a popup where the `h1` is used as the popup title and the rest of the content is in the body of the popup.

Another (probably better example) is using it for product tabs. So they can use `h3` to mark the different tabs. The headline content would go into the tab title and the content following would show when the tab is clicked on.

Gives me a lot of flexibility.

**Comment by pushrax** [comment]
I'm not a fan of how Ruby implements `split` either, but I don't think we will be changing this.
