### ISSUE TITLE
Liquid::UndefinedVariable error in include tag with strict_variables enabled

### ISSUE THREAD

**Issue by svoboda-jan** [Shopify/liquid#871]
Rendering a template with `strict_variables` enabled causes `Liquid::UndefinedVariable` error when using include tag without the `with` or `for` option.

```ruby
template_source = "{% include 'product-grid-item' %}"

Liquid::Template.file_system = Class.new do
  def read_template_file(template_path)
    "test #{template_path}"
  end
end.new

template = Liquid::Template.parse(template_source)

rendered_template = template.render({}, strict_variables: true)

#
# rendered_template.errors
#
# => [#<Liquid::UndefinedVariable: Liquid error: undefined variable product-grid-item>]
#
```

This is caused because the include tag tries to find a variable with the same name as the included template (in this case `product-grid-item`) if `with` or `for` isn't specified.

https://github.com/Shopify/liquid/blob/v4.0.0/lib/liquid/tags/include.rb#L53

**Comment by dylanahsmith** [comment]
Already reported in https://github.com/Shopify/liquid/issues/828
