### ISSUE TITLE
Add a for loop variable with another variable in Django Template

### ISSUE THREAD

**Issue by Dineshramk** [Shopify/liquid#873]
Model:
class Jan17(models.Model):
    id = models.TextField(primary_key=True)
    slno = models.TextField(db_column='SLNo')
    teammembers = models.TextField(db_column='TeamMembers')
    level = models.TextField(db_column='Level')
    skillset = models.TextField(db_column='Skillset')
    employeeid = models.TextField(db_column='EmployeeID')
    pridid = models.TextField(db_column='PridID')
    jan01 = models.TextField(db_column='Jan01')
    jan02 = models.TextField(db_column='Jan02')

Form:
{% for user in users %}
  <tr>
      <td>{{ user.teammembers }}</td>
      <td>{{ user.level }}</td>
      <td>{{ user.skillset }}</td>
      <td>{{ user.id }}</td>
      {% for dat in finaldatod %}
        <td>{{ user.dat }}</td>
      {% endfor %}
  </tr>
{% endfor %}

View:
def filter_users(request):
  form = UserlistForm(request.POST or None)
  users = None
  fromdate = None
  todate = None
  months = None
  finaldat = {}
  finaldatod = {}
  if request.method == 'POST':
    if form.is_valid():
        users = Jan17.objects.filter(Q(teammembers__contains=form.cleaned_data.get('teammembers')))
        fromdate = form.cleaned_data.get('fromdate')
        todate = form.cleaned_data.get('todate')
        months = form.cleaned_data.get('months')
        for dat in range(int(fromdate),int(todate)+1):
            if dat in [1,2,3,4,5,6,7,8,9]:
                findat = months + '0' + str(dat)
            else:
                findat = months+str(dat)
            finaldat[findat] = findat
        finaldatod = collections.OrderedDict(sorted(finaldat.items()))

return(render(request, 'useroutput.html', {'form': form, 'users': users, 'fromdate': fromdate, 'todate': todate, 'months': months, 'finaldatod': finaldatod}))

Template:
<form action="." enctype="application/x-www-form-urlencoded" method="post">
{{ form.as_ul }}
{% csrf_token %}
<button type="submit">Search</button>
{% if users %}
<table border="5">
    <tr>
    <th>TeamMember</th>
    <th>Level</th>
    <th>SkillSet</th>
    <th>PridID</th>
    {% for dat in finaldatod %}
    <th>{{ dat }}</th>
    {% endfor %}
    </tr>
    {% for user in users %}
    <tr>
        <td>{{ user.teammembers }}</td>
        <td>{{ user.level }}</td>
        <td>{{ user.skillset }}</td>
        <td>{{ user.pridid }}</td>
        <td>{{ user.jan01 }}</td>
        <td>{{ user.jan02 }}</td>
        {% for dat in finaldatod %}
        <td>{{ user.dat }}</td>
        {% endfor %}
    </tr>
    {% endfor %}
</table>
{% endif %}

Here users and dat are two dictionaries passed from my view.

users has all the users available in the database
dat has all the dates of the month
Now am able to fetch the username, skillset, level and id of all the users. But unable to fetch the shifts of the user for all the dates of the month.

Here {{  user.dat  }} is not working as its unable to substitute user value and dat value together.

Kindly advise how I can pass the values from first for loop to the second and get the data from the database.

Thanks in advance!!

**Comment by dylanahsmith** [comment]
> Django Template

Did you report this to the wrong project?  The project is for *ruby* implementation of the *liquid* template language.
