### ISSUE TITLE
Creating runtime variables using objects within the assign tag

### ISSUE THREAD

**Issue by robbiematthews** [Shopify/liquid#875]
I'm trying to create a runtime variable by using an object within the assign tag.

e.g. {% assign test_link = 'https://app.example.co&{{campaign.${name}}}' %}

This currently creates the variable test_link but does not template in the {{campaign.${name}}} save object. 

I've attempted to assign the object alone as a variable and then use the saved variable within the second variable but this also doesn't work.

Is this expected behaviour? If not are you able to help me with the method? Thanks in advance!

**Comment by fw42** [comment]
Yea this is on purpose. You can use the `capture` tag to achieve what you want.
