### ISSUE TITLE
Liquid used with DocFX

### ISSUE THREAD

**Issue by vverrastro** [Shopify/liquid#881]
Hi all,
I'm trying to use liquid to realize a custom template for DocFX website. At the moment I exported default template in a directory "template." It is not realized with Liquid but with mustache.

Can someone explain to me how to start the conversion of the existing template?

I read all these pages: https://shopify.github.io/liquid/
But I didn't found any tutorial for integrate liquid with my DocFX project.
Thanks

Vito

**Comment by pushrax** [comment]
DocFX is unaffiliated with Liquid, try checking their documentation https://dotnet.github.io/docfx/tutorial/intro_template.html#renderer-in-liquid-syntax.
