### ISSUE TITLE
How to make '{% xx %}' to just a text in liquid?

### ISSUE THREAD

**Issue by chenjian158978** [Shopify/liquid#882]
I build my blog  on Github Page with the tool of Jekyll. 

In Macdown, I add a HTML fragment using the type of \``` html xxxxx \``` like below. 
There is a special code in the HTML, where was marked by **RED pane**.

<img width="1270" alt="wx20170420-134846 2x" src="https://cloud.githubusercontent.com/assets/15992345/25215581/0e682516-25d1-11e7-85aa-a50205e17213.png">

After running `jekyll serve --watch`, I got a **Liquid Exception: Liquid syntax error** like below.

<img width="626" alt="wx20170420-135218 2x" src="https://cloud.githubusercontent.com/assets/15992345/25215768/fe4b9f54-25d1-11e7-94ce-b96f4f42c7a8.png">

I am not using liguid in my HTML fragment, just adding a piece text of HTML.

How to make '{% xx %}' to just a text in liquid?

**Comment by iamunknown2** [comment]
Put your tags between {% raw %} and {% endraw %} for them to not be interpreted as Liquid tags.

**Comment by chenjian158978** [comment]
@iamunknown2 That is cool, thanks a lot!

**Comment by 1step2hell** [comment]
Hi @admhlt ,I had a problem, how could I make the whole string "{% raw %} {{some-text}} {% endraw %}" showing as raw text?
You may wonder why there are people do this weird stuff, Yeah I did, actually I want to record this issue in markdown file. So I need show the whole string "{% raw %} {% include file.ext %} {% endraw %}" as raw text. But the first "{% endraw %}" always match to the "{% raw %}", can't find a way to make itself as raw text.
Thanks

**Comment by admhlt** [comment]
Hi @1step2hell,

This is indeed quite a tricky thing to do, but I've had to solve this problem before as well.

One solution is to use HTML entities (like `&#123;`) to replace the Liquid tag characters `{`, `}`, and `%`. It's not a pretty solution, but it works.

I've created an example for you to look at in this [DropPen](https://droppen.org/?droppen=aprjspb).

**Comment by 1step2hell** [comment]
Done! @admhlt thank you.
You remind me of this <https://daringfireball.net/projects/markdown/syntax#autoescape>
