### ISSUE TITLE
Drop ruby 2.0 support

### ISSUE THREAD

**Issue by StevenWatremez** [Shopify/liquid#885]
On commit `9dd0801f5c42b1457294023f1b52e76a8764120c` you dropped ruby 2.0 support. I am using your gem to improve our data model generator (**gyro: https://github.com/NijiDigital/gyro**), but inside my team everyone work on MacBookPro with macOS Sierra. And inside Sierra ruby is basically installed in `2.0.0`. How can I use your gem in my case? I want to stay in touch about your futur improvements.

**Note :** to keep my gem simple, unfortunately I can't ask to everyone to manage ruby version.

Thanks, and sorry for my english.

**Comment by djjimba** [comment]
changing ruby version on a macOS is simple with tools like RVM.
https://rvm.io/rvm/basics

**Comment by pushrax** [comment]
Can you believe that ruby 2.1 was released in 2013? Seems like just yesterday.

Anyway, your options are to use Liquid 3, or the unreleased Liquid 4 before Ruby 2.0 was dropped, or install a more recent Ruby. If you are using Homebrew, it's as easy as `brew install ruby`.

**Comment by StefanoCecere** [comment]
this is huge question now that 3.5.0 has been released and tons of developers are on macOS + Ruby 2.0.0

i guess we should put big in the releases notes: macOS users please update to Ruby >2.1 with https://rvm.io/rvm/basics
