### ISSUE TITLE
format_address filter incorrectly escaping characters

### ISSUE THREAD

**Issue by gina-gregory** [Shopify/liquid#887]
It seems the format_address filter is doing some sort of weird double escaping where it escapes the ampersand in HTML entities so it is rendered not as HTML but as plain text. 

An apostrophe is output as ```&amp;#39;```
A quote is output as ```&amp;quot;```
An ampersand is output as ```&amp;&amp;```

**Comment by Thibaut** [comment]
This was fixed in Shopify a few weeks ago.
