### ISSUE TITLE
Error in docs

### ISSUE THREAD

**Issue by InquisitiveDevelopment** [Shopify/liquid#889]
I wasn't able to find a location to submit this IN the docs so I'm submitting it here.

https://shopify.github.io/liquid/basics/types/

When looking at the "types" page you say there are six types that liquid supports, but you only specify five in the docs.

**Comment by Shashwat986** [comment]
I was looking at this issue. I think it's already been fixed. If it isn't, can someone point me to the point where the docs are incorrect? I'll be glad to help out if help is required.

**Comment by adamhollett** [comment]
Looks like this has been resolved.
