### ISSUE TITLE
How do I check if a variable is defined?

### ISSUE THREAD

**Issue by casey-chow** [Shopify/liquid#89]
Say (in Jekyll, for example) I want to check if a certain variable, say `header_image` was defined and do something if it is, and something else if it isn't. How would I do that?

**Comment by dvdsgl** [comment]
What if the possibly undefined variable is a boolean, and you want to run the block if it's `true` or `false`, but not if it's undefined?

**Comment by fw42** [comment]
then you can use ```{% if header_image == true or header_image == false %}```

**Comment by bristoljon** [comment]
What about negating this check?

In my case the variable `row.image` may or may not be defined. If it is I want to show an `<img>` tag but hide a different background `<div>`.

Although `{% if row.image %} works as expected, the only way I've found to negate it is:

```
{% if row.image %}
{% else %}
  <div>...</div>
{% endif %}
```
Is there a more succinct form e.g. `{% if !row.image %}`?

**Comment by fw42** [comment]
There is an `unless` tag

**Comment by dyspop** [comment]
the unless tag is the inverse of the if tag and sounds like it will work for you

**Comment by bristoljon** [comment]
Thanks @fw42 and @dyspop, that's exactly what I was looking for and it was in the docs right below `if`!

**Comment by anetacamo** [comment]
But if I want to check for a condition OR if the variable is not defined at all
lets say something like this
<pre>
<code>
{% if row.number == 0 or !column.number  %}
something is missing
{% else %}
for loop
{% endif %}
</code>
</pre>
I would prefer to write it in as few statements as possible because the code else if is large

**Comment by steinbachr** [comment]
For anyone who stumbles here and - like me - was looking for this check in the context of a Jekyll list filter (e.g. `where_exp`), I was able to eventually get it with `where_exp: "item", "item.header_image != nil"`. 

Unfortunately, it's pretty unclear from the language documentation what the difference between `empty`, `nil`, and `blank` is, so required some trial and error to get working.

**Comment by Ynjxsjmh** [comment]
> {% if row.number == 0 or !column.number  %}
> something is missing
> {% else %}
> for loop
> {% endif %}

I do this by

```
{% if page.type == "asciidoc" %}
  {% include article/asciidoc.html %}
{% elsif page.type == "readtheorg" %}
  {% include article/readtheorg.html %}
{% elsif page.type == "markdown" or page.type == "" or page.type == nil %}
  {% include article/markdown.html %}
{% else %}
  "Post type invalid, your type is {{page.type}}, which is not a valid type."
{% endif %}
```

I think `page.type == ""` can check if `type` varaible is defined in page. If true, type is not defined.
