### ISSUE TITLE
Why can't Shopify's Liquid handle device detection?

### ISSUE THREAD

**Issue by ConduciveMammal** [Shopify/liquid#893]
I've been wondering for a long while why Shopify's Liquid can't handle device detection?

Something like
`{% if user.device = phone %}`
         ` I am a mobile`
      `{% endif %}`

Given an "it's not possible" would be believable, except Adobe's Business Catalyst, which is built on Shopify's Liquid, has supported it for six years.
[Source](http://www.businesscatalyst.com/bc-blog/introducing_tablet_phone_support_for_sites)

Can this please be implemented? It's the bane of many developers lives having to hide and unhide elements based on device type. Especially when element IDs start getting duplicated.

**Comment by pushrax** [comment]
Liquid itself is just a template renderer, and doesn't know about HTTP requests – this feature suggestion would be better made on Shopify's forums as there is no change to Liquid itself that could address it.

To answer your question though, within Shopify, Liquid templates are heavily cached, so request-dependent variables are kept to a minimum. Each variable that can change based on the request requires segmenting the cache, leading to combinatorial problems. Most theme developers these days use CSS features for responsive design these days anyway, so there is not a lot of demand for this feature.
