### ISSUE TITLE
`concat` filter appears to be missing from website

### ISSUE THREAD

**Issue by adamvoss** [Shopify/liquid#902]
**concat** does not appear in the side bar and the presumed URL (https://shopify.github.io/liquid/filters/concat/) returns as 404.

**Comment by kainjow** [comment]
Fixed with #872

**Comment by kainjow** [comment]
Looks like there's no docs for it at all: https://github.com/Shopify/liquid/tree/gh-pages/filters

**Comment by oncletom** [comment]
#906 has been merged so I guess this issue can be closed now 🙂

**Comment by adamhollett** [comment]
Ah, thanks, @oncletom. I thought this would close automatically but I guess it didn't.

**Comment by oncletom** [comment]
@adamhollett ah I see! I have been fooled multiple times by this behaviour too—the `fixes #<issue>` closes the issue when the PR is merged onto the _default branch_; `master` I guess. PR targetting `gh-pages`(as #906 does) would not 😢
