### ISSUE TITLE
before_method not invokving while rendering template

### ISSUE THREAD

**Issue by ajays1991** [Shopify/liquid#907]
Hi,

I have following Drop for a activerecord object.

```
# frozen_string_literal: true
module O3::Drop
  class LeadDrop < Liquid::Drop

    def before_method(method)
      byebug
    end

    def initialize(lead)
      byebug
      @lead = lead
    end

    def name
      byebug
      @lead.name
    end
  end
end

```

Following is how i build from liquid template and liquid drop.

```
      lead_drop = O3::Drop::LeadDrop.new(lead)
      result = Liquid::Template.parse(liquid_template.template)
      result.render('lead' => lead_drop)
```
My `Gemfile.lock` is freezed at 4.0 for liquid.
`before_method` is never invoked. pls share some working example for same.

Thanks.

**Comment by dylanahsmith** [comment]
Please read History.md for list of breaking changes on major releases

> * Rename Drop method `before_method` to `liquid_method_missing` (#661)

**Comment by ajays1991** [comment]
Thanks. i was looking at source code to catch `Underivable type` exception to implement a workaround.

Made my day easy.
