### ISSUE TITLE
Bug with error_mode

### ISSUE THREAD

**Issue by isavita** [Shopify/liquid#908]
When I try to set **error_mode** to **:strict** as follows
```ruby
template = Liquid::Template.parse("My great text message {{a.b}} {{a}}", error_mode: :strict)
```
and try to render expecting to see errors for **undefined variable a**
```ruby
template.render({ 'b' => 4}, {strict_variables: true})
template.errors # => []
```
The **template.errors** returns **empty Array**
I found work around by firstly setting the error_mode to nil
```ruby
Liquid::Template.error_mode = nil
template = Liquid::Template.parse("My great text message {{a.b}} {{a}}", error_mode: :strict)
```
Then the error message was correct.
```ruby
template.render({ 'b' => 4}, {strict_variables: true})
template.errors
=> [#<Liquid::UndefinedVariable: Liquid error: undefined variable a>, #<Liquid::UndefinedVariable: Liquid error: undefined variable a>]
```

**Comment by dylanahsmith** [comment]
I tried running the script

```ruby
require 'liquid'
template = Liquid::Template.parse("My great text message {{a.b}} {{a}}", error_mode: :strict)
template.render({ 'b' => 4}, {strict_variables: true})
puts template.errors.inspect
```

on master and version 4.0.0 and both output

```
[#<Liquid::UndefinedVariable: Liquid error: undefined variable a>, #<Liquid::UndefinedVariable: Liquid error: undefined variable a>]
```

and older version of liquid don't support the `:strict_variables` option.  So more information is needed to reproduce this issue.

**Comment by isavita** [comment]
It might be something with my rails loading setting. I tried it on clean project and it was working. You can close the issue. Thanks!
