### ISSUE TITLE
Raise syntax error when unclosed objects/variables precede closed objects.

### ISSUE THREAD

**Issue by wobh** [Shopify/liquid#910]
Earlier this week, I noticed that if I didn't close an object, the template parser was satisfied if there was another complete object later in the template. Here's a parsed and rendered example:

```
irb(main):003:0> Liquid::Template.parse('<img src="{{ url" alt="{{ text }}">').render
=> "<img src=\"\">"
```

I was sort of lucky in that this caused an obvious problem for me. But it seems unlikely to me that it would always, or even usually, do so for others. It seems to me that I should get a syntax error, which is what I get if I switch it up a bit:

```
irb(main):004:0> Liquid::Template.parse('<img src="{{ url }}" alt="{{ text ">').render
Liquid::SyntaxError: Liquid syntax error: Variable '{{' was not properly terminated with regexp: /\}\}/
```

I can add a failing test:

```
diff --git a/test/integration/parsing_quirks_test.rb b/test/integration/parsing_quirks_test.rb
index 23742dc..5a8a18b 100644
--- a/test/integration/parsing_quirks_test.rb
+++ b/test/integration/parsing_quirks_test.rb
@@ -20,6 +20,12 @@ class ParsingQuirksTest < Minitest::Test
     end
   end

+  def test_raise_on_labels_with_mismatched_bracets
+    assert_raises(SyntaxError) do
+      Template.parse("TEST {{ this {{ that }}")
+    end
+  end
+
   def test_raise_on_label_and_no_close_bracets_percent
     assert_raises(SyntaxError) do
       Template.parse("TEST {% ")
```

I've looked into `Liquid::BlockBody` and it seems like somewhere after line 38 is where the fix should go, but that's as far as I thought I should go before bringing this up here.

Somewhat tangentially, Is Liquid's grammar formally specified, somewhere? A casual search through the docs didn't turn anything up.

Thank you!

**Comment by pushrax** [comment]
For proper syntax errors, make sure to use strict mode https://github.com/Shopify/liquid#error-modes

```
irb(main):002:0> Liquid::Template.parse('<img src="{{ url" alt="{{ text }}">', error_mode: :strict).render
Liquid::SyntaxError: Liquid syntax error: Unexpected character { in "{{ url" alt="{{ text }}"
```

Liquid's grammar is not yet formally specified. I started working on it a year or two ago but didn't find the time to complete it.

**Comment by wobh** [comment]
Thanks! I didn't know about the strict mode.
