### ISSUE TITLE
No Exception with .render! and strict_variables: true

### ISSUE THREAD

**Issue by natschz** [Shopify/liquid#913]
In the readme it says:

`template = Liquid::Template.parse("{{x}} {{y}}")`
`template.render!({ 'x' => 1}, { strict_variables: true })`
`#=> Liquid::UndefinedVariable: Liquid error: undefined variable y`

But I do not get an exception.

Am I missing something or is this a bug? Also is there a workaround?

**Comment by dylanahsmith** [comment]
What version of liquid are you using?  Since I get the Liquid::UndefinedVariable exception on master and v4.0.0.

**Comment by natschz** [comment]
We had version 3 installed and now upgraded to version 4, now it runs fine.

Thank you very much!
