### ISSUE TITLE
Liquid Warning: Expected dotdot but found pipe

### ISSUE THREAD

**Issue by edap** [Shopify/liquid#917]
I've got this warning "Liquid Warning: Liquid syntax error (line 11): Expected dotdot but found pipe in "{{(site.github.public_repositories | sort: 'stargazers_count') reverse }}" in tools.html"

And this is the snippet generating this error

```html
  {% assign selected = "repo1,repo2,repo3" | split: "," %}
  {% assign sorted = (site.github.public_repositories | sort: 'stargazers_count') | reverse %}
  {% for repository in sorted  %}
    {% if selected contains repository.name %}
        {% include card.html repoName=repository.name  gridClass = "grid" %}
    {% endif %}
  {% endfor %}
```

I've tried to substiute the offending line with:

`{% assign sorted = (site.github.public_repositories sort: 'stargazers_count') reverse %}`

or

`{% assign sorted = (site.github.public_repositories sort: 'stargazers_count') | reverse %}`

or

`{% assign sorted = (site.github.public_repositories | sort: 'stargazers_count') reverse %}`

but the result does not change. What am I doing wrong?

**Comment by kainjow** [comment]
IIRC, I don't think parentheses can be used in Liquid. Did you try this?

    site.github.public_repositories | sort: 'stargazers_count' | reverse

**Comment by edap** [comment]
it works, thanks @kainjow ;)
