### ISSUE TITLE
Liquid gets confused when a Drop is both a Drop and a String.

### ISSUE THREAD

**Issue by envygeeks** [Shopify/liquid#918]
## Drop Source

```ruby
module Liquid
  class Drop
    class Str < String
      attr_writer :context

      # --
      # Mocks `#is_a?` so that Liquid thinks we are a
      #   drop. If it ever decides to ask.
      # --
      def is_a?(v)
        v == Liquid::Drop || super(v)
      end

      # --
      # Liquid version of `method_missing`, except it only
      #   works for Liquid and only takes the method.
      # @return Error.
      # --
      def liquid_method_missing(method)
        return nil unless @context && @context.strict_variables
        raise Liquid::UndefinedDropMethod, \
          "undefined method #{method}"
      end


      # --
      # Invokes a method on the drop if it exist and is
      #   not blacklisted.  We blacklist most methods by
      #   default if it's on `String`, `Array`, `Enumberable`
      #   `Hash` and this own class...
      # --
      def invoke_drop(m)
        self.class.invokable?(m) ? send(m) : liquid_method_missing(m)
      end

      # --
      def to_liquid
        self
      end

      # --
      # This is `.invokable?` when it comes to Liquids own
      #   source.  We change it to discourage users from overriding
      #   the methods because this is a wrapper.
      # --
      def self.invokable?(m)
        invokable_methods.include?(m.to_s)
      end

      # --
      def self.invokable_methods
        @invokable_methods ||= begin
          Set.new(good.map(&:to_s))
        end
      end

      private
      def self.bad
        @bad ||= begin bad = []
          bad = bad |       Drop.public_instance_methods
          bad = bad |      Array.public_instance_methods
          bad = bad | Enumerable.public_instance_methods
          bad = bad |     String.public_instance_methods
          bad = bad |       Hash.public_instance_methods
        end
      end

      private
      def self.good
        @good ||= [:to_liquid] | (
          public_instance_methods - bad
        )
      end

      # --

      alias_method :===, :is_a?
      alias_method :[], :invoke_drop
    end
  end
end
```

```ruby
module EnvyGeeks
  module Drops
    class Tag < Liquid::Drop::Str
      attr_reader :weight, :site
      extend Forwardable::Extended
      rb_delegate :name, to: :@tag, alias_of: :to_s
      include Helpers::Tag

      # --
      def initialize(tag, site:, weight: 1)
        super(tag)

        @site = site
        @weight = weight
        @tag = tag
      end

      # --
      def url
        File.join(*tag_path)
      end

      # --
      # @return [[]] the tags.
      # Loop through tags, set them up and then, pass
      #   them back out.
      # --
      def self.to_tags(site:)
        div = 4.0 / site.tags.values.max_by(&:size).size
        site.tags.each_with_object([]) do |(k, v), o|
          weight = format("%.2f", div * v.size)

          o << new(k, {
            weight: weight.to_f,
            site: site,
          })
        end
      end
    end
  end
end
```

## Liquid

```liquid
  <ul class="tags">
    {% assign tags = site.tags | keys %}
    {% for tag in tags %}
    <li style="font-size: {{ tag.weight }}em" class="weight-{{ tag.weight | floor }}">
      <a title="Tag: {{ tag }}" href="{{ tag.url | pretty }}">
        {{ tag | klass }} - {{ tag }}
      </a>
    </li>
    {% endfor %}
  </ul>
```

## Results in no `weight`, or `url`.

```html
<ul class="tags">    
  <li style="font-size: em" class="weight-0">
    <a title="Tag: hstore" href="">
      EnvyGeeks::Drops::Tag - hstore
    </a>
  </li>
</ul>
```

## Additional

```ruby
[1] pry(main)> tags.first.is_a?(String) # => true
[2] pry(main)> tags.first.class #=> EnvyGeeks::Drops::Tag
[3] pry(main)> tags.first.class.respond_to?(:invokable?) => true
[4] pry(main)> tags.first.is_a?(Liquid::Drop) # => true
[5] pry(main)> tags.first == "hstore" # => true
```

## But Why?

Because we want to optimize Jekyll (this is not officially sanctioned) and we can can actually convert the entirety of Jekyll's tags into drops and match them by strings in a `Hash` while also passing those back into Liquid without having to create, recreate, and otherwise slow down Ruby.  It's all about optimization when you have thousands of builds going on at once.

```ruby
[1] pry(main)> s.tags.class #=> Hash
[2] pry(main)> s.class # => Jekyll::Site
[3] pry(main)> s.tags.keys.first.class # => EnvyGeeks::Drops::Tag
[4] pry(main)> s.tags.keys.first.hash == "hstore".hash
[5] pry(main)> s.tags["ruby"].size # => 11
```

## Notes

I'm pretty sure I did something wrong but I'm not so sure.

**Comment by envygeeks** [comment]
It's because `#key?` was missing...  Perhaps Liquid could check for it's own methods?

**Comment by pushrax** [comment]
That would be an antipattern for sure, if an object overrides `is_a?` then it's up to the object to make it really does act like it says.

**Comment by envygeeks** [comment]
What just happened? None of what was just said makes sense.

**Comment by fw42** [comment]
Why not actually subclass from `Liquid::Drop` like intended instead of trying to be smart about it? I have to agree that overwriting `is_a?` seems very hacky and I'm not surprised that something breaks because of it.

**Comment by wolffy** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  stevenwolffy@gmail.com
    Domain wolffy.net has exceeded the max emails per hour (210/200 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:34169 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by cowberry.viviotech.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.89)
	(envelope-from <noreply@github.com>)
	id 1dgErG-000KnS-3x
	for steven@wolffy.net; Fri, 11 Aug 2017 11:40:32 -0700
Date: Fri, 11 Aug 2017 11:39:48 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1502476788;
	bh=HHeOWxZz7ssX38Of7Ly8JTH9rnyyNmaKG4vYnhMPpN0=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1gZr8DPL0EyMmSHPsP+Q8xmHG2cRa6C+mTZCCAmauP0xWq2ZnZHl2JrGIUoY4oN9h
	 8ua4u1SVVUi5gHxZkWP8tH1nu9f/Hva9znKz0Q5PGI0xSFFev5y8r6KQ6QnTiZI0lb
	 7zZqpWbhTK5nERhMNj9tbLeDyg48NTHi7Y1EuUqI=

**Comment by envygeeks** [comment]
@fw42 you can't sub-class from two classes in Ruby.  This isn't about `String#is_a?` which doesn't break anything at all... :roll_eyes: ... it isn't an anti-pattern, it isn't bad, and at the very maximum it's unnecessary probably at most... this is about Liquid breaking a drop when it doesn't have `#key?` instead of looking for one of a couple of the methods it literally requires to run (and runs.)  The aforementioned method is a superfluous check considering it has a static value.

**Comment by fw42** [comment]
The "official" pattern for using Liquid drops is to subclass from `Liquid::Drop` and use the new subclass to encapsulate your "payload". Something like this:

```ruby
class YourDrop < Liquid::Drop
  def initialize(string)
    @string = string
  end

  def whatever
    @string.something
  end
end
```
Why would that approach not work for you?

**Comment by pushrax** [comment]
When I said antipattern, I was referring to "Perhaps Liquid could check for it's own methods?" – the API contract is that drops must be a `Liquid::Drop`, and if you pass in something that says it's a `Liquid::Drop` it would be an antipattern to check for every method and see that it actually exists.

**Comment by envygeeks** [comment]
I just read this after months...

And... you realize my class, when it sub-classes from Liquid::Drop, it wouldn't be a Liquid::Drop. It would be a descendant of Liquid::Drop, so literally everybody is breaking your contract just by making a drop with Liquid::Drop, in the first place.  And mocking something isn't an antipattern.

Nobody said check for every method, I asked if you could check for a method you actually care about and use, and need to legit actually use.  Rather than a superfluous method that only determines logic later, and has no bearing on if something can actually be a drop, or is a drop.

**Comment by fw42** [comment]
> when it sub-classes from Liquid::Drop, **it wouldn't be a Liquid::Drop. It would be a descendant** of Liquid::Drop

Check out the [documentation of `is_a?`](https://ruby-doc.org/core-2.4.2/Object.html#method-i-is_a-3F), which says:

> `is_a?(class)` Returns `true` if `class` is the class of `obj`, **or if `class` is one of the superclasses of `obj`** or modules included in `obj`.

This is the definition that Justin was referring to when he said
> (..) if you pass in something that says it's a Liquid::Drop (..)

**Comment by envygeeks** [comment]
Yeah that's all non-relevant arguing, we can argue till the day is long, but I'm unsubscribing from this thread, it's quite obvious you guys will never fix that faulty drop check and start checking for actual relevant methods, so there is no point for me to continue in this ticket.

Good day.
