### ISSUE TITLE
Flush an Array

### ISSUE THREAD

**Issue by JulienItard** [Shopify/liquid#926]
Hello,

is there any way to flush an array in Liquid ?

Thanks !

**Comment by dylanahsmith** [comment]
Do you mean empty an array?

We don't have a way to mutate arrays, but you could assign an empty array to replace the previous array assigned to a variable.  E.g. if you have a variable `foo` that holds an array, you could assign it to an empty array with `{% assign foo = nil | uniq %}`

**Comment by JulienItard** [comment]
@dylanahsmith My bad i want to `shuffle` not `flush`

**Comment by dylanahsmith** [comment]
No.  I don't think we would want to add anything non-deterministic either, since the results of rendering a template are often cached, so you likely wouldn't get the desired effect.

**Comment by JulienItard** [comment]
Good point. Thanks
