### ISSUE TITLE
String filter capitalize is not working with german umlauts

### ISSUE THREAD

**Issue by webserviceXXL** [Shopify/liquid#928]
It seems that the string filter _capitalize_ is not working with german umlauts.

```
{% assign original = "öl" %}
{% assign capitalized = original | capitalize %}
{{ capitalized }} // echo "öl" instead of "Öl"
```

**Comment by dylanahsmith** [comment]
That is a problem with String#capitalize in ruby 2.3 earlier versions.  It works as you want in ruby 2.4.
