### ISSUE TITLE
Question about process time.

### ISSUE THREAD

**Issue by holidayworking** [Shopify/liquid#931]
Hi.

I have a problem with Example 1 about process time:

Example 1
```liquid
{% for review in reviews %}
  {% for entry in entries %}
    {% assign name = entry.name %}
    {{ review[name] }}
  {% endfor %}
{% endfor %}
```

If I change it like Example 2, I know that this is faster than Example 1:

Example 2
```liquid
{% for review in reviews %}
  {{ review.title }}
  {{ review.comment }}
{% endfor %}'
```

But, I must use the Example 1 because that’s how our system design.
Are there any way we can make Example 1 faster? And we want to make it as faster as Example 2.

For reference, this is the result of benchmark.

```ruby
require 'liquid'
require 'benchmark'

template1 = <<-EOS
{% for review in reviews %}
{{ review.title }}
{{ review.comment }}
{% endfor %}'
EOS

template2 = <<-EOS
{% for review in reviews %}
{% for entry in entries %}
{% assign name = entry.name %}
{{ review[name] }}
{% endfor %}
{% endfor %}
EOS

def render(template)
  Liquid::Template.parse(template).render(
    'reviews' => [
      { 'title' => 'title0', 'comment' => 'comment0' },
      { 'title' => 'title1', 'comment' => 'comment1' },
      { 'title' => 'title2', 'comment' => 'comment2' },
      { 'title' => 'title3', 'comment' => 'comment3' },
      { 'title' => 'title4', 'comment' => 'comment4' },
      { 'title' => 'title5', 'comment' => 'comment5' },
      { 'title' => 'title6', 'comment' => 'comment6' },
      { 'title' => 'title7', 'comment' => 'comment7' },
      { 'title' => 'title8', 'comment' => 'comment8' },
      { 'title' => 'title9', 'comment' => 'comment9' }
    ],
    'entries' => [
      { 'name' => 'title' },
      { 'name' => 'comment' }
    ]
  )
end

n = 100_000
Benchmark.bm(10) do |b|
  b.report 'static' do
    n.times do
      render(template1)
    end
  end

  b.report 'dynamic' do
    n.times do
      render(template2)
    end
  end
end
```

```
$ ruby benchmark.rb
                 user     system      total        real
static      19.390000   0.180000  19.570000 ( 19.786937)
dynamic     42.590000   0.070000  42.660000 ( 42.722720)
```

Thanks.

**Comment by fw42** [comment]
Is this within Shopify? Jekyll? Your own system? If you have control over the Ruby side, there's probably some optimisations that you can make (like flattening the nested loop in Ruby instead of in Liquid).

**Comment by holidayworking** [comment]
@fw42 Thank you for replying.

> Is this within Shopify? Jekyll? Your own system?

Yes, this is our own system.

> If you have control over the Ruby side, there's probably some optimisations that you can make (like flattening the nested loop in Ruby instead of in Liquid).

Thank you for your advice. I do not understand what you mean by ‘like flattening the nested loop in Ruby instead of in Liquid’. Can you please show me some sample code?

**Comment by fw42** [comment]
You have a nested loop here (a loop within another loop):
```
{% for review in reviews %}
  {% for entry in entries %}
    {% assign name = entry.name %}
    {{ review[name] }}
  {% endfor %}
{% endfor %}
```
You could try something like this instead:
```
{% for entry in review_entries %}
  {{ entry }}
{% endfor %}
```
Then in Ruby:
```ruby
stuff = {
  'reviews' => [
    { 'title' => 'title0', 'comment' => 'comment0' },
    { 'title' => 'title1', 'comment' => 'comment1' },
    { 'title' => 'title2', 'comment' => 'comment2' },
    { 'title' => 'title3', 'comment' => 'comment3' },
    { 'title' => 'title4', 'comment' => 'comment4' },
    { 'title' => 'title5', 'comment' => 'comment5' },
    { 'title' => 'title6', 'comment' => 'comment6' },
    { 'title' => 'title7', 'comment' => 'comment7' },
    { 'title' => 'title8', 'comment' => 'comment8' },
    { 'title' => 'title9', 'comment' => 'comment9' }
  ],
  'entries' => [
    { 'name' => 'title' },
    { 'name' => 'comment' }
  ]
}
```
Something like this is what I meant by "flattening":
```ruby
review_entries = []

stuff['reviews'].each do |review|
  stuff['entries'].each do |entry|
    review_entries << review[entry['name']]
  end
end
```
The `review_entries` array now looks like this: `["title0", "comment0", "title1", "comment1", "title2", "comment2", "title3", "comment3", "title4", "comment4", "title5", "comment5", "title6", "comment6", "title7", "comment7", "title8", "comment8", "title9", "comment9"]`, and you can pass this to Liquid.

The result should be the same, but in Liquid there is only 1 loop now, which should make this a bit faster.
