### ISSUE TITLE
Page title has preceding hyphen

### ISSUE THREAD

**Issue by keyfer** [Shopify/liquid#945]
Loading https://shopify.github.io/liquid/, the page title has a preceding hyphen.

![https://screenshot.click/19-41-uj7tp-4vzli.jpg](https://screenshot.click/19-41-uj7tp-4vzli.jpg)

**Comment by pushrax** [comment]
@admhlt when you have a sec

**Comment by admhlt** [comment]
I remember this happened when I tried to create a workaround for a github-pages plugin being wonky. I'll see if I can fix it. Thanks!
