### ISSUE TITLE
Greater and smaller than operators not working in if statement

### ISSUE THREAD

**Issue by zushenyan** [Shopify/liquid#948]
Liquid version: `3.0.2` also tried the latest version `4.0.0`
OS: `Mac OS X 10.11.16`
Ruby Environment: `jruby-9.0.4.0`

These operators `>`, `>=`, `<`, `<=` seem not working in `if` statement.

Example 1
```
{% if 10 < 5 %}
what?
{% endif %}
```

Result for example 1
```
what?
```

Example 2
```
{% assign a = 10 %}
{% assign b = 5 %}
{% if a < b %}
what?
{% endif %}
```

Result for example 2
```
what?
```

However `==` and `!=` work in `if` statement and being parsed as expected results.

Did I do anything wrong or is it suppose to happen?

**Comment by dylanahsmith** [comment]
I tried the following script

```ruby
require 'liquid'

template = Liquid::Template.parse(<<-LIQUID)
{% if 10 < 5 %}
what?
{% endif %}
LIQUID
puts template.render.inspect
```
and it output `"\n"` as expected.

So the behaviour you are seeing isn't the expected behaviour, but I am not able to reproduce that behaviour.

**Comment by zushenyan** [comment]
I found it was caused by string escaping issue. `<` was escaped as `&lt;` in our app.

This issue will be closed.

Thanks for helping~

**Comment by muraliavarma** [comment]
Thank you. This was driving me nuts. Just to add on, I fixed this by "casting" my variable into a number before comparing:
```
assign foo = foo | plus: 0
if foo > 2
   ...
endif
```
