### ISSUE TITLE
cart.item.product_type is actually cart.item.product.type ??

### ISSUE THREAD

**Issue by timdmackey** [Shopify/liquid#953]
I just ran into this issue yesterday, which this old gist has already explained pretty well:
https://gist.github.com/chryton/358231aa0ca6f6fb9baf11384e77a7a7

In the cart object, why is it that a json dump of the items shows `product_type` as a key, when the actual key is `product.type`? Is it meant to be this way? I was pulling my hair out trying to reference this value in my liquid template until I stumbled across the above gist which explains the problem.

**Comment by fw42** [comment]
This GitHub repository is for issues related to the Liquid templating system, not for issues about how Liquid is being used within Shopify themes. Can you post your question in the Shopify forum or contact Shopify support?
