### ISSUE TITLE
Array reduce filter

### ISSUE THREAD

**Issue by ericcornelissen** [Shopify/liquid#965]
I've read the CONTRIBUTING guidelines but I still feel like the addition of an "Array reduce" filter could be a nice default filter, making liquid code easier to read. But feel free to close this issue if you disagree 🙂 

* * *

The reduce filter would take an array and output an array with a subset of items from the original array. It would have roughly the same functionality as the following liquid logic. Where `array` has some items, and at the end of the for-loop `new_array` has only the items from `array` that have the value `"value"`.

```liquid
{% assign new_array = "" %}
{% for item in array %}
  {% if item.key == "value" %}
    {% new_array = new_array | concat: item %}
  {% endif %}
{% endfor %}
```

A real world use case looks something like the following snippet. Where I only want the resulting HTML to have items in the list that should be displayed in this list.

```liquid
<ul>
  {% for item in array %}
    {% if item.show_in_this_list == true %}
      <li>{{ item.value }}</li>
    {% endif %}
  {% endfor %}
</ul>
```

If there was a `reduce` filter, this would look like:

```liquid
<ul>
  {% assign list_items = array | reduce: "show_in_this_list", true %}
  {% for item in list_items %}
    <li>{{ item.value }}</li>
  {% endfor %}
</ul>
```

**Comment by dyspop** [comment]
I question: does this work for deeper nests than a coerced empty string? I don't think your example code does that, though it could be done, I think.

**Comment by ericcornelissen** [comment]
Are you talking about my first snippet? I'm not sure that one works either 😅 The point of that example is that an empty array is initialized (not sure if that is even possible in Liquid) and then the items you want are added to that array.

**Comment by pekspro** [comment]
This sounds very much like the **where** filter explained here:

https://help.shopify.com/en/themes/liquid/filters/array-filters#where

**Comment by ericcornelissen** [comment]
It seems like that is exactly it, thanks @pekspro :ok_hand:

**Comment by netitgo** [comment]
by the way, how can I filter the search results which is returned as an array?
`assign filtered_items = search.results | where: 'tags', 'hidden_product'`
the result is just blank, and I guess that's because the `tags` return an array, and the second arg failed to compare as a string.
then is there any advice in my case to retrieve an array after remove the products that contain the `hidden_product` tag?
