### ISSUE TITLE
Slow backend

### ISSUE THREAD

**Issue by gin1090** [Shopify/liquid#967]
Hi Shopify team,
I'm the developer who developed the new theme for Memoi. I've built a feature with Section and it seems to work fine with my laptop. But my client reported that it was too slow when adding or manipulating with this feature in the backend. I tested with my laptop and PC but it's still working fine. Please refer to the attached record from my client for the issue.
[Adding Swatch Slow.mp4.zip](https://github.com/Shopify/liquid/files/1600799/Adding.Swatch.Slow.mp4.zip)

**Comment by fw42** [comment]
Please contact the Shopify support team about this. This GitHub repository is about the Liquid project, not about Shopify themes.

**Comment by gin1090** [comment]
Thanks anyway @fw42, I got here by an email from Shopify support team @@
