### ISSUE TITLE
Whitespace filter trim whitespace inside string

### ISSUE THREAD

**Issue by bakura10** [Shopify/liquid#971]
Hi,

It seems that the whitespace control trims whitespace where it shouldn't within Shopify system:

```liquid
{%- capture bgset -%}{{ 'test' }} [--phone]{%- endcapture -%}
```

Result:

test[--phone]

Expected result (space after test and literal should be preserved):

test [--phone]

Thanks!

**Comment by dylanahsmith** [comment]
Looks like this is actually a bug in [liquid-c](https://github.com/shopify/liquid-c)

**Comment by bakura10** [comment]
Do you want me to report the same issue there? :)

**Comment by dylanahsmith** [comment]
I'll just open a PR there.  Will need to create regression test on this repo anyways.

**Comment by pushrax** [comment]
Good catch, thanks for the report.

**Comment by dylanahsmith** [comment]
The fix has been deployed for Shopify
