### ISSUE TITLE
Docs: Last navigation links are hidden in Firefox

### ISSUE THREAD

**Issue by DirtyF** [Shopify/liquid#973]
```gherkin 
Given I browse https://shopify.github.io/liquid/filters/ in latest Firefox
When I scroll down to the bottom on the navigation links 
Then last filters are hidden
```

![liquid-documentation](https://user-images.githubusercontent.com/103008/35384231-ee1d97d4-01c4-11e8-948d-12e85f3d939e.png)

Navigation links are well displayed in Google Chrome.

## Expected behavior:

The following filters are accessible in the sidebar:

- upcase
- url_decode
- url_encode

**Comment by adamhollett** [comment]
Thanks Frank — I'll see if I can figure out what's going on here.

**Comment by DirtyF** [comment]
This issue has been fixed.
