### ISSUE TITLE
where with undefined variable

### ISSUE THREAD

**Issue by ludusrusso** [Shopify/liquid#975]
Hi,
I've an array `posts` that may have an undefined variable (`hidden`).

Actually, I use it in this way:
```
{% for post in posts %}
{% if post.hidden != true %}
DO SOMETHING
{% endif %}
{% endfor %}

I wander if it is possible to apply a filter like

```
{% assign no_hidden_posts = posts | where: "hidden", blank %}
```

In order to avoid the `if`!

But I don't found a working solution!

**Comment by pushrax** [comment]
https://github.com/Shopify/liquid/blob/5106466a2dc1885d0791e74652a7384d99b682f4/lib/liquid/standardfilters.rb#L190-L200

might work for you depending on what you mean by "undefined" and what a `post` is.

**Comment by ludusrusso** [comment]
Thanks
