### ISSUE TITLE
Fails to throw error on "{anything}}" and {{not keyword}}

### ISSUE THREAD

**Issue by DexiongYung** [Shopify/liquid#983]
There should be a way to check if in between "{{" and "}}" is not a keyword during parse and have the option to throw an error if so. Also there's a error message for "{{" anything "}", but not "{" anything "}}" not sure if this is deliberate.

**Comment by pushrax** [comment]
`not` is a valid identifier in Liquid at the moment:

```rb
irb(main):001:0> Liquid::Template.parse("{{ not }}").render("not" => "yes")
=> "yes"
```

Lack of error for a single `{` is intentional as it may appear in text with no intention of being parsed by Liquid.

**Comment by DexiongYung** [comment]
is there a way to check if a non-keyword is between {{}} without running render?

**Comment by pushrax** [comment]
Do you mean keyword (a builtin reserved word with meaning) or an identifier (the name of a variable or other user-definable thing)? I assume the latter: variables are not defined until `render` is called, so this is unknowable. Liquid is Turing-complete, so it is required to evaluate the template to completely know what properties it will access.
