### ISSUE TITLE
Passing parameters to include-by-variable across multiple lines

### ISSUE THREAD

**Issue by sbliven** [Shopify/liquid#994]
When including a file based on a variable name (`{% include {{file}} ... %}`), only variables from the first line are passed to the partial. Anything after the first newline is ignored. This is weird, because newlines are allowed if the filename is included explicitly.

## Minimal example

**test_lvl1.html:**
```
---
---
{% capture nextlevel %}test_lvl2.html{% endcapture %}
<style>div {border: solid 1px black; margin:1em;}</style>
<div id="lvl1">
    <h4>Level 1</h4>
    {% include {{nextlevel}} a="level 1"
       b="level 1" %}
</div>
```

**_includes/test_lvl2.html:**
```
<div id="lvl2">
    <h4>Level 2</h4>
    <blockquote>{{include|inspect}}</blockquote>
</div>
```

One would expect that both `include.a` and `include.b` would be available in the partial, but only the first one is.

**output**:
```
<style>div {border: solid 1px black; margin:1em;}</style>
<div id="lvl1">
    <h4>Level 1</h4>
    <div id="lvl3">
    <h4>Level 2</h4>
    <blockquote>{&quot;a&quot;=&gt;&quot;level 1&quot;}</blockquote>
</div>
</div>
```
<img width="365" alt="screen shot 2018-03-17 at 15 55 35" src="https://user-images.githubusercontent.com/595872/37556830-b16d0c34-29fb-11e8-93e4-6950bdfe332f.png">

**Comment by pushrax** [comment]
Judging by the use of `{{nextlevel}}` inside `{% include %}` and the rest of the syntax, I'm guessing you're using Jekyll, which has its own implementation of `{% include %}`. The relevant code is here: https://github.com/jekyll/jekyll/blob/master/lib/jekyll/tags/include.rb

**Comment by sbliven** [comment]
@pushrax Thanks. The liquid/jekyll line is really blurry to me. I've opened an issue on jekyll.
