### ISSUE TITLE
Repeatable Sections on Secondary Pages

### ISSUE THREAD

**Issue by charpun** [Shopify/liquid#999]
I have a section .liquid template that I want to be able to repeat multiple times on a non-homepage template with different content each time.

The only solution I was able to find would be to creating multiple files (i.e. section/file-1.liquid, section/file-2.liquid) with the same code. However, from a mainainablity standpoint this is far less than ideal.

Basically, I want to be able to do the following with unique content each time the section is called:

```
<section class="grid-x">
	{% for index in (1..2) %}
		<div class="cell small-12 medium-large-6">
			{% section 'custom-section' %}
		</div>
	{% endfor %}
</section>
```

And have my section file do something like this:

```
{% assign list = section.blocks %}

{% if list.size > 0 %}
	<section>
		{% if section.settings.title %}
			<h2>{{ section.settings.title }}</h2>
		{% endif %}

		<ul>
			{% for item in list %}
				{% if item.settings.title %}
					<li>
						{% if  item.settings.icon %}
							<span class="icon-area" aria-hidden="true">
								<i class="icon icon-{{ item.settings.icon }}"></i>
							</span>

							<span>{{ item.settings.title }}</span>
						{% endif %}
					</li>
				{% endif %}
			{% endfor %}
		</ul>
	</section>
{% endif %}
```

And that section to appear twice on one page and again on another page with different content in each.

This doesn't seem to work. Am I missing something?

**Comment by charpun** [comment]
![bueller-e1431195418441](https://user-images.githubusercontent.com/8062104/38439395-7d90e63c-39ab-11e8-9b28-db5032cf58f5.jpg)

**Comment by husani** [comment]
+1

**Comment by adamhollett** [comment]
This repo is used for development and maintenance of the Liquid code library. Unfortunately we're not able to provide support on how to use Liquid.

If you need help using Liquid in a Shopify store, please visit the [Shopify Forums](https://ecommerce.shopify.com/c/ecommerce-design) or contact Shopify Support if it's affecting your store.

**Comment by charpun** [comment]
Well, since this does not work, consider this a feature request.

**Comment by husani** [comment]
I saw this issue as a "why isn't this functionality available in Liquid," not a question about HOW to use Liquid. Especially considering the functionality in question isn't possible in the current version.
